In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:86% !important;}
div.cell.code_cell.rendered{width:100%;}
div.CodeMirror {font-family:Consolas; font-size:15pt;}
div.output {font-size:15pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:15pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:15px;}
</style>
"""))

<font size="5" color="red">ch14. 웹데이터수집</font>
# 1절. BeautifuSoup과 parser
```pip install bs4``` 아나콘다를 설치하면 7500여개의 패키지 설치
- 공식 사이트: https://www.crummy.com/software/BeautifulSoup/
- Docs : https://www.crummy.com/software/BeautifulSoup/bs4/doc/

In [8]:
import requests #HTTP 요청 처리 lib
from requests_file import FileAdapter

In [9]:
s = requests.Session() #HTTP요청관리를 위한 세션 객체
s.mount("file://", FileAdapter())
response = s.get('file:///ai_x/lecNote/01_python/data/ch14_sample.html')
response

In [10]:
response.status_code
#200: 정상
#404: 없는 페이지
#406: get, post오류

200

In [11]:
ex = response.content #바이너리 형식의 내용
ex

b'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text"title="greeting">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90 \xec\x95\x88\xec\x9d\x98 \xeb\x82\xb4\xec\x9a\xa9</div>\r\n  <p>CSS \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\x8a\x94 \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xea\xb3\xb3\xec\x97\x90\xec\x84\x9c \xed\x99\x9c\xec\x9a\xa9\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4</p>\r\n  <div class="contents">\r\n    \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\xa5\xbc \xec\x96\xb4\xeb\x96\xbb\xea\xb2\x8c \xec\x9e\x91\xec\x84\xb1\xed\x95\x98\xeb\x8a\x90\xeb\x83\x90\xec\x97\x90 \xeb\x94\xb0\xeb\x9d\xbc\r\n    <span>\xeb\x8b\xa4\xeb\xa5\xb8<b>\xec\x9a\x94\xec\x86\x8c\xea\xb0\x80 \xeb\xb0\x98\xed\x99\x98</b></span>\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4\r\n  </div>\r\n  <div>CSS \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\x8a\x94 \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xea\xb3\xb3\xec\x97\x90 <b>\xed\x99\x9c\xec\x9a\xa9</b>\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4</div>\r\n</body>\r\n</html>'

In [12]:
ex.decode('utf-8')

'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text"title="greeting">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject 선택자 안의 내용</div>\r\n  <p>CSS 선택자는 다양한 곳에서 활용됩니다</p>\r\n  <div class="contents">\r\n    선택자를 어떻게 작성하느냐에 따라\r\n    <span>다른<b>요소가 반환</b></span>됩니다\r\n  </div>\r\n  <div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>\r\n</body>\r\n</html>'

In [13]:
response.text

'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text"title="greeting">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject 선택자 안의 내용</div>\r\n  <p>CSS 선택자는 다양한 곳에서 활용됩니다</p>\r\n  <div class="contents">\r\n    선택자를 어떻게 작성하느냐에 따라\r\n    <span>다른<b>요소가 반환</b></span>됩니다\r\n  </div>\r\n  <div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>\r\n</body>\r\n</html>'

In [4]:
#html 파싱
from bs4 import BeautifulSoup
soup = BeautifulSoup(response.content, #response.text
                    "html.parser")
soup

<!DOCTYPE html>

<html lang="ko">
<head>
<meta contents="always" name="referrer"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="챗지피티의 지식iN Q&amp;A 검색결과입니다. 궁금증을 해결하지 못했다면 지식iN '질문하기'를 해보세요." name="description">
<meta content="width=1024" name="viewport"/>
<meta content="none" name="msapplication-config">
<link href="https://ssl.pstatic.net/static.kin/static/pc/20250528165456/css/min/common.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/static.kin/static/pc/20250528165456/css/min/components.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/static.kin/static/pc/20250528165456/css/min/other.css" rel="stylesheet" type="text/css"/>
<script>

	var pcDomain = "kin.naver.com";
	var pcDomainWithProtocol = "https://kin.naver.com";
	var pcKinServiceProtocol = "https";

	var mobileDomain = "m.kin.naver.com";
	var mobileDomainWithProtocol = "https://m.kin.naver.com";
	var mobileKinServiceProtocol = "https";

	var uploadDomain = "upload.kin.naver.com";
	var uploadDomainWithProtocol = "https://upload.kin.naver.com";
	var uploadKinServiceProtocol = "https";
</script>
<script src="https://ssl.pstatic.net/static.kin/static/pc/20250528165456/js/min/kin.js" type="text/javascript"></script>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="noindex,nofollow" name="robots">
<meta content="챗지피티 검색결과 : 네이버 지식iN" property="og:title">
<meta content="https://kin.naver.com/search/list.naver?query=%EC%B1%97%EC%A7%80%ED%94%BC%ED%8B%B0&amp;page=3" property="og:url"/>
<meta content="https://ssl.pstatic.net/static/kin/common/kin_thumbnail_new_w1000.png" property="og:image"/>
<meta content="챗지피티의 지식iN Q&amp;A 검색결과입니다. 궁금증을 해결하지 못했다면 지식iN '질문하기'를 해보세요." property="og:description"/>
<meta content="네이버 지식iN" property="og:article:author"/>
<meta content="https://kin.naver.com" property="og:article:author:url"/>
<link href="/favicon.ico?v=2.4" rel="shortcut icon" type="image/x-icon"/>
<title>
	챗지피티 검색결과 : 지식iN
</title>
<script type="text/javascript">

if ( typeof window.nhn  == "undefined" ) window.nhn = {};
if ( typeof window.naver  == "undefined" ) window.naver = {};
nhn.isLogin = false;
nhn.isJunior = ("N"=="Y");
nhn.isKinUser = false;
nhn.isPortableDevice = false;
nhn.jsDir = 'https://ssl.pstatic.net/static.kin/static/pc/20250528165456/js/min';

var g_ssc = ("kin.search" == "") ? "kin.temp" : "kin.search";
var ccsrv="cc.naver.com";


var kinRos = {
	bIsNoticeDisplay : ("false" == "" || "false" == "false") ? false : true,
	bIsActionNoticeDisplay : ("false" == "" || "false" == "false") ? false : true

};





var standardReportPopupUrl = "https://srp2.naver.com/report";


var baUserKey = "__UNKNOWN__";
var baLogEndpoint = "https://scv-kin.io.naver.com/jackpotlog/v1/logs";
var baAbTestResult = null;
</script>
</meta></meta></meta></meta></head>
<body>
<div id="loadingIndicator" style="display:none;width:100%;height:100%;position:fixed;top:0px;left:0px;background-color:transparent;z-index:10000;">
<img alt="데이터 요청 응답 대기중" height="21" src="https://ssl.pstatic.net/static/kin/m/ico_lod2.gif" style="position:absolute;top:49%;left:49%;" width="21"/>
</div>
<div class="wrap wrap_search" id="wrap">
<div class="skip_nav header_gnb_inner">
<a class="skip" href="#gnb" onclick="nhn.Kin.Utility.skipNavigation('au_lnb_home');return false;">메인 메뉴 바로가기</a>
<a class="skip" href="#s_content" onclick="nhn.Kin.Utility.skipNavigation('s_content');return false;">본문 바로가기</a>
</div>
<div class="header_wrap">
<div aria-labelledby="ieUpdateBannerTitle" class="popup popup--header_notice" id="ieUpdateBanner" role="dialog" style="display: none;">
<h1 class="blind" id="ieUpdateBannerTitle" tabindex="0">권장 브라우저 업데이트 안내</h1>
<div class="popup__content">
<div class="popup__title">
<p class="popup__title_text"><span class="ico_alert sp_common"></span>권장 브라우저 안내</p>
</div>
<div class="popup__maintext">
<p class="popup__text">혹시 아직 인터넷 익스플로러 9.0 미만 버전을 사용하고 계신가요?</p>
<p class="popup__subtext">새롭게 바뀐 지식iN Q&amp;A 페이지는 IE 9.0 이상의 브라우저에 최적화되어 있습니다. 원활한 이용을 위해 꼭 업데이트 해주세요! <a class="popup__link" href="https://support.microsoft.com/ko-kr/help/17621/internet-explorer-downloads" target="_blank">업데이트하기 <span class="sp_common ico_arr_lnk"></span></a></p>
</div>
</div>
</div>
<script type="text/javascript">
	// IE8 이하이면 브라우저 버전을 올려달라는 배너를 노출한다.
	$Fn(function() {
		var oAgent = jindo.$Agent().navigator();
		if (oAgent.ie && (oAgent.version >= 6 && oAgent.version < 9)) {
			if (typeof naver.kin.SimpleBanner !== "undefined") {
				var oIeUpdateBanner = new naver.kin.SimpleBanner({
					sBannerId: "ieUpdateBannerArea"
				});
			}
		}
	}, this).attach(document, 'domready');
</script>
<div class="header_gnb">
<div class="header_gnb_inner">
<div class="header_gnb__cell">
<h1 class="header_logo">
<a class="logo_naver" href="http://www.naver.com" onclick="nhn.Kin.Utility.nClicks('STA.naverlogo', '', '', event);" title="나의 경쟁력, 네이버"><span class="blind">NAVER</span></a>
</h1>
<div class="header_search">
<h2 class="logo_wrap">
<a class="icon_logo_kin" href="/" onclick="nhn.Kin.Utility.nClicks('STA.kin', '', '', event);"><span class="blind">지식iN</span></a>
</h2>
<h3 class="blind">검색영역</h3>
<form action="/search/list.naver" id="topSearch" method="get" name="topSearch" onsubmit="return checkQuery();">
<fieldset>
<legend>지식인 검색</legend>
<div class="search_area">
<input accesskey="s" aria-autocomplete="list" aria-controls="atcmpList" aria-expanded="false" aria-haspopup="listbox" autocomplete="off" class="search_input" id="nx_query" maxlength="255" name="query" onclick="nhn.Kin.Utility.nClicks('STA.search', '', '', event);return false;" role="combobox" title="검색어 입력" type="text" value="챗지피티"/>
<a class="search_auto" href="#">
<span class="sp_gnb icon_arrow" id="triangleBtn">자동완성 열기</span>
</a>
<div>
<iframe class="auto_complete_box" frameborder="0" height="193px" id="autoFrame" marginheight="0" marginwidth="0" scrolling="no" title="검색어 자동완성" width="290"></iframe>
</div>
<a class="search_btn" href="#" onclick="return checkQuery();"><span class="sp_gnb icon_search">지식iN 검색</span></a>
</div>
</fieldset>
</form>
</div>
</div>
<div class="header_gnb__cell">
<div class="gnb_wrap">
<div class="gnb_eXpertLogo">
<a aria-controls="bannerExpert" aria-expanded="true" aria-haspopup="true" class="link" href="https://expert.naver.com" id="bannerLink" target="_blank">
<span class="logo"><span class="blind">eXpert</span></span>
</a>
</div>
<div class="gnb_common_area">
<div id="gnb">
<script type="text/javascript">

								var gnb_service = "kin";

								var gnb_logout = encodeURIComponent("https://nid.naver.com/nidlogin.logout");

								var gnb_login = encodeURIComponent(location.href || 'https://kin.naver.com');

								var gnb_template = "gnb_utf8";

								var gnb_item_hide_option = 0;




							</script>
<script charset="utf-8" src="https://ssl.pstatic.net/static.gn/templates/gnb_utf8.nhn?2025052910" type="text/javascript"></script>
</div>
</div>
</div>
<div class="header__rolling rolling-notice">
<i class="icon_speaker"><span class="blind">실시간 공지사항</span></i>
<ul class="rolling-notice__list _rolling_banner" id="listNotice">
<li class="rolling-notice__item _rollingItem" data-start-time="2023-07-03 00:00:00" style="display:none;">
<a class="rolling-notice__link" href="https://m.expert.naver.com/mobile/expert/account/join/hub" onclick="nhn.Kin.Utility.nClicks('STA.event', '', '', event);">
<i class="icon_new_red _newMark" style="display:none;"><span class="blind">새소식</span></i>
<span class="text-color--secondary">지식iN은 누구나 엑스퍼트</span><br/>
</a>
</li>
</ul>
</div>
</div>
</div>
</div>
<!-- nav -->
<div class="nav" role="navigation">
<div class="nav_inner">
<h3 class="blind">메인 메뉴</h3>
<ul class="nav_list" id="au_lnb" role="menubar">
<li class="menu" role="presentation">
<a class="item" href="/index.naver" id="au_lnb_home" onclick="nhn.Kin.Utility.nClicks('LNB.home', '', '', event);" role="menuitem" tabindex="0"><em>홈</em></a>
</li>
<li class="menu" role="presentation">
<a aria-expanded="false" aria-haspopup="true" class="item" href="/qna/list.naver" onclick="nhn.Kin.Utility.nClicks('LNB.qna', '', '', event);" role="menuitem" tabindex="-1"><em>Q&amp;A</em></a>
<ul class="nav_sub_list _lnbSubMenu" role="menu">
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=11" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '11', '1', event);" role="menuitem" tabindex="-1">교육, 학문</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=1" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '1', '2', event);" role="menuitem" tabindex="-1">IT/테크</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=2" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '2', '3', event);" role="menuitem" tabindex="-1">게임</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=3" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '3', '4', event);" role="menuitem" tabindex="-1">엔터테인먼트, 예술</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=8" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '8', '5', event);" role="menuitem" tabindex="-1">생활</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=7" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '7', '6', event);" role="menuitem" tabindex="-1">건강</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=6" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '6', '7', event);" role="menuitem" tabindex="-1">사회, 정치</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=4" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '4', '8', event);" role="menuitem" tabindex="-1">경제</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=9" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '9', '9', event);" role="menuitem" tabindex="-1">여행</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=10" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '10', '10', event);" role="menuitem" tabindex="-1">스포츠, 레저</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=5" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '5', '11', event);" role="menuitem" tabindex="-1">쇼핑</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=13" onclick="nhn.Kin.Utility.nClicks('LNB.jun', '', '', event);" role="menuitem" tabindex="-1">쥬니버Q&amp;A</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=12" onclick="nhn.Kin.Utility.nClicks('LNB.loc', '', '', event);" role="menuitem" tabindex="-1">지역&amp;플레이스</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=20" onclick="nhn.Kin.Utility.nClicks('LNB.talk', '', '', event);" role="menuitem" tabindex="-1">고민Q&amp;A</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/opendic/index.naver" onclick="nhn.Kin.Utility.nClicks('LNB.open', '', '', event);" role="menuitem" tabindex="-1">오픈사전</a></li>
</ul>
</li>
<li class="menu" role="presentation">
<a class="item" href="/qna/questionList.naver" onclick="nhn.Kin.Utility.nClicks('LNB.answer', '', '', event);" role="menuitem" tabindex="-1"><em>답변하기</em></a>
</li>
<li class="menu" role="presentation">
<a class="item" href="/volunteer/index.naver" onclick="nhn.Kin.Utility.nClicks('LNB.donation', '', '', event);" role="menuitem" tabindex="-1"><em>지식기부</em></a>
</li>
<li class="menu" role="presentation">
<a class="item" href="/people/elite/index.naver?from=lnb" id="peopleLnbBtn" onclick="nhn.Kin.Utility.nClicks('LNB.people', '', '', event);" role="menuitem" tabindex="-1"><em>사람들</em></a>
</li>
<li class="menu" role="presentation">
<a class="item" href="/best/listaha.naver" onclick="nhn.Kin.Utility.nClicks('LNB.best', '', '', event);" role="menuitem" tabindex="-1"><em>베스트</em></a>
</li>
<li class="menu" role="presentation">
<a class="item" href="/hall/index.naver" onclick="nhn.Kin.Utility.nClicks('LNB.honor', '', '', event);" role="menuitem" tabindex="-1"><em>명예의전당</em></a>
</li>
<li class="menu" role="presentation">
<span class="lnb_bar">|</span>
<a class="item" href="/myinfo/index.naver" onclick="nhn.Kin.Utility.nClicks('LNB.profile', '', '', event);" role="menuitem" tabindex="-1"><em>프로필</em></a>
</li>
<li class="menu" role="presentation">
<a class="item" href="/partnercenter/index.naver" onclick="nhn.Kin.Utility.nClicks('LNB.partner', '', '', event);" role="menuitem" tabindex="-1"><em>파트너센터</em></a>
</li>
<li class="menu" role="presentation">
<a class="item" href="/roulette/home.naver" onclick="nhn.Kin.Utility.nClicks('LNB.roulette', '', '', event);" role="menuitem" tabindex="-1"><em>룰렛</em></a>
</li>
</ul>
<a class="nav__button_question _clickcode:LNB.q" href="#" onclick="nhn.Kin.checkRosAndGoUrl(event, '/qna/question.naver', '');sendBaLog(BaPcEventType.KIN_HOME_5048)" role="button"><span class="btn_inner"><i class="sp_gnb icon_pencil"></i>질문하기</span></a>
</div>
</div>
</div>
<script type="text/javascript">

	$Fn(function() {
		new naver.kin.LNB({
			'questionType' : ''
		});
	}).attach(window, 'load');

	var GNB_BRIGHTNESS_VALUE = {
		DARK_ICON : 0,
		DARK_ICON_AND_TRANSPARENCY : 1,
		BRIGHT_ICON_AND_TRANSPARENCY : 2,
		BRIGHT_ICON : 3
	};

	var GNB_ITEM_HIDE_OPTION_BIT_VALUE = {
		DEFAULT : 0,
		HIDE_LOGIN_BTN : 1,
		HIDE_USER_LAYER : 2,
		HIDE_NAVER_ME_AREA : 4,
		HIDE_MAIL_ALARM_AREA : 8,
		HIDE_PROFILE_IMAGE : 16,
		SHOW_BENEFIT_FOR_STAFF_MEMBER : 32
	};


	var smartSearch = "";

	var gnb_service = "kin";

	var gnb_logout = encodeURIComponent("https://nid.naver.com/nidlogin.logout");

	var gnb_login = encodeURIComponent(location.href || 'https://kin.naver.com');

	var gnb_template = "gnb_utf8";

	var gnb_item_hide_option = GNB_ITEM_HIDE_OPTION_BIT_VALUE.DEFAULT;





	$Fn(function() {

		getGNB();

		var bIsGnbClicked = false;


		$Fn(function (we) {
			if (!bIsGnbClicked) {
				gnbAllLayerClose();
			}

			bIsGnbClicked = false;
		}, this).attach(document.body, 'click');

		$Fn(function(we) {
			bIsGnbClicked = true;
		}, this).attach($('gnb'), 'click');


		try {
			$('autoFrame').src = '/static/reatcmp.html?v=4.1';
		} catch(e) {
		}

		smartSearch = new nhn.AjaxSuggestUS('nx_query', 'autoFrame', {
			url : 'https://ac.search.naver.com/nx/ac',
			cookieName : 'NaverSuggestUse',
			listbox : '_resultBox',
			sFromName : 'topSearch',
			triangleBtn : 'triangleBtn',
			sListMaxLength : 55,
			listMaxCount : 15,
			request_type : 'jsonp',
			request_data : {
				q : '{query}',
				st : '100',
				r_format : 'json',
				t_koreng : '1',
				q_enc : 'UTF-8',
				r_enc : 'UTF-8',
				r_unicode : '0',
				r_escape : '1',
				frm : 'kin'
			},
			sTriangleUpOn : 'https://ssl.pstatic.net/static/common/snb/090513/bu_arrow_up.gif',
			sTriangleUpOff : 'https://ssl.pstatic.net/sstatic/search/mypocket/v3/btn_atcmp_off_op2.gif',
			sTriangleDownOn : 'https://ssl.pstatic.net/static/common/snb/090513/bu_arrow_down.gif',
			sTriangleDownOff : 'https://ssl.pstatic.net/static/common/snb/090513/bu_arrow_down3.gif'
		}).attach({
			actSubmit : function() {
				try {
					top.selectAction(this._elForm);
				} catch(e) {
					try {
						selectAction(this._elForm);
					} catch(e) {
					}
				}

				this._elForm.submit();
			}
		});

		var expertEntryBanner = $$.getSingle("div.gnb_eXpertLogo div.banner");
		if (!!expertEntryBanner) {
			var cookie = new $Cookie();

			$Fn(function () {
				$Element(expertEntryBanner).hide();

				var newDisabledUntil = new Date().getTime() + (3 * 1000 * 24 * 60 * 60);
				cookie.set("kin_expert_entry_banner_disabled_until", newDisabledUntil, 5);
			}).attach($$.getSingle("div.gnb_eXpertLogo div.banner button.buttonCancel"), 'click');

			var disabledUntilTimestamp = new Number(cookie.get("kin_expert_entry_banner_disabled_until"));
			if (!isNaN(disabledUntilTimestamp)) {
				if (new Date().getTime() > disabledUntilTimestamp) {
					cookie.remove("kin_expert_entry_banner_disabled_until");
					$Element(expertEntryBanner).show();
				}
			} else {
				$Element(expertEntryBanner).show();
			}
		}


		if (typeof nhn.Kin.ChatMenu !== "undefined") {
			window.oChatMenu = new nhn.Kin.ChatMenu();
		}
	}).attach(window, 'load');
</script>
<div class="container-fluid" id="container">
<div class="container-fluid-content">
<div class="container-fluid-content-inner">
<div id="search_result">
<strong>'챗지피티'</strong> 에 대한 검색결과입니다.



</div>
<script type="text/javascript">
function checkAdultAuth() {
	var url = "https://" + top.location.hostname + "/search/list.naver?query=%EC%B1%97%EC%A7%80%ED%94%BC%ED%8B%B0&cs=utf8&section=kin&excludeAdultDoc=false";
	var surl = "https://" + top.location.hostname + "/search/list.naver?query=%EC%B1%97%EC%A7%80%ED%94%BC%ED%8B%B0&cs=utf8&section=kin";

	try{


			top.location.href = "https://nid.naver.com/nidlogin.login?svctype=128&a_version=2&viewtype=2&url=" + encodeURIComponent(url + "&from=search") + "&surl=" + encodeURIComponent(surl);

	} catch (e){
		history.back();
	}
}
</script>
<div class="container-fluid-content__left" id="content">
<script src="https://ssl.pstatic.net/static.kin/static/pc/20250528165456/js/min/nhn.Kin.Search.Terms.js" type="text/javascript"></script>
<div id="s_content">
<div id="scl">
<ul>
<li class="tx_depth1"><strong><a class="_nclicks:tab.kin" href="/search/list.naver?query=%EC%B1%97%EC%A7%80%ED%94%BC%ED%8B%B0§ion=kin" title="전체"><span>전체</span></a></strong></li>
<li class="tx_depth2"><a class="_nclicks:tab.qna" href="/search/list.naver?query=%EC%B1%97%EC%A7%80%ED%94%BC%ED%8B%B0§ion=qna" title="Q&amp;A"><span>Q&amp;A</span></a></li>
<li class="tx_depth3"><a class="_nclicks:tab.ency" href="/search/list.naver?query=%EC%B1%97%EC%A7%80%ED%94%BC%ED%8B%B0§ion=ency" title="오픈백과"><span>오픈백과</span></a></li>
<li>
</li></ul>
</div>
<div class="banner_suicide_stop" id="suicidalPreventionBanner" style="display:none;">
<div class="content_suicide_stop">
<h3 class="tit_suicide_stop">
<span class="blind">생명은 소중합니다.! 지금,희망을 클릭하세요.</span>
</h3>
<ul class="info_suicide_stop">
<li class="counsel_list v1">
<strong class="tit_counsel_list">전화상담</strong>
<ul class="counsel_info_list">
<li>자살예방상담전화 <em>109</em></li>
<li>정신건강상담전화 <em>1577-0199</em></li>
<li><a href="https://www.cyber1388.kr:447" target="_blank">청소년 HelpCall</a> <em>1388</em></li>
<li><a href="https://www.lifeline.or.kr" target="_blank">한국생명의전화</a> <em>1588-9191</em></li>
<li>한마음한몸자살예방센터 <em>1577-0199</em></li>
</ul>
</li>
<li class="counsel_list v2">
<strong class="tit_counsel_list">온라인상담</strong>
<ul class="counsel_info_list">
<li><a href="https://www.lifeline.or.kr" id="btn_suicide_stop" target="_blank">한국생명의전화</a></li>
<li><a href="https://www.cyber1388.kr:447" target="_blank">청소년사이버상담센터</a></li>
</ul>
</li>
<li class="counsel_list v3">
<strong class="tit_counsel_list">지식iN도 여러분을 돕습니다.</strong>
<ul class="counsel_info_list">
<li><a href="/qna/question.naver?expertType=doctor&amp;dirId=70109" target="_blank">의사에게질문하기</a></li>
<li><a href="/profile/index.naver?u=6oCfeacJKVQGwsBB7OHEIS4miiPixwQ%2FoueervNeYrg%3D" target="_blank">여성가족부. 한국청소년상담복지개발원</a></li>
<li><a href="/profile/index.naver?u=9xhBJX%2Fe3worDHM4Tp9d%2F4jUxoIMOWjkBn9VK4u3x8M%3D" target="_blank">경기도청소년상담복지센터</a></li>
<li class="list_aside"><a href="/profile/index.naver?u=m61fd7AyyTNGzdSXnfIARZMD2YrqU0TvSai8n3aIfHk%3D" target="_blank">마음상담</a></li>
<li><span class="counsel_vt">|</span><a href="/profile/index.naver?u=9AFcqSNT5xcmX%2BDwjqumdFA11U6ypJgxKXiNTqx%2FenU%3D" target="_blank">허그맘</a></li>
</ul>
</li>
</ul>
</div>
</div>
<script type="text/javascript">
	jindo.$Fn(function() {


		if(nhn.Kin.Utility.containSuicideKeywords('\uCC57\uC9C0\uD53C\uD2F0')) {

			jindo.$Element('suicidalPreventionBanner').show();
		}

In [24]:
# soup.select_one('선택자') : 해당 선택자 처음 하나만
el = soup.select_one('h1') #처음 나오는 h1태그 하나만
print('el:',el)
print('el.text:',el.text)
print('el.string:',el.string)
print('el의 속성들:',el.attrs)
print('el의 title속성:', el.attrs['title'])
print('el의 이름: ', el.name)

el: <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>
el.text: Hello, CSS
el.string: Hello, CSS
el의 속성들: {'class': ['greeting', 'css'], 'id': 'text', 'title': 'greeting'}
el의 title속성: greeting
el의 이름:  h1

In [26]:
#soup.select('선택자') : 해당 선택자 모든 앨리먼트를 리스트로
el = soup.select('h1')
print('리스트el : ', el)
print('el의 text들: ',[e.text for e in el])
print('el의 속성들: ', [e.attrs for e in el])
print('el의 class속성들 : ',[e.attrs.get('class') for e in el])

리스트el :  [<h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>]
el의 text들:  ['Hello, CSS', 'Hi, CSS']
el의 속성들:  [{'class': ['greeting', 'css'], 'id': 'text', 'title': 'greeting'}, {'class': ['css']}]
el의 class속성들 :  [['greeting', 'css'], ['css']]

In [32]:
#select_one(선택자)와 find(태그, 속성)
print('select_one: ', soup.select_one('h1.css'))
print('find: ', soup.find('h1', {'class':'css'}))
print('find: ', soup.find('h1', title='greeting'))
print()
print('select_one: ', soup.select_one('h1#text'))
print('find: ', soup.find('h1', {'id':'text'}))
print()
print('select')

select_one:  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>
find:  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>
find:  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>

select_one:  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>
find:  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>

select

In [34]:
#select(선택)와 find_all(태그, 속성)
print('모든 h1.css, span태그(select): ',
     soup.select('h1.css, span'))
print('모든 h1.css, span태그(find_all): ', 
     soup.find_all(['h1', 'span'], class_='css'))

모든 h1.css, span태그(select):  [<h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>, <span>다른<b>요소가 반환</b></span>]
모든 h1.css, span태그(find_all):  [<h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>]

In [40]:
#없는 엘리먼트 찾기
print('find_all(빈list): ', soup.find_all('a', class_='css'))
print('find(None): ', soup.find('a'))
print('select(빈list): ', soup.select('a.css'))
print('select_one(None): ', soup.select_one('a.css'))

find_all(빈list):  []
find(None):  None
select(빈list):  []
select_one(None):  None

# 2절. 정적 웹 데이터 수집(정적 웹크롤링)
- json, html, xml
## 2.1JSON파일
- request모듈(get)
- urllib.request모듈(urlopen)

In [41]:
#크롤링 허용 범위는 사이트마다 ~/roobts.txt에서 확인할 수 있습니다

In [83]:
#방법1
import requests
response = requests.get('http://api.github.com')
response, response.status_code

(<Response [403]>, 403)

In [43]:
#방법2
from urllib.request import urlopen
response = urlopen(http://api.github.com)
response

In [81]:
text = '{"속성1":"값1", "속성2":"값2"}'
type(text)

str

In [82]:
#문자(딕셔너리 타입)를 딕셔너리
#'{"속성1":"값1", "속성2":"값2"}' => {"속성1":"값1", "속성2":"값2"}
import json
json.loads(text)

{'속성1': '값1', '속성2': '값2'}

## 2.2 html파일
### 1)환율정보 가져오기(네이버->증권->시장지표)
- https://finance.naver.com/marketindex/

In [48]:
#방법1
import requests
from bs4 import BeautifulSoup
url = 'https://finance.naver.com/marketindex/'
response = requests.get(url)
#response, response.status_code
#response.content(바이너리)
#response.content.decode('cp949')
#response.text
soup = BeautifulSoup(response.text,
                    'html.parser')

In [53]:
#방법2
from urllib.request import urlopen
response = urlopen(url)
#response.status 상태코드
#response.read()
#response.read().decode('cp949')
soup = BeautifulSoup(response, #response.read()
                     'html.parser')

In [56]:
title = soup.select('h3.h_lst > span.blind')
[t.text for t in title]

['미국 USD',
 '일본 JPY(100엔)',
 '유럽연합 EUR',
 '중국 CNY',
 '달러/일본 엔',
 '유로/달러',
 '영국 파운드/달러',
 '달러인덱스',
 'WTI',
 '휘발유',
 '국제 금',
 '국내 금']

In [75]:
price = soup.select('div.head_info > span.value')
[round(float(p.text.replace(',',''))) for p in price]
[round(float(''.join(p.text.split(',')))) for p in price]

[1375, 953, 1556, 191, 144, 1, 1, 99, 61, 1633, 3300, 146218]

In [61]:
out = '1,374.70'
round(float(''.join(out.split(','))))

1375

In [63]:
round(float(out.replace(',','')))

1375

In [70]:
unit = soup.select('div.head_info > span > span.blind')
unit = [u.text for u in unit]
unit.insert(7,'')
unit

['원', '원', '원', '원', '엔', '달러', '달러', '', '달러', '원', '달러', '원']

In [71]:
status = soup.select('div.head_info > span.blind')
[t.text for t in title]
[p.text for p in price]
unit
[s.string for s in status]

['하락', '하락', '하락', '하락', '상승', '하락', '하락', '상승', '하락', '하락', '하락', '상승']

In [72]:
len(title), len(price), len(unit), len(status)

(12, 12, 12, 12)

In [76]:
for idx in range(len(title)):
    print("{}. {} : {}{} - {}".format(idx,
                                title[idx].text,
                                 price[idx].text,
                                 unit[idx],
                                 status[idx].text))

0. 미국 USD : 1,375.20원 - 하락
1. 일본 JPY(100엔) : 953.05원 - 하락
2. 유럽연합 EUR : 1,556.38원 - 하락
3. 중국 CNY : 191.04원 - 하락
4. 달러/일본 엔 : 144.3800엔 - 상승
5. 유로/달러 : 1.1342달러 - 하락
6. 영국 파운드/달러 : 1.3520달러 - 하락
7. 달러인덱스 : 99.4200 - 상승
8. WTI : 60.89달러 - 하락
9. 휘발유 : 1633.17원 - 하락
10. 국제 금 : 3300.4달러 - 하락
11. 국내 금 : 146218.18원 - 상승

In [79]:
for idx, (t, p, u, s) in enumerate(zip(title, price, unit, status)):
    print("{}. {}:{}{} - {}".format(idx+1,
                                t.text,
                               p.text,
                               u,
                               s.text))

1. 미국 USD:1,375.20원 - 하락
2. 일본 JPY(100엔):953.05원 - 하락
3. 유럽연합 EUR:1,556.38원 - 하락
4. 중국 CNY:191.04원 - 하락
5. 달러/일본 엔:144.3800엔 - 상승
6. 유로/달러:1.1342달러 - 하락
7. 영국 파운드/달러:1.3520달러 - 하락
8. 달러인덱스:99.4200 - 상승
9. WTI:60.89달러 - 하락
10. 휘발유:1633.17원 - 하락
11. 국제 금:3300.4달러 - 하락
12. 국내 금:146218.18원 - 상승

### 2) 이번주 로또번호 출력
- https://dhlottery.co.kr/gameResult.do?method=byWin google에 "로또번호 당첨번호"검색
```
1173회(2025년 05월 24일 추첨)
당첨번호 [1 5 18 20 30 35]
보너스3
```

In [84]:
# 방법1
import requests
from bs4 import BeautifulSoup
url = 'https://dhlottery.co.kr/gameResult.do?method=byWin'
response = requests.get(url)
soup = BeautifulSoup(response.text, #response.content
                    'html.parser')
soup

<!DOCTYPE html>

<html lang="ko">
<head>
<meta charset="utf-8"/>
<meta content="동행복권" id="utitle" name="title"/>
<meta content="동행복권 1173회 당첨번호 1,5,18,20,30,35+3. 1등 총 24명, 1인당 당첨금액 1,179,946,063원." id="desc" name="description"/>
<title>로또6/45 - 회차별 당첨번호</title>
<title>동행복권</title>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<link href="/images/common/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<link href="/images/common/favicon.ico" rel="icon" type="image/x-icon"/>
<script src="/js/jquery-1.9.1.min.js" type="text/javascript"></script>
<script src="/js/jquery-ui.js" type="text/javascript"></script>
<script charset="utf-8" src="/js/common.js" type="text/javascript"></script>
<script type="text/javascript">

fn_g_init_message("");

var gameUserId = "";

function goGame(){
	var userId = "";

	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login";
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert('접속이 원활하지 않습니다.');
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp("");
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function goGame(lottoId,agreeType){
	var userId = "";
	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + lottoId);
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp(lottoId,agreeType);
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function goGamePnInfo(lottoId,agreeType,svcInfoPnPcMsgYn){
	var svcInfoPnPcMsgYn = svcInfoPnPcMsgYn;

	if (svcInfoPnPcMsgYn == "Y") {
		svcInfoPnMsg();
		return;
	}

	var userId = "";
	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + lottoId);
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",  	// url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp(lottoId,agreeType);
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function goGameElInfo(lottoId,agreeType,svcInfoElPcMsgYn){
	var lottoId = lottoId;
	var svcInfoElPcMsgYn = svcInfoElPcMsgYn;

	// 2024 연마감 관련 코드
	if (svcInfoElPcMsgYn == "Y") {
		if (lottoId == "LI21") {	//20241226 sicc_kic 2024년도 트리플럭 판매종료.
			svcInfoElTrMsg();
			return;
		}
		else if (lottoId == "LI22") {  //20241125 sicc_kic 2024년도 트레져헌터 판매종료.
			svcInfoElThMsg();
			return;
		}
		else if (lottoId == "LI23") {  //20241226 sicc_kic 2024년도 캐치미 판매종료.
			svcInfoElCmMsg();
			return;
		}
		else if (lottoId == "LD10") {  //20241125 sicc_kjh 2024년도 스피드키노 판매종료.
		    svcInfoElSkMsg();
			return;
		}
		else if (lottoId == "LD11") {  //20241112 sicc_khj 2024년도 메가빙고 판매종료.
			svcInfoElMbMsg();
			return;
		}
		else if (lottoId == "LD14") {  //20241125 sicc_kic 2024년도 파워볼 판매종료.
			svcInfoElPbMsg();
			return;
		}
		else if (lottoId == "LD20") {  //20241226 sicc_kic 2024년도 더블잭  판매종료.
			svcInfoElDmMsg();
			return;
		}
		else {
			svcInfoElMsg();
			return;
		}
	}

	var userId = "";
	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + lottoId);
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",  	// url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp(lottoId,agreeType);
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function goGameEnInfo(lottoId,agreeType,endInfoElPcMsgYn){
	var endInfoElPcMsgYn = endInfoElPcMsgYn;

	if (endInfoElPcMsgYn == "Y") {
		endInfoElMsg();
		return;
	}

	var userId = "";
	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + lottoId);
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",  	// url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp(lottoId,agreeType);
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function goGameElEnInfo(lottoId,agreeType,svcInfoElPcMsgYn,endInfoElPcMsgYn){
	var svcInfoElPcMsgYn = svcInfoElPcMsgYn;
	var endInfoElPcMsgYn = endInfoElPcMsgYn;

	//2023연마감 관련 코드 (캐치미,트래져헌터 조기종료로 추가된코드.)
	if("N" == "Y"){
		if(lottoId == "LI23" || lottoId == "LI22" ) {
			//LI23: 캐치미,  LI22트레져헌터
			svcInfoElMsgEx();
			return;
		}
	}

	if (svcInfoElPcMsgYn == "Y") {
			svcInfoElMsg();
			return;
	}

	if (endInfoElPcMsgYn == "Y") {
		endInfoElMsg();
		return;
	}

	var userId = "";
	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + lottoId);
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",  	// url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp(lottoId,agreeType);
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function doGamePopUp(lotid,agreeType){
	/*
	* 스피드키노 LD10, 메가빙고 LD11, 더블잭마이더스 LD20, 파워볼 LD14, 트레져헌터 LI22, 트리플럭 LI21 -> gamePop
	* 캐치미 LI23 -> catchPop
	*/
	var type;

	if( lotid === 'LI23' ){
		type = 'catchPop';
	}else{
		type = 'gamePop';
	}

	if($("#agreeChk").is(":checked") || agreeType == 2){
		var new_popup = centerPop('https://el.dhlottery.co.kr/game/TotalGame.jsp?LottoId='+ lotid, 'type', 1164, 645, 'no');
	}else{
		alert('약관에 동의해 주셔야 이용이 가능합니다.');
		$("#agreeChk").focus();
	}

}

//설문조사 팝업
function popCenter(url){
	var new_popup =	centerPop(url, '설문조사', 480, 800, 'yes');
}

//샘플게임 팝업
function sample_pop(code, userId){

	//location.href = "/gamezone.do?method=gameZoneMainView";
	//return;
	if(userId == null || userId == ""){
		alert("로그인 후 이용이 가능합니다.");
		//location.href = "/user.do?method=login";
		//location.href = "/user.do?method=login&returnUrl=/gamezone.do?method=gameZoneMainView";
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + code);
		return;
	}
	if(!$("#sampleAgreeChk").is(":checked")){
		alert('약관에 동의해 주셔야 이용이 가능합니다.');
		$("#sampleAgreeChk").focus();
		return;
	}

	$.ajax({
		type:"POST",                            // 메소드타입
		url:"/gamezone.do?method=autoAgreeProc",// url
		dataType:"json",                        // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		async:false,
		contentType : "application/json; charset=EUC-KR",
		error: function() {                     // 에러날경우 콜백함수
			console.log("error");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(data.successYn){
				console.log(data);
			}
		}
	});

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		//data:{"jackpot":strJackpotData},   	// 파라메터 타입
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(userId == data.userId && data.userId != ""){
				var new_popup =	centerPop('https://el.dhlottery.co.kr/game_sample/TotalGame.jsp?LottoId=' + code, 'gamePop', 1164, 645, 'no');
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

//샘플게임(랜덤) 팝업
function sample_random_pop(userId){

	//location.href = "/gamezone.do?method=gameZoneMainView";
	//return;
	if(userId == null || userId == ""){
		alert("로그인 후 이용이 가능합니다.");
		location.href = "/user.do?method=login";
// 		location.href = "/user.do?method=login&returnUrl=/gamezone.do?method=gameZoneMainView";
// 		location.href = "/common.do?method=main";
		return;
	}

	var x = Math.floor((Math.random() * 7) + 1 );

	if(x == 1){
		var code = "LD14";
	}else if(x == 2){
		var code = "LD10";
	}else if(x == 3){
		var code = "LD20";
	}else if(x == 4){
		var code = "LI23";
	}else if(x == 5){
		var code = "LI22";
	}else if(x == 6){
		var code = "LI21";
	}else if(x == 7){
		var code = "LD11";
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"/gamezone.do?method=autoAgreeProc",// url
		dataType:"json",                        // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		async:false,
		contentType : "application/json; charset=EUC-KR",
		error: function() {                     // 에러날경우 콜백함수
			console.log("error");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(data.successYn){
				console.log(data);
			}
		}
	});

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		//data:{"jackpot":strJackpotData},   	// 파라메터 타입
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(userId == data.userId && data.userId != ""){
				var new_popup =	centerPop('https://el.dhlottery.co.kr/game_sample/TotalGame.jsp?LottoId=' + code , 'gamePop', 1164, 645, 'no');
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}



function doReserve(){
	var userId = "";

	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		//location.href = "/user.do?method=login";
		location.href = "/user.do?method=login&returnUrl=/gameInfo.do?method=game720Method";
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(userId == data.userId && data.userId != ""){
					window.open('https://el.dhlottery.co.kr/lotto720.do?method=reserveBuy', 'pensionPop' , 'width=930, height=672, left=0, top=0, status=no, toolbar=no, menubar=no, location=no');
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});

}


function jackpotViewPop(){
	var url = "/gameInfo.do?method=jackpotView&lottoId=";
	commonPop("", url, 820, 700, 'yes');
}

function goLottoBuy(agreeType){
	var userId = "";

	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		//location.href = "/user.do?method=login";
		location.href = "/user.do?method=login&returnUrl=/gameInfo.do?method=buyLotto";
		return;
	}
	if(agreeType == 1 && !$("#agreeChk").is(":checked")){
		alert('약관에 동의해 주셔야 이용이 가능합니다.');
		$("#agreeChk").focus();
		return;
	}


	 $.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(userId == data.userId && data.userId != ""){
				var new_popup = centerPop('https://el.dhlottery.co.kr/game/TotalGame.jsp?LottoId=LO40', 'gamePop', 1164, 645, 'no');
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});

}

function loginType(pageCode){
	var userId = "";
	var pageCodes = pageCode.split("-");
}

//엔터만 치면 로그인
function enter_check_top(eventValue) {
	if (eventValue == 13) {
		check_if_Valid_top();
		return;
	}
}

function depositAlert(){
	alert("12월 2일 이후부터 사용 가능합니다.");
}

function check_if_Valid_top() {
	var f = document.frmLogin;

	if (f.userId.value == "") {
		alert("아이디를 입력해 주십시오");
		f.userId.focus();
		return;
	}
	if (f.password.value == "") {
		alert("비밀번호를 입력해 주세요");
		f.password.focus();
		return;
	}
	if (f.userId.value.length >= 15) {
		alert("아이디가 자릿수가 초과되었습니다.");
		return;
	}
	if (f.password.value.length >= 101) {
		alert("비밀번호가 자릿수가 초과되었습니다.");
		return;
	}
	loginpage_top();
}

function loginpage_top(){

	var f = window.document.frmLogin;
	var pageUrl = document.location.href;
	var returnUrl="";

	f.method = "post";
	//f.target = "jform";
	if(returnUrl != ''){
		f.action = "https://www.dhlottery.co.kr/userSsl.do?method=login&returnUrl="+encodeURIComponent(returnUrl);
	}else{
		f.action = "https://www.dhlottery.co.kr/userSsl.do?method=login&returnUrl="+encodeURIComponent(pageUrl);
	}
	f.submit();

}

function getCookie(uName) {
	var flag = document.cookie.indexOf(uName + '=');
	if (flag != -1) {
		flag += uName.length + 1;
		end = document.cookie.indexOf(';', flag);
		if (end == -1)
			end = document.cookie.length;
		return unescape(document.cookie.substring(flag, end));
	}
}

function gomain() {
	location.href="/common.do?method=main";
}

$(document).ready(function() {
	$("#phoneTopMenu").html("");

	if(getCookie("userId") != undefined)
	{
		$('.top_userid').val(getCookie("userId"));
	}

});

function svcInfoPnMsg() {
	alert("일시 판매정지 중입니다.\n\n정지 일시 : 2024년 12월 31일 10시\n재개 일시 : 2025년 01월 02일");
}


function svcInfoElMsg() {
	alert("일시 판매정지 중입니다.\n\n정지 일시 : 2023년 12월 31일 09시\n재개 일시 : 2024년 01월 02일 10시");
}

//연마감용 메시지
function svcInfoElMsgEx() {
	alert("일시 판매정지 중입니다.\n\n정지 일시 : 2023년 12월 05일 00시\n재개 일시 : 2024년 01월 02일 10시");
}

//20241112 sicc_khj 2024년도 메가빙고 판매종료.
function svcInfoElMbMsg() {
	alert("메가빙고 복권은 판매종료 합니다.\n\n판매종료 일시 : 2024년 11월 13일 00시 \n판매재개 일시 : 2025년 01월 02일 ");
}

// 20241125 sicc_kic 2024년도 파워볼 판매종료.
function svcInfoElPbMsg() {
	alert("파워볼 복권은 판매종료 합니다.\n\n판매종료 일시 : 2024년 12월 16일 00시 \n판매재개 일시 : 2025년 01월 02일");
}
//20241212 sicc_kic 2024년도 트레져헌터 판매종료.
function svcInfoElThMsg() {
	alert("트레져헌터 복권은 판매종료 합니다.\n\n판매종료 일시 : 2024년 12월 23일 00시 \n판매재개 일시 : 2025년 01월 02일");
}

//20241217 sicc_kjh 2024년도 스피드키노 판매종료.
function svcInfoElSkMsg() {
	alert("스피드키노 복권은 판매종료 합니다.\n\n판매종료 일시 : 2024년 12월 23일 00시 \n판매재개 일시 : 2025년 01월 02일");
}

//20241226 sicc_kic 2024년도 트리플럭 판매종료.
//--25회차 수정
function svcInfoElTrMsg() {
	alert("트리플럭 복권은 판매 정지 중입니다.\n\n정지일시 : 2024년 12월 31일 10시 \n재개 일시 : 2025년 01월 02일");
}

//20241226 sicc_kic 2024년도 더블잭 판매종료.
function svcInfoElDmMsg() {
	alert("더블잭 마이더스 복권은 판매 정지 중입니다.\n\n정지일시 : 2024년 12월 31일 10시 \n재개 일시 : 2025년 01월 02일 ");
}

//20241226 sicc_kic 2024년도 캐치미 판매종료.
function svcInfoElCmMsg() {
	alert("캐치미 복권은 판매 정지 중입니다.\n\n정지일시 : 2024년 12월 31일 10시 \n재개 일시 : 2025년 01월 02일 ");
}
function endInfoElMsg() {
	alert("판매시간이 아닙니다.\n\n판매 시간 : 06시 ~ 24시");
}

</script>
<!-- <link rel="stylesheet" type="text/css" href="/css/nanum_gothic_dev.css" /> -->
<link href="/css/styles.css" rel="stylesheet" type="text/css"/>
<script charset="utf-8" src="/js/function.js" type="text/javascript"></script>
<script charset="utf-8" src="/js/InsertFlash.js" type="text/javascript"></script>
<script charset="utf-8" src="/js/link.js" type="text/javascript"></script>
<script charset="utf-8" src="/js/makePCookie.js" type="text/javascript"></script>
<script src="/js/jquery.cookie.js" type="text/javascript"></script>
<script src="/js/webfont.js" type="text/javascript"></script>
<script>
if (navigator.platform && /win16|win32|win64|mac/ig.test(navigator.platform) == false) {
	if ('https://m.dhlottery.co.kr'.indexOf(location.hostname) == -1 || 'https://m.dhlottery.co.kr'.indexOf(location.hostname) == -1 ) {
	  	location.href = 'https://m.dhlottery.co.kr';
	}
}
</script>
<script>
var pageCode = "03-01-01";
var pageName = "회차별 당첨번호";

var hdrw = 1;
function search() {
	$('#drwNo').val($("#dwrNoList").val());
	$("#frm").attr({action:"/gameResult.do?method=byWin", method:"post"}).submit();
}

$(document).ready(function() {

	if("1173" != ""){
		$("#dwrNoList").val("1173");
		if ("1173" < 601) hdrw = 2;
	}
	$('#searchBtn').click(function(e) {
		search();
	});
	$('#printBtn').click(function(e) {
		e.preventDefault();
		commonPop("stat_pop", "/gameResult.do?method=allWinPrint&gubun=byWin&nowPage="+$("#nowPage").val()+"&drwNoStart="+$("#drwNoStart").val()+"&drwNoEnd="+$("#drwNoEnd").val(), "800", "750", "");
	});
	$('#exelBtn').click(function(e) {
		var search1 = $("#drwNoStart").val();
		var search2 = $("#drwNoEnd").val();
		if(parseInt(search2) < parseInt(search1)){
			alert("시작회차가 종료회차보다 큽니다.");
			$('#drwNoEnd').focus();
			return false;
		};
		location.href = "/gameResult.do?method=allWinExel&gubun=byWin&nowPage="+$("#nowPage").val()+"&drwNoStart="+$("#drwNoStart").val()+"&drwNoEnd="+$("#drwNoEnd").val();
	});
	$('#hdrwComb').click(function(e) {
		if($('#hdrwComb').val() != hdrw) {
			hdrw = $('#hdrwComb').val();
			$("#dwrNoList").empty();
			$("#drwNoStart").empty();
			$("#drwNoEnd").empty();
			var str = "";

			if(hdrw == 1) {

In [85]:
#방법2
from urllib.request import urlopen
url = 'https://dhlottery.co.kr/gameResult.do?method=byWin'
response= urlopen(url)
soup = BeautifulSoup(response,
                    'html.parser')
soup

<!DOCTYPE html>

<html lang="ko">
<head>
<meta charset="utf-8"/>
<meta content="동행복권" id="utitle" name="title"/>
<meta content="동행복권 1173회 당첨번호 1,5,18,20,30,35+3. 1등 총 24명, 1인당 당첨금액 1,179,946,063원." id="desc" name="description"/>
<title>로또6/45 - 회차별 당첨번호</title>
<title>동행복권</title>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<link href="/images/common/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<link href="/images/common/favicon.ico" rel="icon" type="image/x-icon"/>
<script src="/js/jquery-1.9.1.min.js" type="text/javascript"></script>
<script src="/js/jquery-ui.js" type="text/javascript"></script>
<script charset="utf-8" src="/js/common.js" type="text/javascript"></script>
<script type="text/javascript">

fn_g_init_message("");

var gameUserId = "";

function goGame(){
	var userId = "";

	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login";
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert('접속이 원활하지 않습니다.');
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp("");
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function goGame(lottoId,agreeType){
	var userId = "";
	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + lottoId);
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp(lottoId,agreeType);
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function goGamePnInfo(lottoId,agreeType,svcInfoPnPcMsgYn){
	var svcInfoPnPcMsgYn = svcInfoPnPcMsgYn;

	if (svcInfoPnPcMsgYn == "Y") {
		svcInfoPnMsg();
		return;
	}

	var userId = "";
	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + lottoId);
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",  	// url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp(lottoId,agreeType);
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function goGameElInfo(lottoId,agreeType,svcInfoElPcMsgYn){
	var lottoId = lottoId;
	var svcInfoElPcMsgYn = svcInfoElPcMsgYn;

	// 2024 연마감 관련 코드
	if (svcInfoElPcMsgYn == "Y") {
		if (lottoId == "LI21") {	//20241226 sicc_kic 2024년도 트리플럭 판매종료.
			svcInfoElTrMsg();
			return;
		}
		else if (lottoId == "LI22") {  //20241125 sicc_kic 2024년도 트레져헌터 판매종료.
			svcInfoElThMsg();
			return;
		}
		else if (lottoId == "LI23") {  //20241226 sicc_kic 2024년도 캐치미 판매종료.
			svcInfoElCmMsg();
			return;
		}
		else if (lottoId == "LD10") {  //20241125 sicc_kjh 2024년도 스피드키노 판매종료.
		    svcInfoElSkMsg();
			return;
		}
		else if (lottoId == "LD11") {  //20241112 sicc_khj 2024년도 메가빙고 판매종료.
			svcInfoElMbMsg();
			return;
		}
		else if (lottoId == "LD14") {  //20241125 sicc_kic 2024년도 파워볼 판매종료.
			svcInfoElPbMsg();
			return;
		}
		else if (lottoId == "LD20") {  //20241226 sicc_kic 2024년도 더블잭  판매종료.
			svcInfoElDmMsg();
			return;
		}
		else {
			svcInfoElMsg();
			return;
		}
	}

	var userId = "";
	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + lottoId);
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",  	// url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp(lottoId,agreeType);
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function goGameEnInfo(lottoId,agreeType,endInfoElPcMsgYn){
	var endInfoElPcMsgYn = endInfoElPcMsgYn;

	if (endInfoElPcMsgYn == "Y") {
		endInfoElMsg();
		return;
	}

	var userId = "";
	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + lottoId);
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",  	// url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp(lottoId,agreeType);
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function goGameElEnInfo(lottoId,agreeType,svcInfoElPcMsgYn,endInfoElPcMsgYn){
	var svcInfoElPcMsgYn = svcInfoElPcMsgYn;
	var endInfoElPcMsgYn = endInfoElPcMsgYn;

	//2023연마감 관련 코드 (캐치미,트래져헌터 조기종료로 추가된코드.)
	if("N" == "Y"){
		if(lottoId == "LI23" || lottoId == "LI22" ) {
			//LI23: 캐치미,  LI22트레져헌터
			svcInfoElMsgEx();
			return;
		}
	}

	if (svcInfoElPcMsgYn == "Y") {
			svcInfoElMsg();
			return;
	}

	if (endInfoElPcMsgYn == "Y") {
		endInfoElMsg();
		return;
	}

	var userId = "";
	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + lottoId);
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",  	// url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp(lottoId,agreeType);
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function doGamePopUp(lotid,agreeType){
	/*
	* 스피드키노 LD10, 메가빙고 LD11, 더블잭마이더스 LD20, 파워볼 LD14, 트레져헌터 LI22, 트리플럭 LI21 -> gamePop
	* 캐치미 LI23 -> catchPop
	*/
	var type;

	if( lotid === 'LI23' ){
		type = 'catchPop';
	}else{
		type = 'gamePop';
	}

	if($("#agreeChk").is(":checked") || agreeType == 2){
		var new_popup = centerPop('https://el.dhlottery.co.kr/game/TotalGame.jsp?LottoId='+ lotid, 'type', 1164, 645, 'no');
	}else{
		alert('약관에 동의해 주셔야 이용이 가능합니다.');
		$("#agreeChk").focus();
	}

}

//설문조사 팝업
function popCenter(url){
	var new_popup =	centerPop(url, '설문조사', 480, 800, 'yes');
}

//샘플게임 팝업
function sample_pop(code, userId){

	//location.href = "/gamezone.do?method=gameZoneMainView";
	//return;
	if(userId == null || userId == ""){
		alert("로그인 후 이용이 가능합니다.");
		//location.href = "/user.do?method=login";
		//location.href = "/user.do?method=login&returnUrl=/gamezone.do?method=gameZoneMainView";
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + code);
		return;
	}
	if(!$("#sampleAgreeChk").is(":checked")){
		alert('약관에 동의해 주셔야 이용이 가능합니다.');
		$("#sampleAgreeChk").focus();
		return;
	}

	$.ajax({
		type:"POST",                            // 메소드타입
		url:"/gamezone.do?method=autoAgreeProc",// url
		dataType:"json",                        // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		async:false,
		contentType : "application/json; charset=EUC-KR",
		error: function() {                     // 에러날경우 콜백함수
			console.log("error");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(data.successYn){
				console.log(data);
			}
		}
	});

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		//data:{"jackpot":strJackpotData},   	// 파라메터 타입
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(userId == data.userId && data.userId != ""){
				var new_popup =	centerPop('https://el.dhlottery.co.kr/game_sample/TotalGame.jsp?LottoId=' + code, 'gamePop', 1164, 645, 'no');
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

//샘플게임(랜덤) 팝업
function sample_random_pop(userId){

	//location.href = "/gamezone.do?method=gameZoneMainView";
	//return;
	if(userId == null || userId == ""){
		alert("로그인 후 이용이 가능합니다.");
		location.href = "/user.do?method=login";
// 		location.href = "/user.do?method=login&returnUrl=/gamezone.do?method=gameZoneMainView";
// 		location.href = "/common.do?method=main";
		return;
	}

	var x = Math.floor((Math.random() * 7) + 1 );

	if(x == 1){
		var code = "LD14";
	}else if(x == 2){
		var code = "LD10";
	}else if(x == 3){
		var code = "LD20";
	}else if(x == 4){
		var code = "LI23";
	}else if(x == 5){
		var code = "LI22";
	}else if(x == 6){
		var code = "LI21";
	}else if(x == 7){
		var code = "LD11";
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"/gamezone.do?method=autoAgreeProc",// url
		dataType:"json",                        // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		async:false,
		contentType : "application/json; charset=EUC-KR",
		error: function() {                     // 에러날경우 콜백함수
			console.log("error");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(data.successYn){
				console.log(data);
			}
		}
	});

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		//data:{"jackpot":strJackpotData},   	// 파라메터 타입
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(userId == data.userId && data.userId != ""){
				var new_popup =	centerPop('https://el.dhlottery.co.kr/game_sample/TotalGame.jsp?LottoId=' + code , 'gamePop', 1164, 645, 'no');
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}



function doReserve(){
	var userId = "";

	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		//location.href = "/user.do?method=login";
		location.href = "/user.do?method=login&returnUrl=/gameInfo.do?method=game720Method";
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(userId == data.userId && data.userId != ""){
					window.open('https://el.dhlottery.co.kr/lotto720.do?method=reserveBuy', 'pensionPop' , 'width=930, height=672, left=0, top=0, status=no, toolbar=no, menubar=no, location=no');
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});

}


function jackpotViewPop(){
	var url = "/gameInfo.do?method=jackpotView&lottoId=";
	commonPop("", url, 820, 700, 'yes');
}

function goLottoBuy(agreeType){
	var userId = "";

	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		//location.href = "/user.do?method=login";
		location.href = "/user.do?method=login&returnUrl=/gameInfo.do?method=buyLotto";
		return;
	}
	if(agreeType == 1 && !$("#agreeChk").is(":checked")){
		alert('약관에 동의해 주셔야 이용이 가능합니다.');
		$("#agreeChk").focus();
		return;
	}


	 $.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(userId == data.userId && data.userId != ""){
				var new_popup = centerPop('https://el.dhlottery.co.kr/game/TotalGame.jsp?LottoId=LO40', 'gamePop', 1164, 645, 'no');
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});

}

function loginType(pageCode){
	var userId = "";
	var pageCodes = pageCode.split("-");
}

//엔터만 치면 로그인
function enter_check_top(eventValue) {
	if (eventValue == 13) {
		check_if_Valid_top();
		return;
	}
}

function depositAlert(){
	alert("12월 2일 이후부터 사용 가능합니다.");
}

function check_if_Valid_top() {
	var f = document.frmLogin;

	if (f.userId.value == "") {
		alert("아이디를 입력해 주십시오");
		f.userId.focus();
		return;
	}
	if (f.password.value == "") {
		alert("비밀번호를 입력해 주세요");
		f.password.focus();
		return;
	}
	if (f.userId.value.length >= 15) {
		alert("아이디가 자릿수가 초과되었습니다.");
		return;
	}
	if (f.password.value.length >= 101) {
		alert("비밀번호가 자릿수가 초과되었습니다.");
		return;
	}
	loginpage_top();
}

function loginpage_top(){

	var f = window.document.frmLogin;
	var pageUrl = document.location.href;
	var returnUrl="";

	f.method = "post";
	//f.target = "jform";
	if(returnUrl != ''){
		f.action = "https://www.dhlottery.co.kr/userSsl.do?method=login&returnUrl="+encodeURIComponent(returnUrl);
	}else{
		f.action = "https://www.dhlottery.co.kr/userSsl.do?method=login&returnUrl="+encodeURIComponent(pageUrl);
	}
	f.submit();

}

function getCookie(uName) {
	var flag = document.cookie.indexOf(uName + '=');
	if (flag != -1) {
		flag += uName.length + 1;
		end = document.cookie.indexOf(';', flag);
		if (end == -1)
			end = document.cookie.length;
		return unescape(document.cookie.substring(flag, end));
	}
}

function gomain() {
	location.href="/common.do?method=main";
}

$(document).ready(function() {
	$("#phoneTopMenu").html("");

	if(getCookie("userId") != undefined)
	{
		$('.top_userid').val(getCookie("userId"));
	}

});

function svcInfoPnMsg() {
	alert("일시 판매정지 중입니다.\n\n정지 일시 : 2024년 12월 31일 10시\n재개 일시 : 2025년 01월 02일");
}


function svcInfoElMsg() {
	alert("일시 판매정지 중입니다.\n\n정지 일시 : 2023년 12월 31일 09시\n재개 일시 : 2024년 01월 02일 10시");
}

//연마감용 메시지
function svcInfoElMsgEx() {
	alert("일시 판매정지 중입니다.\n\n정지 일시 : 2023년 12월 05일 00시\n재개 일시 : 2024년 01월 02일 10시");
}

//20241112 sicc_khj 2024년도 메가빙고 판매종료.
function svcInfoElMbMsg() {
	alert("메가빙고 복권은 판매종료 합니다.\n\n판매종료 일시 : 2024년 11월 13일 00시 \n판매재개 일시 : 2025년 01월 02일 ");
}

// 20241125 sicc_kic 2024년도 파워볼 판매종료.
function svcInfoElPbMsg() {
	alert("파워볼 복권은 판매종료 합니다.\n\n판매종료 일시 : 2024년 12월 16일 00시 \n판매재개 일시 : 2025년 01월 02일");
}
//20241212 sicc_kic 2024년도 트레져헌터 판매종료.
function svcInfoElThMsg() {
	alert("트레져헌터 복권은 판매종료 합니다.\n\n판매종료 일시 : 2024년 12월 23일 00시 \n판매재개 일시 : 2025년 01월 02일");
}

//20241217 sicc_kjh 2024년도 스피드키노 판매종료.
function svcInfoElSkMsg() {
	alert("스피드키노 복권은 판매종료 합니다.\n\n판매종료 일시 : 2024년 12월 23일 00시 \n판매재개 일시 : 2025년 01월 02일");
}

//20241226 sicc_kic 2024년도 트리플럭 판매종료.
//--25회차 수정
function svcInfoElTrMsg() {
	alert("트리플럭 복권은 판매 정지 중입니다.\n\n정지일시 : 2024년 12월 31일 10시 \n재개 일시 : 2025년 01월 02일");
}

//20241226 sicc_kic 2024년도 더블잭 판매종료.
function svcInfoElDmMsg() {
	alert("더블잭 마이더스 복권은 판매 정지 중입니다.\n\n정지일시 : 2024년 12월 31일 10시 \n재개 일시 : 2025년 01월 02일 ");
}

//20241226 sicc_kic 2024년도 캐치미 판매종료.
function svcInfoElCmMsg() {
	alert("캐치미 복권은 판매 정지 중입니다.\n\n정지일시 : 2024년 12월 31일 10시 \n재개 일시 : 2025년 01월 02일 ");
}
function endInfoElMsg() {
	alert("판매시간이 아닙니다.\n\n판매 시간 : 06시 ~ 24시");
}

</script>
<!-- <link rel="stylesheet" type="text/css" href="/css/nanum_gothic_dev.css" /> -->
<link href="/css/styles.css" rel="stylesheet" type="text/css"/>
<script charset="utf-8" src="/js/function.js" type="text/javascript"></script>
<script charset="utf-8" src="/js/InsertFlash.js" type="text/javascript"></script>
<script charset="utf-8" src="/js/link.js" type="text/javascript"></script>
<script charset="utf-8" src="/js/makePCookie.js" type="text/javascript"></script>
<script src="/js/jquery.cookie.js" type="text/javascript"></script>
<script src="/js/webfont.js" type="text/javascript"></script>
<script>
if (navigator.platform && /win16|win32|win64|mac/ig.test(navigator.platform) == false) {
	if ('https://m.dhlottery.co.kr'.indexOf(location.hostname) == -1 || 'https://m.dhlottery.co.kr'.indexOf(location.hostname) == -1 ) {
	  	location.href = 'https://m.dhlottery.co.kr';
	}
}
</script>
<script>
var pageCode = "03-01-01";
var pageName = "회차별 당첨번호";

var hdrw = 1;
function search() {
	$('#drwNo').val($("#dwrNoList").val());
	$("#frm").attr({action:"/gameResult.do?method=byWin", method:"post"}).submit();
}

$(document).ready(function() {

	if("1173" != ""){
		$("#dwrNoList").val("1173");
		if ("1173" < 601) hdrw = 2;
	}
	$('#searchBtn').click(function(e) {
		search();
	});
	$('#printBtn').click(function(e) {
		e.preventDefault();
		commonPop("stat_pop", "/gameResult.do?method=allWinPrint&gubun=byWin&nowPage="+$("#nowPage").val()+"&drwNoStart="+$("#drwNoStart").val()+"&drwNoEnd="+$("#drwNoEnd").val(), "800", "750", "");
	});
	$('#exelBtn').click(function(e) {
		var search1 = $("#drwNoStart").val();
		var search2 = $("#drwNoEnd").val();
		if(parseInt(search2) < parseInt(search1)){
			alert("시작회차가 종료회차보다 큽니다.");
			$('#drwNoEnd').focus();
			return false;
		};
		location.href = "/gameResult.do?method=allWinExel&gubun=byWin&nowPage="+$("#nowPage").val()+"&drwNoStart="+$("#drwNoStart").val()+"&drwNoEnd="+$("#drwNoEnd").val();
	});
	$('#hdrwComb').click(function(e) {
		if($('#hdrwComb').val() != hdrw) {
			hdrw = $('#hdrwComb').val();
			$("#dwrNoList").empty();
			$("#drwNoStart").empty();
			$("#drwNoEnd").empty();
			var str = "";

			if(hdrw == 1) {

In [89]:
times = soup.select_one('div.win_result > h4 > strong').text # 1173회
date = soup.select_one('div.win_result >p.desc').text  #(2025년 05월 24일 추첨)
print(times, date)
title1 = soup.select_one('div.num.win > strong').text
lotto_number = soup.select('div.num.win > p > span')
print(title1, [int(lotto.text) for lotto in lotto_number])
title2 = soup.select_one('div.num.bonus > strong').string
bonus_number = soup.select_one('div.num.bonus > p > span').text
print(title2, bonus_number)

1173회 (2025년 05월 24일 추첨)
당첨번호 [1, 5, 18, 20, 30, 35]
보너스 3

In [97]:
#위의 select함수를 find함수로

# times = soup.select_one('div.win_result > h4 > strong').text #1173회
win_result = soup.find('div', class_="win_result")
times = win_result.find('strong').text
# date = soup.select_one('div.win_result >p.desc').text  #(2025년 05월 24일 추첨)
date = soup.find('p', class_="desc").text
print(times,date)
# title1 = soup.select_one('div.num.win > strong').text
num_win = soup.find("div", class_=['num', 'win'])
title1 = num_win.find('strong').text
# lotto_number = soup.select('div.num.win > p > span')
lotto_number = num_win.find_all('span')#배열
print(title1, [int(lotto.text) for lotto in lotto_number])
# title2 = soup.select_one('div.num.bonus > strong').string
num_bonus = soup.find('div', class_=['bonus'])
title2 = num_bonus.find('strong').text
# bonus_number = soup.select_one('div.num.bonus > p > span').text
bonus_number = num_bonus.find('span').text
print(title2, bonus_number)

1173회 (2025년 05월 24일 추첨)
당첨번호 [1, 5, 18, 20, 30, 35]
보너스 3

### 3)다음 검색 리스트

```90
no title link
0 [비트코인 2025] 백악관 크립토 차르~ https://v.daum.net/v/20250528103907230
1 [비즈 나우] 비트코인 2025 컨퍼런~ https://v.daum.net/v/20250528075215864
```

In [113]:
# 방법1
import requests
from bs4 import BeautifulSoup
word = '비트코인'
url = 'https://search.daum.net/search?w=news&nil_search=btn&DA=NTB&enc=utf8&cluster=y&cluster_page=1&q='+word
response = requests.get(url)
soup = BeautifulSoup(response.text, # response.content
                    "html.parser")
items_find_list = [] # 검색한 결과를 담을 dict list
items_el = soup.select('div.item-title > strong.tit-g.clamp-g > a')
# len(items_el)
for idx, item in enumerate(items_el):
    items_find_list.append({'no': idx,
                           'title': item.text,
                           'link': item.attrs['href']})
import pandas as pd
pd.DataFrame(items_find_list)

,no,title,link
0,0,[비트코인 2025] 백악관 크립토 차르 “美 정부 비트코인 추가 매입 검토…부채...,http://v.daum.net/v/20250528103907230
1,1,[비즈 나우] 비트코인 2025 컨퍼런스 개막…'전략자산' 선언 코앞,http://v.daum.net/v/20250528075215864
2,2,“맥O날드보다 맛없어!” 혹평이 가득한 트럼프 만찬과 비트코인 피자데이[엠블록레터],http://v.daum.net/v/20250528143002735
3,3,"비트코인, 트럼프 미디어 비축 소식에도 주춤…1억5100만원대",http://v.daum.net/v/20250528095112897
4,4,"'비트코인 빚투' 스트레티지, 또 샀다…보유량 58만개 돌파",http://v.daum.net/v/20250528042404292
5,5,"美 상원의원 ""트럼프 대통령, 비트코인법 지지""",http://v.daum.net/v/20250528090342853
6,6,"숨 고르는 비트코인, 10만8000달러선 '주춤'",http://v.daum.net/v/20250528095921258
7,7,[비트코인 2025] 로빈후드 창업자 “토큰화 증권은 美 ‘자본 패권’ 키우는 수단”,http://v.daum.net/v/20250528110600761
8,8,"트럼프미디어그룹, 25억 달러 규모 자금 조달 통해 비트코인 매입 예고",http://v.daum.net/v/20250528084245020
9,9,연일 최고가 경신하는 비트코인…투자자들 강 건너 불구경하는 이유는,http://v.daum.net/v/20250526212400275

In [126]:
#다음 뉴스 검색(키워드, 원하는 페이지수)
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
def collect_list(keyword, page=1):
    'keyword로 다음 검색한 결과(해당 page)를 return'
    url = f'https://search.daum.net/search?w=news&nil_search=btn&DA=NTB&enc=utf8&cluster=y'
    params = {'q':keyword, 'p':page}
    response = requests.get(url, params=params)
    soup = BeautifulSoup(response.text, #response.content
                    'html.parser')
    items_find_list = [] # 검색한 결과를 담을 dict list
    items_el = soup.select('div.item-title > strong.tit-g.clamp-g > a')
    for idx, item in enumerate(items_el):
        items_find_list.append({'no': idx,
                           'title': item.text,
                           'link': item.attrs['href']})
    return items_find_list

In [127]:
collect_list('대선', 2)

[{'no': 0,
  'title': ' 부산 다시 찾은 김문수, ‘사전 투표’ 재차 독려 [21대 대선] ',
  'link': 'http://v.daum.net/v/20250528155306855'},
 {'no': 1,
  'title': " [살까팔까] '지배구조 개선' 대선 공약에…한화·효성 등 지주사株 '훨훨' ",
  'link': 'http://v.daum.net/v/20250528155002701'},
 {'no': 2,
  'title': ' [이재명 공약집] 금융사, 소액 금융분쟁 결정 바로 따라야 [대선 2025] ',
  'link': 'http://v.daum.net/v/20250528152126320'},
 {'no': 3,
  'title': ' 대선에 경찰 최대동원…서울 투표함 회송에 무장경찰 6400명 ',
  'link': 'http://v.daum.net/v/20250528154201339'},
 {'no': 4,
  'title': ' [대선공약] 코리아 디스카운트 넘는다…李 "주주권익 보호" vs 金 "세제 혜택" ',
  'link': 'http://v.daum.net/v/20250528153751194'},
 {'no': 5,
  'title': ' 이준석 발언 겨냥? 이재명 “대선, 혐오의 언어로 채워져” ',
  'link': 'http://v.daum.net/v/20250528144125273'},
 {'no': 6,
  'title': ' [대선공약] 李·金 모두 \'AI 인프라\' 방점…"구체적 실행 방안은 실종" ',
  'link': 'http://v.daum.net/v/20250528160128321'},
 {'no': 7,
  'title': ' “여성 유권자에게 사과”…이준석 유세 중 날아든 지적 [21대 대선] ',
  'link': 'http://v.daum.net/v/20250528142905688'},
 {'no': 8,
  'title': ' 대선토론 최악의 언어 성폭력…이준석 발언 ‘사후 제재’ 가능할까 ',
  'link': 'http://v.daum.net/v/20250528144503420'},
 {'no': 9,
  'title': " '대선 투표함 지켜라' 무장경찰 6400명 투입… 본투표땐 갑호비상 ",
  'link': 'http://v.daum.net/v/20250528154717586'}]

In [132]:
#원하는 keyword로 다음검색
result = []
keyword="청바지"
pages = 3
for page in range(1, pages+1):
    result.extend(collect_list(keyword, page))
    time.sleep(1)
result_df = pd.DataFrame(result)
result_df

Empty DataFrame
Columns: []
Index: []

In [141]:
keywords = ['청바지', '면바지']
pages=5
result0 = [] #청바지 검색결과 50개
result1 = [] #면바지 검색결과 50개
for i, keyword in enumerate(keywords):
    for page in range(1, pages+1):
        print(f'~~~~~~~~~{i}번째 {keyword} {page}검색 중입니다~~~~~~~~')
        if i==0:
            result0.extend(collect_list(keyword, page))
        else:
            result1.extend(collect_list(keyword, page))
        time.sleep(3)

~~~~~~~~~0번째 청바지 1검색 중입니다~~~~~~~~
~~~~~~~~~0번째 청바지 2검색 중입니다~~~~~~~~
~~~~~~~~~0번째 청바지 3검색 중입니다~~~~~~~~
~~~~~~~~~0번째 청바지 4검색 중입니다~~~~~~~~
~~~~~~~~~0번째 청바지 5검색 중입니다~~~~~~~~
~~~~~~~~~1번째 면바지 1검색 중입니다~~~~~~~~
~~~~~~~~~1번째 면바지 2검색 중입니다~~~~~~~~
~~~~~~~~~1번째 면바지 3검색 중입니다~~~~~~~~
~~~~~~~~~1번째 면바지 4검색 중입니다~~~~~~~~
~~~~~~~~~1번째 면바지 5검색 중입니다~~~~~~~~

In [142]:
result0_df = pd.DataFrame(result0)
result0_df.head()

,no,title,link
0,0,"'이병헌♥' 이민정, 매장 통째로 빌려 청바지 쇼핑",http://v.daum.net/v/20250528050507783
1,1,"“추앙받을 만 하네”… 김지원, 셔츠에 청바지만 입어도 공항 ‘정지’",http://v.daum.net/v/20250526182411395
2,2,흰 티셔츠에 청바지 정석대로 입는 법,http://v.daum.net/v/20250527185425864
3,3,"이민정, 매장 빌려 폭풍 쇼핑 ""10년 전 샀던 청바지는 응급실""(MJ)",http://v.daum.net/v/20250527191015309
4,4,"‘이병헌♥’ 이민정, 청바지 사는데 매장 통째로 빌렸다..남다른 쇼핑 클래스 “나...",http://v.daum.net/v/20250527192310643

In [143]:
result1_df = pd.DataFrame(result0)
result1_df.head()

,no,title,link
0,0,"'이병헌♥' 이민정, 매장 통째로 빌려 청바지 쇼핑",http://v.daum.net/v/20250528050507783
1,1,"“추앙받을 만 하네”… 김지원, 셔츠에 청바지만 입어도 공항 ‘정지’",http://v.daum.net/v/20250526182411395
2,2,흰 티셔츠에 청바지 정석대로 입는 법,http://v.daum.net/v/20250527185425864
3,3,"이민정, 매장 빌려 폭풍 쇼핑 ""10년 전 샀던 청바지는 응급실""(MJ)",http://v.daum.net/v/20250527191015309
4,4,"‘이병헌♥’ 이민정, 청바지 사는데 매장 통째로 빌렸다..남다른 쇼핑 클래스 “나...",http://v.daum.net/v/20250527192310643

In [147]:
result0_df.to_csv('data/ch14'+keywords[0]+'.csv',index=False, encoding='cp949')
result1_df.to_csv('data/ch14'+keywords[1]+'.csv',index=False)

### 4) Useragent를 추가하여 크롤링
- urlopen()함수를 사용하면 크롤링이 안 되는 사이트

In [145]:
#방법2
from urllib.request import urlopen, Request
import urllib.parse
word = '비트코인'
word = urllib.parse.quote(word)
#print(word)
url = 'https://search.daum.net/search?w=news&nil_search=btn&DA=NTB&enc=utf8&cluster=y&cluster_page=1&q='+word
#User-Agent를 추가하여 브라우저처럼 보이게 포장
headers = {'user-agent':
         'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36'}
request = Request(url, headers = headers)
response = urlopen(request)
soup = BeautifulSoup(response, # response.content
                    "html.parser")
soup

<!DOCTYPE html>

<html lang="ko" xmlns="http://www.w3.org/1999/xhtml">
<head profile="http://a9.com/-/spec/opensearch/1.1/">
<meta content="text/html;charset=utf-8" http-equiv="content-Type"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="off" name="autocomplete"/>
<meta content="always" name="referrer"/>
<meta content="telephone=no,address=no,email=no" name="format-detection">
<meta content="비트코인 – Daum 검색" property="og:title"/>
<meta content="https://search.daum.net/search?w=news&amp;nil_search=btn&amp;DA=NTB&amp;enc=utf8&amp;cluster=y&amp;cluster_page=1&amp;q=%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8" property="og:url"/>
<meta content="Daum 검색에서 비트코인에 대한 최신정보를 찾아보세요." property="og:description"/>
<meta content="https://search1.daumcdn.net/search/statics/common/img/20250107/daum_og.png" property="og:image"/>
<meta content="다음검색" property="og:site_name"/>
<link href="https://t1.daumcdn.net/top/favicon/20241223/daum.ico" rel="shortcut icon"/>
<link href="//sl.search.daum.net/" rel="preconnect"/>
<link href="//ssl.daumcdn.net/" rel="preconnect"/>
<link href="//t1.daumcdn.net/" rel="preconnect"/>
<link href="//wat.ad.daum.net/" rel="preconnect"/>
<link href="//track.tiara.daum.net/" rel="preconnect"/>
<link href="//webid.ad.daum.net/" rel="preconnect"/>
<link href="//webid.kakao.com/" rel="preconnect"/>
<title>비트코인 – Daum 검색</title>
<link href="//search.daum.net/OpenSearch.xml" rel="search" title="Daum" type="application/opensearchdescription+xml"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2025/p_common.0408023855.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2024/p_component.0610023548.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2025/pm_common.0512034956.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2025/q_comm.0407032624.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/js/fe/cubic/20250519130026/cubic.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2025/p_collection.0114125841.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2024/p_collection2.0923031103.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2024/p_newsColl.1105104334.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript">
var uk = "cf930c51-382a-463c-80ab-45e2c559410f";
var mk = "cf930c51-382a-463c-80ab-45e2c559410f";
var ksk = "cf930c51-382a-463c-80ab-45e2c559410f";
var ud = "";
var uuid = "";
var adid = "";
var adid_enabled = "N";
var viewio = "i";
var viewsite = "";
var ServerTime = "20250528165143";
var utf8Query = encodeURIComponent("비트코인");
var topQuery = "비트코인";
var backQuery = encodeURIComponent("비트코인");
var login_yn = "N";
var encodeType = "2";
var refCode = "";
var bucketType = "";
var name_check = "0";
var mobileDevice = "N";
var param_w = "news";
var param_da = "NTB";
var paramCfg = "";
var param_cnucc = "";
var tpl_cfg = "";
var cnucc = "";
var usrIp = "210.121.189.12";
var isDetailTab = "N";
var schSort = "";
var existMobileTabYn = "N";
var width_over_620 = "N";
var sPageLoadedmsTime =  266 ;
var isReleaseMode = '';
var isTotDebugMode = false;
var KAKAO_ACCOUNT_ID_CONNECTED = "N";
var displayInfo = {"SER":[{"code":"DNS","doc_count":10}],"SGR":[{"code":"1MV","doc_count":10},{"code":"NSJ","doc_count":0},{"code":"DCC","doc_count":0}],"SUI":[],"CUT":[]};
var usr4 = "1MV10_PSB0_NSJ0_DCC0_DNS10";
var slCallType = "sync";
var pageLoadedTime = 0;
var startTime = new Date().getTime();
var sugLocCode = "";
var searchLog = {
uc: 0,
clickCount: 0,
dl: ""
};
var SEARCHLOGDOMAIN = "\/\/sl.search.daum.net";
var CNUCC_URL = "https:\/\/harm.search.daum.net\/v2\/api\/report-harm";
var SUG_URL = "\/\/suggest.search.daum.net\/sushi\/pc\/get";
var VSUG_URL = "\/\/vmsuggest.search.daum.net\/v2\/sushi\/pc\/get";
var ASUG_URL = "\/\/ninstant.search.daum.net\/suggest\/index.daum";
var AMADO_URL = "\/\/search1.daumcdn.net\/search\/statics\/common\/js\/fe\/amado-workspace\/pc\/2.8.0\/main.js";
var SF = {
phase: "prod",
userQueryParamW: "news",
platform: "pc",
iam: {
clean: false,
geo: false,
login: false,
adult: false,
adultUrl: "https:\/\/logins.daum.net\/accounts\/loginform.do?service=adult_service\u0026url=https%3A%2F%2Fsearch.daum.net%2Fsearch%3FDA%3DNTB%26cluster%3Dy%26cluster_page%3D1%26enc%3Dutf8%26nil_search%3Dbtn%26q%3D%25EB%25B9%2584%25ED%258A%25B8%25EC%25BD%2594%25EC%259D%25B8%26realname_redirect%3D1%26w%3Dnews"
},
ua: {"ua":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36","browser":{"name":"chrome","version":{"info":"136.0.0.0","major":136,"minor":0,"patch":0}},"device":"","os":{"name":"windows","version":{"info":"10","major":10,"minor":0,"patch":0}},"platform":"pc","app":{"isDaumapp":false,"isKakao":false,"version":{"info":"","major":0,"minor":0,"patch":0}}}
};
SF.ua.app.isApp = SF.ua.app.isDaumapp;
SF.ua.os[SF.ua.os.name] = true;
SF.ua.browser[SF.ua.browser.name] = true;
SF.loadModuleList = {"amcharts":"//search1.daumcdn.net/search/statics/common/js/fe/tot-search/library/p/amcharts.20190321202015.min.js","calendar":"//search1.daumcdn.net/search/statics/common/js/fe/tot-search/module/p/calendar/module.p.calendar.20210312112039.min.js","chart":"//search1.daumcdn.net/search/statics/common/js/fe/tot-search/library/p/chart.20200602182334.min.js","kakaosdk":"//search1.daumcdn.net/search/statics/common/js/fe/tot-search/library/p/kakaosdk.20230811110443.min.js","kakaotv":"//tv.kakao.com/player/script/sdk/player_api.min.js","ks":"//search1.daumcdn.net/search/statics/common/js/fe/tot-search/module/p/ks/module.p.ks.20221122154101.min.js","pagenavigation":"//search1.daumcdn.net/search/statics/common/js/fe/tot-search/module/p/pagenavigation/module.p.pagenavigation.20220705092744.min.js","v3":"//ssl.daumcdn.net/dmaps/map_js_init/v3.js","youtube":"//www.youtube.com/player_api"};
var SD = {};
var SG = {};
var C = {};
var T = {};
var SL = {
mkeyLog: function(){},
freelog: {
send: function(){}
},
dexposeLog: {
send: function(){}
},
xscrollLog: function(){}
};
var smartLog = function(){};
</script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/tot-workspace/polyfill/p-legacy/1.4.0/main.min.js" type="text/javascript"></script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/tot-workspace/logger/1.2.0/main.js?o=p" type="text/javascript"></script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/tot-workspace/vendor/p/1.0.0/main.min.js" type="text/javascript"></script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/tot-workspace/search-log/p/1.3.0/main.min.js" type="text/javascript"></script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/tot-workspace/module/1.43.0/main.min.js?o=p" type="text/javascript"></script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/tot-workspace/library/1.38.0/remoteEntry.js?o=p" type="text/javascript"></script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/tot-workspace/runtime/1.34.0/main.min.js?o=p" type="text/javascript"></script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/cubic/20250519130026/cubic.min.js?o=p" type="text/javascript"></script>
<script src="//t1.daumcdn.net/tiara/js/v1/tiara.min.js" type="text/javascript"></script>
<script type="text/javascript">
(function(SF){
SF.tiaraTracker.setDefaultConfig();
})(window.SF || {});
</script>
</meta></head>
<body class="daum windows win chrome pc">
<script type="text/javascript">
SL.mkeyLog();
</script>
<nav class="d_direct" id="daumIndex">
<a class="link_direct" href="#daumBody">본문 바로가기</a>
<a class="link_direct" href="#daumGnb">메뉴 바로가기</a>
</nav>
<div id="saq" style="display:none">비트코인</div>
<div class="sch_tab_news" id="daumWrap">
<header id="daumHead">
<div class="d_head">
<h1 class="screen_out">다음</h1>
<h2 class="screen_out">검색</h2>
<div class="inner_header" id="innerHeader">
<form class="d_sch" id="daumSearch" method="get" name="search">
<fieldset class="fld_total">
<legend class="screen_out">검색폼</legend>
<input id="nil_suggest" name="nil_suggest" type="hidden" value="btn"/>
<input id="nil_ch" name="nil_ch" type="hidden" value=""/>
<input name="rtupcoll" type="hidden" value=""/>
<input name="w" type="hidden" value="news"/>
<input name="m" type="hidden" value=""/>
<input id="f" name="f" type="hidden" value=""/>
<input name="lpp" type="hidden" value=""/>
<input name="DA" type="hidden" value="SBC"/>
<input name="sug" type="hidden" value=""/>
<input name="sq" type="hidden" value=""/>
<input name="o" type="hidden" value=""/>
<input name="sugo" type="hidden" value=""/>
<input name="cluster" type="hidden" value="y"/>
<div class="box_searchbar">
<div class="inner_searchbar">
<a class="link_service" data-target="_top" href="https://www.daum.net/" id="daumLogo" onclick='smartLog(this, "e=1&amp;dc=MLC", event);' target="_top" title="Daum 메인페이지로 가기">
<img alt="Daum" height="56" src="//search1.daumcdn.net/search/statics/common/pi/logo/logo_D112x112_241223.svg"/>
</a>
<input autocomplete="off" class="tf_keyword" id="q" maxlength="255" name="q" title="검색어 입력" type="text" value="비트코인"/>
<button class="btn_reset" id="btnResetHeader" onclick="smartLog(this, 'pg=1&amp;p=2&amp;r=1&amp;rc=1&amp;dc=SBC&amp;at=func', event);" title="검색어 지우기" type="button">
<span class="ico_ksg">입력삭제</span>
</button>
<button aria-label="가상키보드 열기" class="btn_vkey" id="VKIBtn" onclick="smartLog(this, 'pg=1&amp;p=1&amp;r=1&amp;rc=1&amp;dc=BFJ&amp;at=func', event);" title="가상키보드 열기" type="button">
<svg fill="none" height="28" width="28" xmlns="http://www.w3.org/2000/svg">
<rect height="15" rx="4" stroke="currentColor" stroke-width="2" width="24" x="2" y="6.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="6" y="9.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="9.5" y="9.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="13" y="9.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="16.5" y="9.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="20" y="9.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="6" y="13"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="9.5" y="13"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="13" y="13"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="16.5" y="13"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="20" y="13"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="6" y="16.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="9" x="9.5" y="16.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="20" y="16.5"></rect>
</svg>
</button>
<button aria-label="검색" class="btn_ksearch" id="daumBtnSearch" title="검색" type="submit">
<svg fill="currentColor" height="28" viewbox="0 0 28 28" width="28" xmlns="http://www.w3.org/2000/svg">
<path clip-rule="evenodd" d="M6 12.5C6 8.91015 8.91015 6 12.5 6C16.0899 6 19 8.91015 19 12.5C19 16.0899 16.0899 19 12.5 19C8.91015 19 6 16.0899 6 12.5ZM12.5 4C7.80558 4 4 7.80558 4 12.5C4 17.1944 7.80558 21 12.5 21C14.5006 21 16.3399 20.3088 17.7919 19.1522C17.836 19.2314 17.8916 19.3059 17.9589 19.3731L22.9589 24.3731C23.3494 24.7636 23.9826 24.7636 24.3731 24.3731C24.7636 23.9826 24.7636 23.3494 24.3731 22.9589L19.3731 17.9589C19.3059 17.8916 19.2314 17.836 19.1522 17.7919C20.3088 16.3399 21 14.5006 21 12.5C21 7.80558 17.1944 4 12.5 4Z" fill="currentColor" fill-rule="evenodd"></path>
</svg>
</button>
</div>
</div>
</fieldset>
<div class="box_suggest" id="daumSuggestTop"><div id="suggestBox"></div></div>
</form>
<div id="wrapMinidaum"></div>
</div>
<div id="daumGnb">
<div class="tab_dynamic tab_flex">
<ul class="list_tab">
<li class="">
<a class="tab_tit" href="?w=tot&amp;q=%eb%b9%84%ed%8a%b8%ec%bd%94%ec%9d%b8&amp;DA=NTB" onclick="smartLog(this, 'pg=1&amp;r=1&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event);"><span class="inner_tab">통합</span></a>
</li>
<li class="on">
<span class="screen_out">선택된 항목</span>
<a class="tab_tit" href="?w=news&amp;nil_search=btn&amp;DA=NTB&amp;enc=utf8&amp;cluster=y&amp;cluster_page=1&amp;q=%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8" onclick="smartLog(this, 'pg=1&amp;r=2&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event)">
<span class="inner_tab">
뉴스</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="?w=img&amp;nil_search=btn&amp;DA=NTB&amp;enc=utf8&amp;q=%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8" onclick="smartLog(this, 'pg=1&amp;r=3&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event)">
<span class="inner_tab">
이미지</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="?w=vclip&amp;nil_search=btn&amp;DA=NTB&amp;enc=utf8&amp;q=%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8" onclick="smartLog(this, 'pg=1&amp;r=4&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event)">
<span class="inner_tab">
동영상</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="?w=fusion&amp;nil_search=btn&amp;DA=NTB&amp;p=2&amp;q=%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8" onclick="smartLog(this, 'pg=1&amp;r=5&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event)">
<span class="inner_tab">
통합웹</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="?w=site&amp;nil_search=btn&amp;DA=NTB&amp;enc=utf8&amp;lpp=10&amp;q=%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8" onclick="smartLog(this, 'pg=1&amp;r=6&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event)">
<span class="inner_tab">
사이트</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="http://dic.daum.net/search.do?q=%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8" onclick="smartLog(this, 'pg=1&amp;r=7&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event)" target="_blank">
<span class="inner_tab">
어학사전<span class="ico_ksg ico_outlink">새창</span>
</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="https://map.kakao.com/?from=total&amp;nil_suggest=btn&amp;tab=place&amp;q=%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8" onclick="smartLog(this, 'pg=1&amp;r=8&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event)" target="_blank">
<span class="inner_tab">
지도<span class="ico_ksg ico_outlink">새창</span>
</span>
</a>
</li>
</ul>
<div class="more_dynamic more_search">
<button class="btn_tab" id="gnbToggleBtn" title="더보기" type="button">
<span class="ico_ksg">더보기/접기</span>
</button>
<ul class="list_more">
<li class="">
<a class="tab_tit" href="https://100.daum.net/search/entry?q=%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8" onclick="smartLog(this, 'pg=1&amp;r=9&amp;p=2&amp;rc=1&amp;e1=NS&amp;e2=1DVZ&amp;dc=NTB&amp;at=more', event)" target="_blank">
<span class="inner_tab">
백과사전<span class="ico_ksg ico_outlink">새창</span>
</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="https://shoppinghow.kakao.com/search/%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8/&amp;srchhow=Cexpo" onclick="smartLog(this, 'pg=1&amp;r=10&amp;p=2&amp;rc=1&amp;e1=NS&amp;e2=SNPZ&amp;dc=NTB&amp;at=more', event)" target="_blank">
<span class="inner_tab">
쇼핑<span class="ico_ksg ico_outlink">새창</span>
</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="?w=book&amp;nil_search=btn&amp;DA=NTB&amp;enc=utf8&amp;q=%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8" onclick="smartLog(this, 'pg=1&amp;r=11&amp;p=2&amp;rc=1&amp;e1=NS&amp;e2=LB2Z&amp;dc=NTB&amp;at=more', event)">
<span class="inner_tab">
책</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="https://www.melon.com/search/total/index.htm?q=%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8&amp;ref=W10060" onclick="smartLog(this, 'pg=1&amp;r=12&amp;p=2&amp;rc=1&amp;e1=NS&amp;e2=MS2Z&amp;dc=NTB&amp;at=more', event)" target="_blank">
<span class="inner_tab">
멜론뮤직<span class="ico_ksg ico_outlink">새창</span>
</span>
</a>
</li>
</ul>
</div>
</div>
</div>
</div>
</header>
<div id="daumContent">
<main id="cMain">
<div id="mArticle">
<div class="inner_article">
<span class="screen_out" id="daumBody">검색 본문</span>
<div class="g_comp" disp-attr="NSJ">

In [146]:
def collect_list(keyword, page=1):
    'keyword로 다음 검색한 결과(해당 page)를 return'
    url = f'https://search.daum.net/search?w=news&nil_search=btn&DA=NTB&enc=utf8&cluster=y'
    params = {'q':keyword, 'p':page}
    response = requests.get(url, params=params)
    soup = BeautifulSoup(response.text, #response.content
                    'html.parser')
    items_find_list = [] # 검색한 결과를 담을 dict list
    items_el = soup.select('div.item-title > strong.tit-g.clamp-g > a')
    for idx, item in enumerate(items_el):
        items_find_list.append({'no': idx,
                           'title': item.text,
                           'link': item.attrs['href']})
    return items_find_list
collect_list('청바지', 1)

[{'no': 0,
  'title': " '이병헌♥' 이민정, 매장 통째로 빌려 청바지 쇼핑 ",
  'link': 'http://v.daum.net/v/20250528050507783'},
 {'no': 1,
  'title': ' “추앙받을 만 하네”… 김지원, 셔츠에 청바지만 입어도 공항 ‘정지’ ',
  'link': 'http://v.daum.net/v/20250526182411395'},
 {'no': 2,
  'title': ' 흰 티셔츠에 청바지 정석대로 입는 법 ',
  'link': 'http://v.daum.net/v/20250527185425864'},
 {'no': 3,
  'title': ' 이민정, 매장 빌려 폭풍 쇼핑 "10년 전 샀던 청바지는 응급실"(MJ) ',
  'link': 'http://v.daum.net/v/20250527191015309'},
 {'no': 4,
  'title': ' ‘이병헌♥’ 이민정, 청바지 사는데 매장 통째로 빌렸다..남다른 쇼핑 클래스 “나는 즉흥적”(이민정 MJ) ',
  'link': 'http://v.daum.net/v/20250527192310643'},
 {'no': 5,
  'title': ' 이시영처럼 다리 길어보이고 싶어서 청바지 분석함 [입스타그램] ',
  'link': 'http://v.daum.net/v/20250519172231644'},
 {'no': 6,
  'title': ' \'의사 그만둔\' 고윤정, 흰 티+청바지..."정석 미녀" [★해시태그] ',
  'link': 'http://v.daum.net/v/20250522182007490'},
 {'no': 7,
  'title': ' "청렴이 최고" … 창원특례시 성산구 문화위생과, \'청바지 데이\' 추진 ',
  'link': 'http://v.daum.net/v/20250511091428626'},
 {'no': 8,
  'title': ' 패셔니스타 김지원, 청바지가 어울리는 여자랍니다! [포토] ',
  'link': 'http://v.daum.net/v/20250518220139191'},
 {'no': 9,
  'title': ' 박병은 "류준하로 3개월 활동"…청바지 모델 시절 언급 ',
  'link': 'http://v.daum.net/v/20250519190323957'}]

- 꼭 User-Agent를 사용하여야 하는 경우: https://www.melon.com/chart/

In [161]:
# 방법1
import requests
from bs4 import BeautifulSoup
url='https://www.melon.com/chart/'
melonpage = requests.get(url)
melonpage

In [162]:
# 방법2
from urllib.request import urlopen, Request
#melonpage = urlopen(url) 에러남

In [163]:
#User-Agent추가
headers={'user-agent':
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36'}
#방법2
request = Request(url, headers=headers)
melonpage = urlopen(request)
#방법1
melonpage = requests.get(url, headers=headers)
soup = BeautifulSoup(melonpage.text, #melonpage.content
                    'html.parser')
#soup

In [168]:
#멜론 순위, 가수, 노래 제목
#1위 |너에게 닿기를 |10cm  (100위까지 크롤링)
title_els = soup.select('div.ellipsis rank01 > span')
singer_els = soup.select('div.ellipsis.rank02 > span.checkEllipsis')
len([title.text.strip() for title in title_els]),\
len([singer.text for singer in singer_els])
for idx, (title, singer) in enumerate(zip(title_els, singer_els)):
    print('{}위 | {} - {}'.format(idx+1,
                                title.text.strip(),
                                singer.text))

### 5)네이버 지식인으로 검색(open API 사용X)
- 특정 keyword를 특정페이지 수(3)만큼 검색한 결과 데이터프레임으로 출력

In [5]:
# 방법1
from requests import get
keyword='챗지피티'
url = 'https://kin.naver.com/search/list.naver?query={}'.format(keyword)
print(url)
response = get(url)
#response.status_code
soup = BeautifulSoup(response.text, #response.content
                    'html.parser')

https://kin.naver.com/search/list.naver?query=챗지피티

In [6]:
from urllib.request import urlopen
from urllib.parse import quote
# 챗지피티 ->%EC%B1%97%EC%A7%80%ED%94%BC%ED%8B%B0
keyword = quote(keyword) #url인코딩된 문자열로 전환
url = 'https://kin.naver.com/search/list.naver?query={}'.format(keyword)
#print(url)
response = urlopen(url)
soup = BeautifulSoup(response, 'html.parser')

In [8]:
#페이징 포함(keyword를 pages수 만큼 검색한 결과를 데이터프레임에 )
import requests
from bs4 import BeautifulSoup
import pandas as pd
keyword = '챗지피티'
pages = 3
items_list = [] #크롤링 한 데이터를 담을 list
for page in range(1, pages+1):
    url = f'https://kin.naver.com/search/list.naver?query={keyword}&page={page}'
    #print(url)
    #해당 url의 soup객체 -> 글제목, link를 가져와서 items_list에 append
    response = requests.get(url)
    #print(response.status_code) 정상 접근 가능한지 여부
    soup = BeautifulSoup(response.text, 'html.parser')
    items = soup.select('dt > a')
    #print([item.attrs['href'] for item in items])
    for dt in dts:
        item = dt.find('a')
#        items_list.append([item.text, item.attrs.get('href')])
#         items_list.append({
#             'title': item.text,
#             'link': item.attrs.get('href')
#         })
# print(len(items_list), '개 데이터')
# print(items_list[:2])
df = pd.DataFrame(items_list, columns = ['title', 'link'])
df

,title,link
0,챗지피티 사주,https://kin.naver.com/qna/detail.naver?d1id=3&...
1,챗지피티 타로,https://kin.naver.com/qna/detail.naver?d1id=3&...
2,챗지피티 타로,https://kin.naver.com/qna/detail.naver?d1id=3&...
3,챗지피티 갸륵체 어떻게 생각하시나요?,https://kin.naver.com/qna/detail.naver?d1id=1&...
4,챗지피티 사용하려면 어떻게 해야 하나요?,https://kin.naver.com/qna/detail.naver?d1id=4&...
5,챗지피티 잡아내는거..,https://kin.naver.com/qna/detail.naver?d1id=4&...
6,챗지피티 개인정보,https://kin.naver.com/qna/detail.naver?d1id=1&...
7,챗지피티 돈 내면서 쓰는거 좋나요?,https://kin.naver.com/qna/detail.naver?d1id=6&...
8,카피킬러 표절 및 챗지피티 검사 83%,https://kin.naver.com/qna/detail.naver?d1id=11...
9,챗지피티 무료 렉 거림,https://kin.naver.com/qna/detail.naver?d1id=1&...
10,아 ㅆ 지식인 챗지피티 돌리는 것들 잘...,https://kin.naver.com/qna/detail.naver?d1id=8&...
11,챗지피티 동시 접속 되나요?,https://kin.naver.com/qna/detail.naver?d1id=1&...
12,챗지피티 plus 파일 생성 오류,https://kin.naver.com/qna/detail.naver?d1id=1&...
13,무료 챗지피티 써보려고 하는데,https://kin.naver.com/qna/detail.naver?d1id=1&...
14,하 챗지피티,https://kin.naver.com/qna/detail.naver?d1id=11...
15,챗지피티 연애상담,https://kin.naver.com/qna/detail.naver?d1id=7&...
16,챗지피티 코딩,https://kin.naver.com/qna/detail.naver?d1id=1&...
17,퍼플렉시티 챗지피티 질문,https://kin.naver.com/qna/detail.naver?d1id=1&...
18,챗지피티 음성,https://kin.naver.com/qna/detail.naver?d1id=4&...
19,조선왕조실록 챗지피티 사실 검증,https://kin.naver.com/qna/detail.naver?d1id=11...
20,겜스고 챗지피티,https://kin.naver.com/qna/detail.naver?d1id=1&...
21,챗지피티 검사기,https://kin.naver.com/qna/detail.naver?d1id=3&...
22,챗지피티 메모리,https://kin.naver.com/qna/detail.naver?d1id=5&...
23,챗지피티 유료 차이,https://kin.naver.com/qna/detail.naver?d1id=1&...
24,모바일 챗지피티,https://kin.naver.com/qna/detail.naver?d1id=2&...
25,지식인<<<챗지피티,https://kin.naver.com/qna/detail.naver?d1id=7&...
26,챗지피티 결제 플러스,https://kin.naver.com/qna/detail.naver?d1id=1&...
27,챗지피티 4o 이용해야 하나…?,https://kin.naver.com/qna/detail.naver?d1id=1&...
28,챗지피티 오류,https://kin.naver.com/qna/detail.naver?d1id=1&...
29,챗지피티 주 사용 연령층,https://kin.naver.com/qna/detail.naver?d1id=1&...

In [18]:
#페이징 포함(keyword를 pages수 만큼 검색한 결과를 데이터프레임에 )
def get_items_data(keyword, pages):
    import requests
    from bs4 import BeautifulSoup
    import pandas as pd
    items_list = [] #크롤링 한 데이터를 담을 list(2차원 리스트)
    for page in range(1, pages+1):
        url = f'https://kin.naver.com/search/list.naver?query={keyword}&page={page}'
        #해당 url의 soup객체 -> 글제목, link를 가져와서 items_list에 append
        response = requests.get(url)
        soup = BeautifulSoup(response.text, 'html.parser')
        dts = soup.find_all('dt')
        for dt in dts:
            item = dt.find('a')
            items_list.append([item.text, item.attrs.get('href')])
    return pd.DataFrame(items_list, columns = ['title', 'link'])

In [20]:
df = get_items_data('청바지', 3)
df

,title,link
0,영어로 청바지를 뭐라고하나요?,https://kin.naver.com/qna/detail.naver?d1id=11...
1,"전 남자인데, 누워서 청바지를 입으면...",https://kin.naver.com/qna/detail.naver?d1id=7&...
2,청바지 없는데 면접취소 할까요?,https://kin.naver.com/qna/detail.naver?d1id=6&...
3,고관절 지방이식 후 청바지,https://kin.naver.com/qna/detail.naver?d1id=7&...
4,임영웅 청바지 입은 사진?,https://kin.naver.com/qna/detail.naver?d1id=3&...
5,청바지 세탁,https://kin.naver.com/qna/detail.naver?d1id=8&...
6,미국에서 청바지 가격이 306불입니다...,https://kin.naver.com/qna/detail.naver?d1id=4&...
7,청바지? 면바지도 트레이닝바지인가요?,https://kin.naver.com/qna/detail.naver?d1id=13...
8,핀턱 청바지 수선,https://kin.naver.com/qna/detail.naver?d1id=8&...
9,청바지 이염,https://kin.naver.com/qna/detail.naver?d1id=5&...
10,골프 연습장 에서 부츠컷 청바지 입어도...,https://kin.naver.com/qna/detail.naver?d1id=10...
11,강아지 청바지 뜯어먹음,https://kin.naver.com/qna/detail.naver?d1id=8&...
12,청바지 수선,https://kin.naver.com/qna/detail.naver?d1id=5&...
13,청바지는 오랫동안 쓸 수 있나요?,https://kin.naver.com/qna/detail.naver?d1id=8&...
14,여자들중에 원피스보다 청바지가 예쁜...,https://kin.naver.com/qna/detail.naver?d1id=8&...
15,체육대회때 흰티에 청바지 입어도 되나요?,https://kin.naver.com/qna/detail.naver?d1id=5&...
16,8월 초 이탈리아 청바지,https://kin.naver.com/qna/detail.naver?d1id=9&...
17,청바지는 오랫동안 쓸 수 있나요?,https://kin.naver.com/qna/detail.naver?d1id=5&...
18,청바지에서 파란 물,https://kin.naver.com/qna/detail.naver?d1id=8&...
19,40대 남자도 청바지를 입나요?,https://kin.naver.com/qna/detail.naver?d1id=8&...
20,검은 청바지에 검은 티셔츠 ㄱㅊ나요?,https://kin.naver.com/qna/detail.naver?d1id=5&...
21,청바지 이름이 뭔가요..??,https://kin.naver.com/qna/detail.naver?d1id=5&...
22,청바지 수선이요,https://kin.naver.com/qna/detail.naver?d1id=8&...
23,남자가 청바지를 입으면 고환이 아플 수...,https://kin.naver.com/qna/detail.naver?d1id=7&...
24,청바지 섬유유연제 넣어도 빳빳해요,https://kin.naver.com/qna/detail.naver?d1id=8&...
25,임영웅 청바지 입은 사진?,https://kin.naver.com/qna/detail.naver?d1id=3&...
26,런닝맨 옛날꺼에 송지효가 청바지만 입은...,https://kin.naver.com/qna/detail.naver?d1id=8&...
27,회색후드티 청바지 레이어드 없어도...,https://kin.naver.com/qna/detail.naver?d1id=8&...
28,청바지 자국 남은거 지울수 없나요??,https://kin.naver.com/qna/detail.naver?d1id=5&...
29,와이드 청바지 빨래,https://kin.naver.com/qna/detail.naver?d1id=10...

### 6)네이버 지식인으로 검색(open API 사용O)-
- 특정 keyword를 특정페이지 수(3)만큼 검색한 결과 데이터프레임으로 출력
     - .env에 발급받은 키 저장 -> load(pip install python-dotenv)

In [13]:
#환경변수 가져오기
from dotenv import load_dotenv
import os
load_dotenv() #dotenv_path='.env'기본값
# print(os.getenv('Client_ID'))
# print(os.getenv('Client_Secret'))

AYfT_6KERF5DIoARIprd
F20oajAL_D

In [22]:
# 네이버 검색 API 예제 - 블로그 검색
import os
import sys
import urllib.request
client_id = os.getenv('Client_ID')
client_secret = os.getenv('Client_Secret')
encText = urllib.parse.quote("챗지피티")
url = "https://openapi.naver.com/v1/search/kin.json?query=" + encText # JSON 결과
# url = "https://openapi.naver.com/v1/search/blog.xml?query=" + encText # XML 결과

headers = {'X-Naver-Client-Id':client_id,
          'X-Naver-Client-Secret':client_secret}
request = urllib.request.Request(url, headers=headers)
# request = urllib.request.Request(url)
# request.add_header("X-Naver-Client-Id",client_id)
# request.add_header("X-Naver-Client-Secret",client_secret)

response = urllib.request.urlopen(request)
rescode = response.getcode()
if(rescode==200):
    response_body = response.read()
    print(type(response_body.decode('utf-8')))
    import json
    data = json.loads(response_body.decode('utf-8'))
    print(type(data))
    #print(data['items'])
else:
    print("Error Code:" + rescode)

<class 'str'>
<class 'dict'>
[{'title': '<b>챗지피티</b> 사주', 'link': 'https://kin.naver.com/qna/detail.naver?d1id=3&dirId=31501&docId=484827506&qb=7LGX7KeA7ZS87Yuw&enc=utf8', 'description': '책지피티 사주 다 정확하지는 않죠?ㅠ 좋아하던 사람한테 연락올 가능성... <b>챗지피티</b>는 이용하지 않는게 좋습니다 <b>챗지피티</b> 제작 초기 최초 적용, 입력한... <b>챗지피티</b>는 세월이 갈수록 세련되어 지는게 아니라 엉뚱한 소리를 하게 되는... '}, {'title': '<b>챗지피티</b> 타로', 'link': 'https://kin.naver.com/qna/detail.naver?d1id=3&dirId=31503&docId=484836001&qb=7LGX7KeA7ZS87Yuw&enc=utf8', 'description': '<b>챗지피티</b> 타로 믿을만한가요?ㅜㅜ <b>챗지피티</b> 타로, 그러니까 인공지능이... 요즘엔 온라인에서 너무나 손쉽게 타로를 볼 수 있고, 특히 <b>챗지피티</b>처럼 최신... 이런 부분은 <b>챗지피티</b> 같은 인공지능이 잡아내기는 어렵습니다. 인공지능 타로는... '}, {'title': '<b>챗지피티</b> 타로', 'link': 'https://kin.naver.com/qna/detail.naver?d1id=3&dirId=31503&docId=485464963&qb=7LGX7KeA7ZS87Yuw&enc=utf8', 'description': '제가 <b>챗지피티</b>로 사주랑 타로를 많이 보는데요 사주는 가끔 가다가 말이 너무 달라지고요 타로도 제가 카드 뽑고... <b>챗지피티</b>가 해석해주는데 것도 말이 달라요 그래서 제가 똑바로 해석하라고 해서 다시 해줬는데 아예... '}, {'title': '<b>챗지피티</b> 갸륵체 어떻게 생각하시나요?', 'link': 'https://kin.naver.com/qna/detail.naver?d1id=1&dirId=113&docId=485266256&qb=7LGX7KeA7ZS87Yuw&enc=utf8', 'description': '요즘 <b>챗지피티</b> 갸륵체가 정말 핫하더라고요. 갸륵체 외에도 다양한 사람들... 혹시 여러분은 자신만의 <b>챗지피티</b> 답변 문체가 있나요? 아니면 갸륵체를... 요즘 <b>챗지피티</b> ‘갸륵체’처럼 독특한 문체가 인기를 끌고 있다는 건, 사람들이... '}, {'title': '<b>챗지피티</b> 사용하려면 어떻게 해야 하나요?', 'link': 'https://kin.naver.com/qna/detail.naver?d1id=4&dirId=408&docId=485386619&qb=7LGX7KeA7ZS87Yuw&enc=utf8', 'description': '<b>챗지피티</b> 사용하려면 어떻게 해야 하나요? 회원가입을 해야 하나요? 순서도 모르겠고 어떻게 해야 하는지 몰라... <b>챗지피티</b> 쓰려면 openai.com 가서 회원가입 먼저 하셔야 해요 이메일 인증하고 로그인하면 바로 질문할 수 있어요... '}, {'title': '<b>챗지피티</b> 잡아내는거..', 'link': 'https://kin.naver.com/qna/detail.naver?d1id=4&dirId=40608&docId=484141621&qb=7LGX7KeA7ZS87Yuw&enc=utf8', 'description': '... <b>챗지피티</b> 같은 AI 많이 쓰잖아요 이걸 그대로 베껴오지않고 조금 수정해도 걸린다는데 도대체 뭐 써서 <b>챗지피티</b>... <b>챗지피티</b> 같은 AI 많이 쓰잖아요 이걸 그대로 베껴오지않고 조금 수정해도 걸린다는데 도대체 뭐 써서 <b>챗지피티</b>... '}, {'title': '<b>챗지피티</b> 개인정보', 'link': 'https://kin.naver.com/qna/detail.naver?d1id=1&dirId=11003&docId=485467804&qb=7LGX7KeA7ZS87Yuw&enc=utf8', 'description': '<b>챗지피티</b>에서 지금까지 운영자가 보는거 제외하고 타인에게 개인정보가 유출된 사례가 존재하나요? 메일주소나 ip주소 등등 <b>챗지피티</b>의 개인정보 유출 사례가 있습니다. <b>챗지피티</b> 개인정보 유출과 관련된 사례는 아래... '}, {'title': '<b>챗지피티</b> 해킹, 원격조종', 'link': 'https://kin.naver.com/qna/detail.naver?d1id=1&dirId=11001&docId=485270801&qb=7LGX7KeA7ZS87Yuw&enc=utf8', 'description': '<b>챗지피티</b> 어플을 사용하는데 오래 사용하다보면 타자가... <b>챗지피티</b> 앱을 사용하시다가 키보드가 제대로... 앱 오류: <b>챗지피티</b> 앱이 가끔 오류를 일으킬 수 있어요.... <b>챗지피티</b>는 OpenAI가 제공하는 신뢰할 수 있는 서비스이기... '}, {'title': '<b>챗지피티</b> 돈 내면서 쓰는거 좋나요?', 'link': 'https://kin.naver.com/qna/detail.naver?d1id=6&dirId=60101&docId=480556548&qb=7LGX7KeA7ZS87Yuw&enc=utf8', 'description': '... <b>챗 지피티</b> 싸게 이용하는 방법 안내해드릴께요! 겜스고라는 사이트가시면 다른분들이랑 같이 구독해서 저렴하게 이용할수 있는데 프로모션 코드에 MLWYX입력하시면 추가할인되어요! 프로모션 코드 MLWYX 아래 ⬇️ 글 참고하세요'}, {'title': '카피킬러 표절 및 <b>챗지피티</b> 검사 83%', 'link': 'https://kin.naver.com/qna/detail.naver?d1id=11&dirId=110501&docId=484520422&qb=7LGX7KeA7ZS87Yuw&enc=utf8', 'description': '카피킬러 사용해서 표절률이랑 <b>챗지피티</b>? 검사 했는데 83%나오는데 왜 이런가요?? <b>챗지피티</b> 유료라 사용도 안해봤는데… 맞아요. 카피킬러에서 AI(<b>챗지피티</b>) 판별은 원래 높게 나오는 경우 많아요. GPT 안 써도, 말투가 단정하거나... '}]

In [38]:
#함수 작성
def get_naver_kin(keyword, cnt):
    import requests
    import pandas as pd
    import json
    from dotenv import load_dotenv
    import os
    load_dotenv()
    client_id = os.getenv('Client_ID')
    client_secret = os.getenv('Client_Secret')
    url = f'https://openapi.naver.com/v1/search/kin.json?query={keyword}&display={cnt}'
    headers = {'X-Naver-Client-Id':client_id,
              'X-Naver-Client-Secret':client_secret}
    response = requests.get(url, headers=headers)
    #response.status_code
    #items = json.loads(response.text)['items'] : 방법1과 방법2
    items = response.json()['items'] #방법1에서만 가능한 함수
    items_list = []
    for item in items:
        items_list.append([item.get('title').replace('<b>','').replace('</b>',''), #item['title']
                          item.get('link'),
                          item.get('description')
                          ])
    df = pd.DataFrame(items_list, columns=['title', 'link', 'description'])
    return df

In [39]:
get_naver_kin('청바지',20)

,title,link,description
0,영어로 청바지를 뭐라고하나요?,https://kin.naver.com/qna/detail.naver?d1id=11...,영어로 <b>청바지</b>를 뭐라고하나요? 안녕하세요~ 선생님도 매월 시험보는 목동...
1,"전 남자인데, 누워서 청바지를 입으면 고환이 아플 수?",https://kin.naver.com/qna/detail.naver?d1id=7&...,"전 남자인데, 누워서 <b>청바지</b>를 입으면 고환이 아플 수? 안녕하세요. 하..."
2,청바지 없는데 면접취소 할까요?,https://kin.naver.com/qna/detail.naver?d1id=6&...,낼 알바 면접인데 츄리닝만 있고 <b>청바지</b>가 없어요 취소할까요? 아님 <b...
3,고관절 지방이식 후 청바지,https://kin.naver.com/qna/detail.naver?d1id=7&...,"현재 고관절(골반) 지방이식 한 지 두달 가까이 되어가는데,꽉 끼는 <b>청바지</..."
4,임영웅 청바지 입은 사진?,https://kin.naver.com/qna/detail.naver?d1id=3&...,임영웅 사진첩 만들고 있는데요! <b>청바지</b> 입은 사진 갖고 계신분 공유부탁...
5,청바지 세탁,https://kin.naver.com/qna/detail.naver?d1id=8&...,... <b>청바지</b> 구매하고 처음 한번은 드라이크리닝으로 했는데요. 한번 드...
6,미국에서 청바지 가격이 306불입니다 관부가세 얼마나오,https://kin.naver.com/qna/detail.naver?d1id=4&...,<b>청바지</b> 디스쿼드 샌스에서 309불에 사려고 합니다 배대지 이용합니다.....
7,청바지? 면바지도 트레이닝바지인가요?,https://kin.naver.com/qna/detail.naver?d1id=13...,제가 내일 체육대회인데여 트레이닝바지가 된다는데 제가 가지고있는바지중에서 카키색에 ...
8,핀턱 청바지 수선,https://kin.naver.com/qna/detail.naver?d1id=8&...,핀턱있는 <b>청바지</b> 허리 줄일 수 있나용 네! 핀턱 <b>청바지</b>도 ...
9,청바지 이염,https://kin.naver.com/qna/detail.naver?d1id=5&...,... 아니면 진한 <b>청바지</b>는 다 이염이 된다고 봐야하나요ㅠ 진한 <b>...
10,골프 연습장 에서 부츠컷 청바지 입어도 되나요?,https://kin.naver.com/qna/detail.naver?d1id=10...,... 바지가 부츠컷 <b>청바지</b>만 았는데 좀 달라 붙는 거라서.. 가능한가...
11,강아지 청바지 뜯어먹음,https://kin.naver.com/qna/detail.naver?d1id=8&...,8살된 강아지가 제 <b>청바지</b>를 좀 뜯어먹었어요.. 손가락 지문만큼 먹었는...
12,청바지 수선,https://kin.naver.com/qna/detail.naver?d1id=5&...,제가 내일 입고 나가려고 바지를 시켰는데요 혹시 데님 <b>청바지</b>도 허벅지부...
13,청바지는 오랫동안 쓸 수 있나요?,https://kin.naver.com/qna/detail.naver?d1id=8&...,"<b>청바지</b>는 오랫동안 쓸 수 있나요? <b>청바지</b>, 하나 잘 사면 ..."
14,여자들중에 원피스보다 청바지가 예쁜 이유는요?,https://kin.naver.com/qna/detail.naver?d1id=8&...,... 보다 <b>청바지</b>를 입고 있는게 예쁜 이유는요? 여자들 사이에서 <b...
15,체육대회때 흰티에 청바지 입어도 되나요?,https://kin.naver.com/qna/detail.naver?d1id=5&...,체육대회때 흰티에 <b>청바지</b> 입어도 되나요? 체육대회에 흰티와 <b>청바지...
16,8월 초 이탈리아 청바지,https://kin.naver.com/qna/detail.naver?d1id=9&...,... 가는데 <b>청바지</b> 입으면 더울까요ㅠ 더위를 많이 타는 편이라면 더울...
17,청바지는 오랫동안 쓸 수 있나요?,https://kin.naver.com/qna/detail.naver?d1id=5&...,<b>청바지</b>는 오랫동안 쓸 수 있나요? <b>청바지</b>는 품질에 따라 다...
18,청바지에서 파란 물,https://kin.naver.com/qna/detail.naver?d1id=8&...,파란물이 원래 나오나요?<b>청바지</b>입고 크록스 신고 돌아댕겻는데 크록스 발꿈...
19,40대 남자도 청바지를 입나요?,https://kin.naver.com/qna/detail.naver?d1id=8&...,40대 남자도 <b>청바지</b>를 입나요? 보통 20대에 <b>청바지</b> 많이...

### quiz)네이버 open API를 이용해서 청바지 이미지 100건 데이터를 csv파일로 저장
- 데이터 : 제목, 이미지링크, 썸네일링크,높이,폭

In [55]:
import requests
import pandas as pd
from dotenv import load_dotenv
import os
load_dotenv() 
client_id = os.getenv('Client_ID')
client_secret = os.getenv('Client_Secret')
word = "청바지"
url = f'https://openapi.naver.com/v1/search/image?query={word}&display=100'
headers = {'X-Naver-Client-Id': client_id,
           'X-Naver-Client-Secret':client_secret}
response = requests.get(url, headers=headers)
# print(response.text)
items = response.json()['items'] # 방법1에서만 가능한 함수
items_list = []
for idx, item in enumerate(items):
    title = item.get('title')
    link = item.get('link')
    thumbnail = item.get('thumbnail')
    sizeheight = item.get('sizeheight')
    sizewidth = item.get('sizewidth')
    items_list.append({
        'no': idx+1,
        'title': title,
        'link' : link,
        'thumbnail' : thumbnail,
        'sizeheight':sizeheight,
        'sizewidth' :sizewidth
    })
    # link와 thumbnail을 저장
df = pd.DataFrame(items_list)
df

,no,title,link,thumbnail,sizeheight,sizewidth
0,1,BINIWU 심플 빈티지 워싱 청바지 남자 봄가을 루즈핏 통바지 28 빈티지블루,http://shopping.phinf.naver.net/main_5172227/5...,https://search.pstatic.net/common/?type=b150&s...,800,800
1,2,중년 청바지 아이스 팬츠 남성 얇은 슬랙스 바지남 긴바지,http://shopping.phinf.naver.net/main_5314890/5...,https://search.pstatic.net/common/?type=b150&s...,1000,1000
2,3,게스 게스 여성 청바지 플레어 붓컷 미디엄블루 데님팬츠 M YM3D0117,http://shopping.phinf.naver.net/main_5182791/5...,https://search.pstatic.net/common/?type=b150&s...,700,700
3,4,가우리 봄 가을 프리미엄 중년 남성 청바지 CRO 스판 청 팬츠 - 청바지 | 쿠팡,https://thumbnail8.coupangcdn.com/thumbnails/r...,https://search.pstatic.net/sunny/?type=b150&sr...,492,492
4,5,청바지 남자 여름 얇은 레져 텐셀 아메리칸 빈티지 청바지 남자 카우형 남자 스타일 팬츠,http://shopping.phinf.naver.net/main_5188539/5...,https://search.pstatic.net/common/?type=b150&s...,600,600
...,...,...,...,...,...,...
95,96,남자 청바지 타이거 자수 스판 슬림 청바지 ZT120306 28,http://shopping.phinf.naver.net/main_5289686/5...,https://search.pstatic.net/common/?type=b150&s...,800,800
96,97,[쩡대샵] 남자 811원포 청바지 : 쩡대샵,http://shop1.phinf.naver.net/20180919_176/hotj...,https://search.pstatic.net/common/?type=b150&s...,640,640
97,98,하늘 자수 배기 팬츠 칠부 청바지 여 women s jeans 하늘비즈 A8 I09...,http://shopping.phinf.naver.net/main_5463263/5...,https://search.pstatic.net/common/?type=b150&s...,1920,1920
98,99,엄마옷 여성 와이드 청바지 항아리 배기바지,http://shopping.phinf.naver.net/main_5369150/5...,https://search.pstatic.net/common/?type=b150&s...,600,600
99,100,베라 S 187 데님 여성청바지 : 미샵,http://shop1.phinf.naver.net/20231005_74/16964...,https://search.pstatic.net/common/?type=b150&s...,1000,1000

In [56]:

df.loc[3, 'link']

'https://thumbnail8.coupangcdn.com/thumbnails/remote/492x492ex/image/vendor_inventory/images/2017/09/07/17/1/837feb8c-041e-4921-bd39-174fec765a2a.jpg'

In [71]:

df[df['link'].str.find('?')!=-1]

Empty DataFrame
Columns: [no, title, link, thumbnail, sizeheight, sizewidth]
Index: []

In [72]:

df[~df['link'].str.endswith('jpg')].loc[5, 'link']

'http://shop1.phinf.naver.net/20250503_295/1746250611381Vinxl_JPEG/21192829047529977_2039968073.jpeg'

In [75]:
def save_img(attr, idx, query, url):
    import requests
    '{attr}_{idx}_{query}.{확장자} 이미지 저장'
    file_extension = url.split('.')[-1]
    quote_index = file_extension.find('?')
    
    if quote_index != -1:
        file_extension = file_extension[:quote_index]
#     print(file_extension)
    img = requests.get(url).content
    open(f'ch14_image/{attr}_{idx}_{query}.{file_extension}', 'wb').write(img)

In [76]:
save_img('메인', 1, '청바지', df.loc[5, 'link'])

In [77]:
# word image 100개 검색한 데이터는 csv파일로, 이미지는 ch14_image폴더에 저장되는 함수
def get_naver_save_image(word):
    import requests
    import pandas as pd
    from dotenv import load_dotenv
    import os
    load_dotenv() 
    client_id = os.getenv('Client_ID')
    client_secret = os.getenv('Client_Secret')

    url = f'https://openapi.naver.com/v1/search/image?query={word}&display=100'
    headers = {'X-Naver-Client-Id': client_id,
               'X-Naver-Client-Secret':client_secret}
    response = requests.get(url, headers=headers)

    items = response.json()['items'] # 방법1에서만 가능한 함수
    items_list = []
    for idx, item in enumerate(items):
        title = item.get('title')
        link = item.get('link')
        thumbnail = item.get('thumbnail')
        sizeheight = item.get('sizeheight')
        sizewidth = item.get('sizewidth')
        items_list.append({
            'no': idx+1,
            'title': title,
            'link' : link,
            'thumbnail' : thumbnail,
            'sizeheight':sizeheight,
            'sizewidth' :sizewidth
        })
        # link와 thumbnail을 저장
        save_img('메인', idx+1, word, link)
        save_img('썸네일', idx+1, word, thumbnail)
        # 20%, 40%, 60% 80% 지점 message 출력
        if idx/20 == round(idx/20):
            print(f'= = = {idx}% 진행 중입니다 = = =')
    df = pd.DataFrame(items_list)
    df.to_csv(f'ch14_image/{word}.csv', encoding='cp949', index=False)
    print('~ ~ ~ 이미지 및 csv 파일 저장 완료 ~ ~ ~')

In [78]:
get_naver_save_image('청바지')

= = = 0% 진행 중입니다 = = =
= = = 20% 진행 중입니다 = = =
= = = 40% 진행 중입니다 = = =
= = = 60% 진행 중입니다 = = =
= = = 80% 진행 중입니다 = = =
~ ~ ~ 이미지 및 csv 파일 저장 완료 ~ ~ ~

# 2.3 xml 파일
- 기상예측 RSS 활용
http://www.kma.go.kr/repositary/xml/fct/mon/img/fct_mon1rss_108_20250529.xml

In [86]:
from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd

In [87]:
url = 'https://www.kma.go.kr/repositary/xml/fct/mon/img/fct_mon1rss_108_20250529.xml'
response = urlopen(url)
#response.status #response.getcode()
soup = BeautifulSoup(response, 'xml')#pip install lxml
locals = soup.find_all('local_ta')
#locals[1]
items_list = []
for local in locals:
    local_ta_name = local.select_one('local_ta_name')
    week1_normalYear = local.select_one('week1_local_ta_normalYear') #평년기온
    week1_similarRange = local.select_one('week1_local_ta_similarRange') #기온범위
    week1_min = local.select_one('week1_local_ta_minVal')
    week1_max = local.select_one('week1_local_ta_maxVal')
    week2_normalYear = local.select_one('week1_local_ta_normalYear') #평년기온
    week2_similarRange = local.select_one('week1_local_ta_similarRange') #기온범위
    week2_min = local.select_one('week1_local_ta_minVal')
    week2_max = local.select_one('week1_local_ta_maxVal')
    items_list.append({
        '지역':local_ta_name,
        '1주평년기온':week1_normalYear,
        '1주범위':week1_similarRange,
        '1주최저':week1_min,
        '1주최고':week1_max,
        '2주평년기온':week2_normalYear,
        '2주범위':week2_similarRange,
        '2주최저':week2_min,
        '2주최고':week2_max,
    })
pd.DataFrame(items_list)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   no          100 non-null    int64
 1   title       100 non-null    object
 2   link        100 non-null    object
 3   thumbnail   100 non-null    object
 4   sizeheight  100 non-null    object
 5   sizewidth   100 non-null    object
dtypes: int64(1), object(5)
memory usage: 4.8+ KB

# 3. 연습문제
- yes24베스트셀러 정보를 ch14_yes24.csv(ch14_yes24.txt)로 출력
- 작업순서 : 순위, 책이름, 저자, 출판사, 가격(1~48위) => 리스트 => 데이터프레임 => csv => txt

In [94]:
from urllib.request import urlopen

url = 'http://www.yes24.com/24/category/bestseller'
response = urlopen(url)
soup = BeautifulSoup(response, 'html.parser')

yesBestList = soup.select('div.bSGoodsSecArea > ul > li')

items_list = []
for idx, item in yesBestList:
    rank = idx+1
    title = yesBestList.select('info row.info_name')
    writer = yesBestList.select('authPub.info_auth')

[<li class="" data-goods-no="145629000" data-iy-no="0" data-statgb="02">
 <div class="itemUnit">
 <div class="item_img">
 <div class="img_canvas">
 <div class="img_upper">
 <em class="ico rank">1</em>
 <span class="rank_info rank_even">
 <span class="ico"></span><em class="txt rank"></em><em class="txt">위 상승</em>
 </span>
 </div>
 <span class="img_item">
 <span class="img_grp">
 <a class="lnk_img" href="/product/goods/145629000" onclick="wiseLogV2('BS', '001_005_001', ''); ">
 <em class="img_bdr">
 <img alt="청춘의 독서" border="0" class="lazy" data-original="https://image.yes24.com/goods/145629000/L" src="https://image.yes24.com/momo/Noimg_L.jpg"/>
 </em>
 </a>
 </span>
 </span>
 </div>
 <div class="img_btn">
 <a class="btnC btn_preview" href="javascript:yes24GU.openPreviewCheck(145629000); wiseLogV2('BS', '001_005_011', '');"><span class="bWrap"><em class="txt">미리보기</em></span></a>
 </div>
 </div>
 <div class="item_info">
 <div class="info_row info_keynote">
 <span class="gd_keynote" id="spanGdKeynote">
 <a class="iconC tBook" href="/24/Category/More/001014?ElemNo=13&amp;ElemSeq=1&amp;Gcode=000_030_001"><em class="txt">오늘의책</em></a>
 <!-- 클래스24 상품일 경우 -->
 </span>
 <script type="text/javascript">
         if ($('#spanGdKeynote').children().length == 0) {
             $('#spanGdKeynote').remove();
         }
     </script>
 </div>
 <div class="info_row info_name">
 <span class="gd_res">[도서]</span>
 <a class="gd_name" href="/product/goods/145629000" onclick="wiseLogV2('BS', '001_005_001', ''); ">청춘의 독서</a>
 <span class="gd_nameE">세상을 바꾼 위험하고 위대한 생각들</span>
 <span class="gd_feature">
                         [
 <span class="feature">특별증보판</span><span class="feature">양장</span>                        ]
                     </span>
 <a class="bgYUI ico_nWin" href="/product/goods/145629000" onclick="wiseLogV2('BS', '001_005_001', ''); " target="_blank">청춘의 독서 새창이동</a>
 </div>
 <div class="info_row info_pubGrp">
 <span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%259C%25A0%25EC%258B%259C%25EB%25AF%25BC&amp;authorNo=409&amp;author=유시민" target="">유시민</a> 저
                             </span>
 <span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%9b%85%ec%a7%84%ec%a7%80%ec%8b%9d%ed%95%98%ec%9a%b0%ec%8a%a4&amp;query=%25EC%259B%2585%25EC%25A7%2584%25EC%25A7%2580%25EC%258B%259D%25ED%2595%2598%25EC%259A%25B0%25EC%258A%25A4">웅진지식하우스</a></span>
 <span class="authPub info_date">2025년 04월</span>
 </div>
 <dl class="info_present">
 <dt><em class="bgYUI ico_present">구매혜택</em></dt>
 <dd>
 <a href="https://event.yes24.com/template?EventNo=258420">유시민 수건 (포인트 차감)</a>
 </dd>
 </dl>
 <div class="info_row info_price">
 <span class="txt_sale"><em class="num">10</em>%</span>
 <strong class="txt_num"><em class="yes_b">17,010</em>원</strong>
 <span class="txt_num dash"><em class="yes_m">18,900</em>원</span>
 <span class="yPoint"><em class="bgYUI ico_point">포인트적립</em>940원</span>
 </div>
 <div class="info_row info_rating">
 <span class="saleNum">
                                 판매지수 804,042
                             </span>
 <span class="rating_rvCount">
 <a href="https://www.yes24.com/product/goods/145629000?ReviewYn=Y" onclick="wiseLogV2('BS', '001_005_004', '');"><em class="bit">회원리뷰</em>(<em class="txC_blue">221</em>건)</a>
 </span>
 <span class="rating_grade">
 <span class="bgYUI tRating tRating_10">리뷰 총점</span><em class="yes_b">9.5</em>
 <span class="moreRatingArea">
 <span class="moreRatingBtn">
 <a class="bgYUI" href="javascript:void(0);" onclick="toggleLiCont(this,$('.sGLi'),event);">정보 더 보기/감추기</a>
 </span>
 <span class="moreRatingLi">
 <span class="moreRatingLiRow">
 <ul class="yesAlertLi">
 <li><em class="bl_dot bgYUI"> </em>종이책 리뷰 (69건)</li>
 <li><em class="bl_dot bgYUI"> </em>eBook 리뷰 (0건)</li>
 <li><em class="bl_dot bgYUI"> </em>종이책 한줄평 (150건)</li>
 <li><em class="bl_dot bgYUI"> </em>eBook 한줄평 (2건)</li>
 </ul>
 </span>
 </span>
 </span>
 </span>
 </div>
 <div class="info_row info_deli" name="delvTextArea"></div>
 <div class="info_row info_signature">
                     특별증보판
                 </div>
 <div class="info_row info_tag">
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EB%258F%2585%25EC%2584%259C%25EC%25B2%2598%25EB%25B0%25A9%25EC%25A0%2584&amp;hashNm=%eb%8f%85%ec%84%9c%ec%b2%98%eb%b0%a9%ec%a0%84" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '독서처방전', '145629000','2233');">#독서처방전</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EB%258F%2585%25EC%2584%259C%25EA%25B6%258C%25EC%259E%25A5&amp;hashNm=%eb%8f%85%ec%84%9c%ea%b6%8c%ec%9e%a5" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '독서권장', '145629000','1756');">#독서권장</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%25B1%2585%25EC%2597%2590%25EA%25B4%2580%25ED%2595%259C%25EC%25B1%2585&amp;hashNm=%ec%b1%85%ec%97%90%ea%b4%80%ed%95%9c%ec%b1%85" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '책에관한책', '145629000','623');">#책에관한책</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EB%258F%2585%25EC%2584%259C%25EB%25B2%2595&amp;hashNm=%eb%8f%85%ec%84%9c%eb%b2%95" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '독서법', '145629000','2748');">#독서법</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EB%258F%2585%25EC%2584%259C%25ED%2595%2598%25EA%25B8%25B0%25EC%25A2%258B%25EC%259D%2580%25EB%2582%25A0&amp;hashNm=%eb%8f%85%ec%84%9c%ed%95%98%ea%b8%b0%ec%a2%8b%ec%9d%80%eb%82%a0" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '독서하기좋은날', '145629000','5667');">#독서하기좋은날</a>
 </span>
 </div>
 <div class="info_row info_event">
 <div class="event">
 <span class="iconC freeD"><em class="txt">이벤트</em></span>
 <span class="iconC"><em class="txt">사은품</em></span>
 <span class="iconC"><em class="txt">기획전</em></span>
 <span class="txt"><a href="https://event.yes24.com/earlyReader">이달의 책 5월 :  아크릴 액자 </a></span>
 <span class="date">(25.05.01 ~ 25.05.31)</span>
 </div>
 </div>
 <div class="info_row info_relG">
                     관련상품 :                            <span class="relG"><a href="/product/goods/146477263">eBook <span class="relG_num">11,970원</span></a></span>
 </div>
 </div>
 <div class="item_btnCol">
 <span class="btn_row">
 <span class="chkBox" style=""><label><input class="basic" data-goodsno="145629000" id="ordChk_145629000" name="ORD_GOODS_CHKBOX" style="" type="checkbox"/><span class="bgYUI chk"></span></label></span>
 <span class="numBox">
 <span class="yesIpt ipt_wSizeF">
 <input class="ac yes_m" id="ordCnt_145629000" maxlength="3" name="ORD_GOODS_CNT" onkeyup="return checkNumeric(this);" style="ime-mode:disabled !important" title="수량설정" type="text" value="1"/>
 </span>
 <button class="minus" onclick="order_payment.downOrderCount('145629000'); wiseLogV2('BS', '001_005_006', '');" type="button"><span class="bgYUI">수량감소</span></button>
 <button class="plus" onclick="order_payment.upOrderCount('145629000'); wiseLogV2('BS', '001_005_006', '');" type="button"><span class="bgYUI">수량증가</span></button>
 </span>
 </span>
 <a class="btnC btn_blue" href="javascript:void(0);" onclick="order_payment.addCartV3('145629000', '', this, '', '', '', '', 'Search', true); wiseLogV2('BS', '001_005_007', '');"><span class="bWrap"><em class="txt">카트에 넣기</em></span></a>
 <a class="btnC btn_sBlue" href="javascript:void(0);" onclick="order_payment.orderDirectV3('145629000', '', this, '', '', '', '', 'Search'); wiseLogV2('BS', '001_005_008', '');"><span class="bWrap"><em class="txt">바로구매</em></span></a>
 <a class="btnC" href="javascript:void(0);" name="btnList" onclick="order_payment.addMyListV3('145629000', '', '', true, ''); wiseLogV2('BS', '001_005_010', '');;"><span class="bWrap"><em class="txt">리스트에 넣기</em></span></a>
 <input id="ordOpt_145629000" name="ORD_GOODS_OPT" type="hidden" value='{"goods_no":145629000,"goods_seq":1,"order_limit_yn":"N","order_remain_count":0,"event_no":0,"add_cart_yn":"Y","goods_state":"02","order_limit_count":0,"resource_key":"01","limit_age_yn":"N","limit_age":0,"member_age":0,"goods_name":"청춘의 독서","noint_quotamonth":0,"min_cnt":0,"max_cnt":0,"opt_salepr":0,"opt_yn":"N","opt_inst_yn":"N","flat_rate_yn":null,"rent_goods_yn":"N","bookclue_yn":"N","goods_gb":"01","goodsSortNo":"001014","goodsSortNm":"인문","goodsAuth":"&lt;유시민&gt; 저","shopPrice":18900.00,"salePrice":17010.00,"discountShopPrice":1890.00}'>
 </input></div>
 </div>
 </li>,
 <li class="" data-goods-no="112925092" data-iy-no="0" data-statgb="02">
 <div class="itemUnit">
 <div class="item_img">
 <div class="img_canvas">
 <div class="img_upper">
 <em class="ico rank">2</em>
 <span class="rank_info rank_even">
 <span class="ico"></span><em class="txt rank"></em><em class="txt">위 상승</em>
 </span>
 </div>
 <span class="img_item">
 <span class="img_grp">
 <a class="lnk_img" href="/product/goods/112925092" onclick="wiseLogV2('BS', '001_005_001', ''); ">
 <em class="img_bdr">
 <img alt="엄마의 말 연습" border="0" class="lazy" data-original="https://image.yes24.com/goods/112925092/L" src="https://image.yes24.com/momo/Noimg_L.jpg"/>
 </em>
 </a>
 </span>
 </span>
 </div>
 <div class="img_btn">
 <a class="btnC btn_preview" href="javascript:yes24GU.openPreviewCheck(112925092); wiseLogV2('BS', '001_005_011', '');"><span class="bWrap"><em class="txt">미리보기</em></span></a>
 </div>
 </div>
 <div class="item_info">
 <div class="info_row info_keynote">
 <span class="gd_keynote" id="spanGdKeynote">
 <a class="iconC tBook" href="/24/Category/More/001014?ElemNo=13&amp;ElemSeq=1&amp;Gcode=000_030_001"><em class="txt">오늘의책</em></a> <a class="iconC boyI" href="/campaign/00_corp/2022/boyFinal.aspx"><em class="txt">2022 올해의 책</em></a>
 <!-- 클래스24 상품일 경우 -->
 </span>
 <script type="text/javascript">
         if ($('#spanGdKeynote').children().length == 0) {
             $('#spanGdKeynote').remove();
         }
     </script>
 </div>
 <div class="info_row info_name">
 <span class="gd_res">[도서]</span>
 <a class="gd_name" href="/product/goods/112925092" onclick="wiseLogV2('BS', '001_005_001', ''); ">엄마의 말 연습</a>
 <span class="gd_nameE">화내지 않고 사랑하는 마음을 오롯이 전하는 39가지 존중어 수업</span>
 <a class="bgYUI ico_nWin" href="/product/goods/112925092" onclick="wiseLogV2('BS', '001_005_001', ''); " target="_blank">엄마의 말 연습 새창이동</a>
 </div>
 <div class="info_row info_pubGrp">
 <span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%259C%25A4%25EC%25A7%2580%25EC%2598%2581&amp;authorNo=275131&amp;author=윤지영" target="">윤지영</a> 저
                             </span>
 <span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%b9%b4%ec%8b%9c%ec%98%a4%ed%8e%98%ec%95%84&amp;query=%25EC%25B9%25B4%25EC%258B%259C%25EC%2598%25A4%25ED%258E%2598%25EC%2595%2584">카시오페아</a></span>
 <span class="authPub info_date">2022년 09월</span>
 </div>
 <dl class="info_present">
 <dt><em class="bgYUI ico_present">구매혜택</em></dt>
 <dd>
 <a href="https://event.yes24.com/template?EventNo=250588">[가정살림/건강취미 요즘의 책] 밀크글라스/리버서블 백/찻잔 세트 (포인트차감)</a>
 </dd>
 </dl>
 <div class="info_row info_price">
 <span class="txt_sale"><em class="num">10</em>%</span>
 <strong class="txt_num"><em class="yes_b">15,750</em>원</strong>
 <span class="txt_num dash"><em class="yes_m">17,500</em>원</span>
 <span class="yPoint"><em class="bgYUI ico_point">포인트적립</em>870원</span>
 </div>
 <div class="info_row info_rating">
 <span class="saleNum">
                                 판매지수 139,086
                             </span>
 <span class="rating_rvCount">
 <a href="https://www.yes24.com/product/goods/112925092?ReviewYn=Y" onclick="wiseLogV2('BS', '001_005_004', '');"><em class="bit">회원리뷰</em>(<em class="txC_blue">133</em>건)</a>
 </span>
 <span class="rating_grade">
 <span class="bgYUI tRating tRating_10">리뷰 총점</span><em class="yes_b">9.8</em>
 <span class="moreRatingArea">
 <span class="moreRatingBtn">
 <a class="bgYUI" href="javascript:void(0);" onclick="toggleLiCont(this,$('.sGLi'),event);">정보 더 보기/감추기</a>
 </span>
 <span class="moreRatingLi">
 <span class="moreRatingLiRow">
 <ul class="yesAlertLi">
 <li><em class="bl_dot bgYUI"> </em>종이책 리뷰 (71건)</li>
 <li><em class="bl_dot bgYUI"> </em>eBook 리뷰 (0건)</li>
 <li><em class="bl_dot bgYUI"> </em>종이책 한줄평 (62건)</li>
 <li><em class="bl_dot bgYUI"> </em>eBook 한줄평 (0건)</li>
 </ul>
 </span>
 </span>
 </span>
 </span>
 </div>
 <div class="info_row info_deli" name="delvTextArea"></div>
 <div class="info_row info_tag">
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25ED%2583%259C%25EC%259A%2594%25EB%25AF%25B8%25EB%2584%25A4&amp;hashNm=%ed%83%9c%ec%9a%94%eb%af%b8%eb%84%a4" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '태요미네', '112925092','7275');">#태요미네</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%2598%25AC%25ED%2595%25B4%25EC%259D%2598%25EC%25B1%2585&amp;hashNm=%ec%98%ac%ed%95%b4%ec%9d%98%ec%b1%85" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '올해의책', '112925092','2716');">#올해의책</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EB%25A7%2590%25EC%2598%2588%25EC%2581%2598%25EA%25B2%258C%25ED%2595%2598%25EB%258A%2594%25EC%2582%25AC%25EB%259E%258C%25EC%259D%25B4%25EC%25A2%258B%25EB%258D%2594%25EB%259D%25BC&amp;hashNm=%eb%a7%90%ec%98%88%ec%81%98%ea%b2%8c%ed%95%98%eb%8a%94%ec%82%ac%eb%9e%8c%ec%9d%b4%ec%a2%8b%eb%8d%94%eb%9d%bc" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '말예쁘게하는사람이좋더라', '112925092','4149');">#말예쁘게하는사람이좋더라</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%2597%2584%25EB%25A7%2588%25EA%25B0%2580%25EB%2590%259C%25EB%258B%25A4%25EB%258A%2594%25EA%25B2%2583&amp;hashNm=%ec%97%84%eb%a7%88%ea%b0%80%eb%90%9c%eb%8b%a4%eb%8a%94%ea%b2%83" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '엄마가된다는것', '112925092','3431');">#엄마가된다는것</a>
 </span>
 </div>
 <div class="info_row info_event">
 <div class="event">
 <span class="iconC freeD"><em class="txt">이벤트</em></span>
 <span class="iconC"><em class="txt">기획전</em></span>
 <span class="txt"><a href="https://event.yes24.com/template?EventNo=257171">[훈육 고민 해결] 이럴 땐 이렇게! 훈육 고민 10가지에 대한 김보경 박사의 솔루션!</a></span>
 <span class="date">(25.03.19 ~ 00.12.31)</span>
 </div>
 </div>
 </div>
 <div class="item_btnCol">
 <span class="btn_row">
 <span class="chkBox" style=""><label><input class="basic" data-goodsno="112925092" id="ordChk_112925092" name="ORD_GOODS_CHKBOX" style="" type="checkbox"/><span class="bgYUI chk"></span></label></span>
 <span class="numBox">
 <span class="yesIpt ipt_wSizeF">
 <input class="ac yes_m" id="ordCnt_112925092" maxlength="3" name="ORD_GOODS_CNT" onkeyup="return checkNumeric(this);" style="ime-mode:disabled !important" title="수량설정" type="text" value="1"/>
 </span>
 <button class="minus" onclick="order_payment.downOrderCount('112925092'); wiseLogV2('BS', '001_005_006', '');" type="button"><span class="bgYUI">수량감소</span></button>
 <button class="plus" onclick="order_payment.upOrderCount('112925092'); wiseLogV2('BS', '001_005_006', '');" type="button"><span class="bgYUI">수량증가</span></button>
 </span>
 </span>
 <a class="btnC btn_blue" href="javascript:void(0);" onclick="order_payment.addCartV3('112925092', '', this, '', '', '', '', 'Search', true); wiseLogV2('BS', '001_005_007', '');"><span class="bWrap"><em class="txt">카트에 넣기</em></span></a>
 <a class="btnC btn_sBlue" href="javascript:void(0);" onclick="order_payment.orderDirectV3('112925092', '', this, '', '', '', '', 'Search'); wiseLogV2('BS', '001_005_008', '');"><span class="bWrap"><em class="txt">바로구매</em></span></a>
 <a class="btnC" href="javascript:void(0);" name="btnList" onclick="order_payment.addMyListV3('112925092', '', '', true, ''); wiseLogV2('BS', '001_005_010', '');;"><span class="bWrap"><em class="txt">리스트에 넣기</em></span></a>
 <input id="ordOpt_112925092" name="ORD_GOODS_OPT" type="hidden" value='{"goods_no":112925092,"goods_seq":1,"order_limit_yn":"N","order_remain_count":0,"event_no":0,"add_cart_yn":"Y","goods_state":"02","order_limit_count":0,"resource_key":"01","limit_age_yn":"N","limit_age":0,"member_age":0,"goods_name":"엄마의 말 연습","noint_quotamonth":0,"min_cnt":0,"max_cnt":0,"opt_salepr":0,"opt_yn":"N","opt_inst_yn":"N","flat_rate_yn":null,"rent_goods_yn":"N","bookclue_yn":"N","goods_gb":"01","goodsSortNo":"001017","goodsSortNm":"가정 살림","goodsAuth":"&lt;윤지영&gt; 저 ","shopPrice":17500.00,"salePrice":15750.00,"discountShopPrice":1750.00}'>
 </input></div>
 </div>
 </li>,
 <li class="" data-goods-no="144021119" data-iy-no="0" data-statgb="02">
 <div class="itemUnit">
 <div class="item_img">
 <div class="img_canvas">
 <div class="img_upper">
 <em class="ico rank">3</em>
 <span class="rank_info rank_up">
 <span class="ico"></span><em class="txt rank">1</em><em class="txt">위 상승</em>
 </span>
 </div>
 <span class="img_item">
 <span class="img_grp">
 <a class="lnk_img" href="/product/goods/144021119" onclick="wiseLogV2('BS', '001_005_001', ''); ">
 <em class="img_bdr">
 <img alt="단 한 번의 삶" border="0" class="lazy" data-original="https://image.yes24.com/goods/144021119/L" src="https://image.yes24.com/momo/Noimg_L.jpg"/>
 </em>
 </a>
 </span>
 </span>
 </div>
 <div class="img_btn">
 <a class="btnC btn_preview" href="javascript:yes24GU.openPreviewCheck(144021119); wiseLogV2('BS', '001_005_011', '');"><span class="bWrap"><em class="txt">미리보기</em></span></a>
 </div>
 </div>
 <div class="item_info">
 <div class="info_row info_keynote">
 <span class="gd_keynote" id="spanGdKeynote">
 <a class="iconC tBook" href="/24/Category/More/001014?ElemNo=13&amp;ElemSeq=1&amp;Gcode=000_030_001"><em class="txt">오늘의책</em></a>
 <!-- 클래스24 상품일 경우 -->
 </span>
 <script type="text/javascript">
         if ($('#spanGdKeynote').children().length == 0) {
             $('#spanGdKeynote').remove();
         }
     </script>
 </div>
 <div class="info_row info_name">
 <span class="gd_res">[도서]</span>
 <a class="gd_name" href="/product/goods/144021119" onclick="wiseLogV2('BS', '001_005_001', ''); ">단 한 번의 삶</a>
 <span class="gd_feature">
                         [
 <span class="feature">양장</span>                        ]
                     </span>
 <a class="bgYUI ico_nWin" href="/product/goods/144021119" onclick="wiseLogV2('BS', '001_005_001', ''); " target="_blank">단 한 번의 삶 새창이동</a>
 </div>
 <div class="info_row info_pubGrp">
 <span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B9%2580%25EC%2598%2581%25ED%2595%2598&amp;authorNo=673&amp;author=김영하" target="">김영하</a> 저
                             </span>
 <span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%eb%b3%b5%eb%b3%b5%ec%84%9c%ea%b0%80&amp;query=%25EB%25B3%25B5%25EB%25B3%25B5%25EC%2584%259C%25EA%25B0%2580">복복서가</a></span>
 <span class="authPub info_date">2025년 04월</span>
 </div>
 <dl class="info_present">
 <dt><em class="bgYUI ico_present">구매혜택</em></dt>
 <dd>
 <a href="https://event.yes24.com/earlyReader">[이달의 책 5월] &lt;디즈니 캐릭터&gt; 아크릴 액자 (포인트차감) </a>
 </dd>
 </dl>
 <div class="info_row info_price">
 <span class="txt_sale"><em class="num">10</em>%</span>
 <strong class="txt_num"><em class="yes_b">15,120</em>원</strong>

### 2) 버스위치정보 조회(OpenAPI활용)
    * 서울특별시_노선정보조회 서비스(busRouteId, stationNm,-정류소명, station-정류소id
    * 서울특별시_버스위치정보조회 서비스(busRouteId->버스들위치)

In [ ]:
# step1 : 버스번호 -> busRouteId
#노선정보조회 서비스 3번 getBusRouteList서비스

In [1]:
from dotenv import load_dotenv
import os
load_dotenv()#dotenv_path='.env'
# print('key=',os.getenv('key'))
# print('skey=',os.getenv('skey'))

True

In [5]:
import requests
from bs4 import BeautifulSoup
from urllib.request import urlretrieve #url경로파일을 내pc에 저장
from urllib.parse import quote
busNum = '마포01'
busNum = '162'
key = os.getenv('key')
url1 = f'http://ws.bus.go.kr/api/rest/busRouteInfo/getBusRouteList?ServiceKey={key}&strSrch={busNum}'
#print(url1)
# response = requests.get(url)
# soup = BeautifulSoup(response.text, 'xml')
savefilename = 'data/ch14_busInfo.xml'
urlretrieve(url1, savefilename) #url경로 파일을 savefilename으로 저장
xml = open(savefilename, 'r', encoding='utf-8').read()
soup = BeautifulSoup(xml, 'xml')

for item in soup.select('itemList'):
    busRouteNm = item.select_one('busRouteNm').text
    if busRouteNm == busNum:
        busRouteId = item.select_one('busRouteId').text
        break
print('busRouteId:', busRouteId)

busRouteId: 100100034

In [ ]:
# step2 : busRouteId로 버스 정류장 목록(정류장이름과 정류장 id)
#노선정보조회 서비스 4번 getStaionsByRouteList

In [21]:
import pandas as pd
url2 = f'http://ws.bus.go.kr/api/rest/busRouteInfo/getStaionByRoute?ServiceKey={key}&busRouteId={busRouteId}'
print(url2)
response = requests.get(url2)
soup = BeautifulSoup(response.text, "xml")
itemLists = soup.find_all('itemList')
print(busNum + '번 정류장 갯수 : ', len(itemLists))
bus_station = []
for itemList in itemLists:
    #정류장이름, 정류장id, 경도, 위도
    stationNm = itemList.find('stationNm').text
    station = itemList.find('station').text
    gpsX = itemList.find('gpsX').text
    gpsY = itemList.find('gpsY').text
    bus_station.append([stationNm, station, gpsX, gpsY])
df = pd.DataFrame(bus_station, columns=['정류소명', 'id', '경도', '위도'])
df.head()

http://ws.bus.go.kr/api/rest/busRouteInfo/getStaionByRoute?ServiceKey=kWiLqR5an3qgHfkycjPmjxAie5mGGzW0LuPktrSNA3kqpsmWfsLSW9TxR9k0khrZgJLecVcO88n5LsStz845eg%3D%3D&busRouteId=100100034
162번 정류장 갯수 :  77

             정류소명         id              경도             위도
0         정릉산장아파트  107000071      127.003343      37.616712
1    정릉4동주민센터.경국사  107000073      127.006345      37.613529
2     북한산보국문역2번출구  107000518  127.0079858233   37.612293899
3  성북청수도서관.정릉4동성당  107000075  127.0084193769  37.6115696748
4          정릉시장입구  107000077  127.0098212542  37.6084653256

In [22]:
 # step3 : busRouteId로 버스 위치 정보 조회 2번 getBusPosByRtidList

url3 = f'http://ws.bus.go.kr/api/rest/buspos/getBusPosByRtid?ServiceKey={key}&busRouteId={busRouteId}'
print(url3)
response = requests.get(url3)
soup = BeautifulSoup(response.text, "xml")
bus_position = []
itemLists = soup.select('itemList')
print('운행중인 버스 수 : ', len(itemLists))
for itemList in soup.select('itemList'):
    #차량번호, 혼잡도, 경도, 위도, 최종정류장id(lastStnId), 다음정류장id, 도착소요시간
    plainNo = itemList.select_one('plainNo').text
    congetion = itemList.select_one('congetion').text
    congetion = "여유"if congetion =='3'\
            else "보통" if congetion=='4'\
            else"혼잡" if congetion =='5'\
            else "매우혼잡"
    gpsX = itemList.select_one('gpsX').text
    gpsY = itemList.select_one('gpsY').text
    lastStnId = itemList.select_one('lastStnId').text
    nextStId = itemList.select_one('nextStId').text
    nextStTm = itemList.select_one('nextStTm').text
    bus_position.append({
        '차량번호':plainNo,
        '혼잡도':congetion,
        '경도':gpsX,
        '위도':gpsY,
        '최종정류소id':lastStnId,
        '다음정류소id':nextStId,
        '도착소요시간':nextStTm,
    })
df_pos = pd.DataFrame(bus_position)
df_pos.head()

http://ws.bus.go.kr/api/rest/buspos/getBusPosByRtid?ServiceKey=kWiLqR5an3qgHfkycjPmjxAie5mGGzW0LuPktrSNA3kqpsmWfsLSW9TxR9k0khrZgJLecVcO88n5LsStz845eg%3D%3D&busRouteId=100100034
운행중인 버스 수 :  21

        차량번호 혼잡도          경도         위도    최종정류소id    다음정류소id 도착소요시간
0  서울74사1967  여유  127.006345  37.613529  107000073  107000079    274
1  서울70사6556  여유  127.013733   37.60061  107000170  101000042   1632
2  서울74사3008  여유  127.009134  37.589851  107000009  101000042   1184
3  서울74사1537  여유  126.984204  37.576022  100000369  101000042    538
4  서울74사1618  여유  126.982458  37.565518  101000141  101000042    123

In [25]:
#id가 107000168인 정류소명
df.loc[df['id'] == '107000168', '정류소명'].iloc[0]

'정릉입구.정릉역'

In [35]:
def station_name(row):
    row['최종정류소명'] = df.loc[df['id'] == row['최종정류소id'], '정류소명'].iloc[0]
    row['다음정류소명'] = df.loc[df['id'] == row['다음정류소id'], '정류소명'].iloc[0]
    return row

In [36]:
station_name(df_pos.loc[0])

차량번호          서울74사1967
혼잡도                  여유
경도           127.006345
위도            37.613529
최종정류소id       107000073
다음정류소id       107000079
도착소요시간              274
최종정류소명     정릉4동주민센터.경국사
다음정류소명           정릉우체국앞
Name: 0, dtype: object

In [39]:
df_pos = df_pos.apply(station_name, axis=1)
df_pos.sample()

,차량번호,혼잡도,경도,위도,최종정류소id,다음정류소id,도착소요시간,최종정류소명,다음정류소명
4,서울74사1618,여유,126.982458,37.565518,101000141,101000042,123,을지로입구역.광교,해운센터.롯데영플라자

In [40]:
# 컬럼명에 id가 포함된 컬럼 제거
drop_true = df_pos.columns.str.contains('id')
drop_column_name = df_pos.columns[drop_true]
df_pos.drop(drop_column_name, axis=1)

,차량번호,혼잡도,경도,위도,도착소요시간,최종정류소명,다음정류소명
0,서울74사1967,여유,127.006345,37.613529,274,정릉4동주민센터.경국사,정릉우체국앞
1,서울70사6556,여유,127.013733,37.60061,1632,아리랑고개.아리랑시네미디어센터,해운센터.롯데영플라자
2,서울74사3008,여유,127.009134,37.589851,1184,삼선교.한성대학교,해운센터.롯데영플라자
3,서울74사1537,여유,126.984204,37.576022,538,안국역.서울공예박물관,해운센터.롯데영플라자
4,서울74사1618,여유,126.982458,37.565518,123,을지로입구역.광교,해운센터.롯데영플라자
5,서울74사3372,여유,126.971781,37.545977,275,갈월동.숙대입구역10번출구,남영역
6,서울70사6557,여유,126.966578,37.538316,439,용산꿈나무종합타운.원효로우체국,시범아파트.대교아파트
7,서울74사3366,여유,126.930784,37.518587,1091,KBS별관,여의도역6번출구
8,서울74사1604,여유,126.924228,37.521911,914,여의도역5번출구,여의도역6번출구
9,서울70사6549,여유,126.917623,37.528036,639,국회의사당역5번출구,여의도역6번출구
10,서울74사2296,여유,126.926771,37.518745,551,샛강역4번출구.여의도자이,원효로3가
11,서울74사2220,여유,126.970142,37.541096,228,용산경찰서,남영역
12,서울74사8118,여유,126.97236,37.541978,437,남영역,서울역버스환승센터.강우규의거터
13,서울70사6554,여유,126.97297,37.555224,412,서울역버스환승센터.강우규의거터,명동.롯데영플라자
14,서울74사3032,여유,126.982353,37.564412,1124,명동.롯데영플라자,혜화역2번출구.마로니에공원
15,서울70사6553,여유,126.983093,37.572041,730,조계사.종로경찰서,혜화역2번출구.마로니에공원
16,서울70사6560,여유,126.99684,37.575955,400,창덕궁.돈화문국악당,혜화역2번출구.마로니에공원
17,서울74사3360,여유,127.014794,37.597423,153,돈암2동주민센터입구.흥천사,아리랑고개.아리랑시네미디어센터
18,서울74사2216,여유,127.011315,37.605609,116,정릉우체국앞,정릉입구.정릉역
19,서울74사2218,여유,127.008329,37.612084,117,북한산보국문역1번출구,정릉입구.정릉역
20,서울70사6558,여유,127.006157,37.614597,117,정릉4동주민센터.경국사,정릉입구.정릉역

# 4절-1. 연습문제