In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:86% !important;}
div.cell.code_cell.rendered{width:100%;}
div.CodeMirror {font-family:Consolas; font-size:15pt;}
div.output {font-size:15pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:15pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:15px;}
</style>
"""))

<font size="5" color="red">ch14. 웹데이터수집</font>
# 1절. BeautifuSoup과 parser
```pip install bs4``` 아나콘다를 설치하면 7500여개의 패키지 설치
- 공식 사이트: https://www.crummy.com/software/BeautifulSoup/
- Docs : https://www.crummy.com/software/BeautifulSoup/bs4/doc/

In [15]:
import requests #HTTP 요청 처리 lib
from requests_file import FileAdapter

In [16]:
s = requests.Session() #HTTP요청관리를 위한 세션 객체
s.mount("file://", FileAdapter())
response = s.get('file:///ai_x/lecNote/01_python/data/ch14_sample.html')
response

In [17]:
response.status_code
#200: 정상
#404: 없는 페이지
#406: get, post오류

200

In [18]:
ex = response.content #바이너리 형식의 내용
ex

b'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text"title="greeting">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90 \xec\x95\x88\xec\x9d\x98 \xeb\x82\xb4\xec\x9a\xa9</div>\r\n  <p>CSS \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\x8a\x94 \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xea\xb3\xb3\xec\x97\x90\xec\x84\x9c \xed\x99\x9c\xec\x9a\xa9\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4</p>\r\n  <div class="contents">\r\n    \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\xa5\xbc \xec\x96\xb4\xeb\x96\xbb\xea\xb2\x8c \xec\x9e\x91\xec\x84\xb1\xed\x95\x98\xeb\x8a\x90\xeb\x83\x90\xec\x97\x90 \xeb\x94\xb0\xeb\x9d\xbc\r\n    <span>\xeb\x8b\xa4\xeb\xa5\xb8<b>\xec\x9a\x94\xec\x86\x8c\xea\xb0\x80 \xeb\xb0\x98\xed\x99\x98</b></span>\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4\r\n  </div>\r\n  <div>CSS \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\x8a\x94 \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xea\xb3\xb3\xec\x97\x90 <b>\xed\x99\x9c\xec\x9a\xa9</b>\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4</div>\r\n</body>\r\n</html>'

In [19]:
ex.decode('utf-8')

'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text"title="greeting">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject 선택자 안의 내용</div>\r\n  <p>CSS 선택자는 다양한 곳에서 활용됩니다</p>\r\n  <div class="contents">\r\n    선택자를 어떻게 작성하느냐에 따라\r\n    <span>다른<b>요소가 반환</b></span>됩니다\r\n  </div>\r\n  <div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>\r\n</body>\r\n</html>'

In [20]:
response.text

'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text"title="greeting">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject 선택자 안의 내용</div>\r\n  <p>CSS 선택자는 다양한 곳에서 활용됩니다</p>\r\n  <div class="contents">\r\n    선택자를 어떻게 작성하느냐에 따라\r\n    <span>다른<b>요소가 반환</b></span>됩니다\r\n  </div>\r\n  <div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>\r\n</body>\r\n</html>'

In [21]:
#html 파싱
from bs4 import BeautifulSoup
soup = BeautifulSoup(response.content, #response.text
                    "html.parser")
soup

<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
</head>
<body>
<h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>
<h1 class="css">Hi, CSS</h1>
<div id="subject">subject 선택자 안의 내용</div>
<p>CSS 선택자는 다양한 곳에서 활용됩니다</p>
<div class="contents">
    선택자를 어떻게 작성하느냐에 따라
    <span>다른<b>요소가 반환</b></span>됩니다
  </div>
<div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>
</body>
</html>

In [24]:
# soup.select_one('선택자') : 해당 선택자 처음 하나만
el = soup.select_one('h1') #처음 나오는 h1태그 하나만
print('el:',el)
print('el.text:',el.text)
print('el.string:',el.string)
print('el의 속성들:',el.attrs)
print('el의 title속성:', el.attrs['title'])
print('el의 이름: ', el.name)

el: <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>
el.text: Hello, CSS
el.string: Hello, CSS
el의 속성들: {'class': ['greeting', 'css'], 'id': 'text', 'title': 'greeting'}
el의 title속성: greeting
el의 이름:  h1

In [26]:
#soup.select('선택자') : 해당 선택자 모든 앨리먼트를 리스트로
el = soup.select('h1')
print('리스트el : ', el)
print('el의 text들: ',[e.text for e in el])
print('el의 속성들: ', [e.attrs for e in el])
print('el의 class속성들 : ',[e.attrs.get('class') for e in el])

리스트el :  [<h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>]
el의 text들:  ['Hello, CSS', 'Hi, CSS']
el의 속성들:  [{'class': ['greeting', 'css'], 'id': 'text', 'title': 'greeting'}, {'class': ['css']}]
el의 class속성들 :  [['greeting', 'css'], ['css']]

In [32]:
#select_one(선택자)와 find(태그, 속성)
print('select_one: ', soup.select_one('h1.css'))
print('find: ', soup.find('h1', {'class':'css'}))
print('find: ', soup.find('h1', title='greeting'))
print()
print('select_one: ', soup.select_one('h1#text'))
print('find: ', soup.find('h1', {'id':'text'}))
print()
print('select')

select_one:  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>
find:  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>
find:  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>

select_one:  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>
find:  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>

select

In [34]:
#select(선택)와 find_all(태그, 속성)
print('모든 h1.css, span태그(select): ',
     soup.select('h1.css, span'))
print('모든 h1.css, span태그(find_all): ', 
     soup.find_all(['h1', 'span'], class_='css'))

모든 h1.css, span태그(select):  [<h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>, <span>다른<b>요소가 반환</b></span>]
모든 h1.css, span태그(find_all):  [<h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>]

In [40]:
#없는 엘리먼트 찾기
print('find_all(빈list): ', soup.find_all('a', class_='css'))
print('find(None): ', soup.find('a'))
print('select(빈list): ', soup.select('a.css'))
print('select_one(None): ', soup.select_one('a.css'))

find_all(빈list):  []
find(None):  None
select(빈list):  []
select_one(None):  None

# 2절. 정적 웹 데이터 수집(정적 웹크롤링)
- json, html, xml
## 2.1JSON파일
- request모듈(get)
- urllib.request모듈(urlopen)

In [41]:
#크롤링 허용 범위는 사이트마다 ~/roobts.txt에서 확인할 수 있습니다

In [83]:
#방법1
import requests
response = requests.get('http://api.github.com')
response, response.status_code

(<Response [403]>, 403)

In [43]:
#방법2
from urllib.request import urlopen
response = urlopen(http://api.github.com)
response

In [81]:
text = '{"속성1":"값1", "속성2":"값2"}'
type(text)

str

In [82]:
#문자(딕셔너리 타입)를 딕셔너리
#'{"속성1":"값1", "속성2":"값2"}' => {"속성1":"값1", "속성2":"값2"}
import json
json.loads(text)

{'속성1': '값1', '속성2': '값2'}

## 2.2 html파일
### 1)환율정보 가져오기(네이버->증권->시장지표)
- https://finance.naver.com/marketindex/

In [48]:
#방법1
import requests
from bs4 import BeautifulSoup
url = 'https://finance.naver.com/marketindex/'
response = requests.get(url)
#response, response.status_code
#response.content(바이너리)
#response.content.decode('cp949')
#response.text
soup = BeautifulSoup(response.text,
                    'html.parser')

In [53]:
#방법2
from urllib.request import urlopen
response = urlopen(url)
#response.status 상태코드
#response.read()
#response.read().decode('cp949')
soup = BeautifulSoup(response, #response.read()
                     'html.parser')

In [56]:
title = soup.select('h3.h_lst > span.blind')
[t.text for t in title]

['미국 USD',
 '일본 JPY(100엔)',
 '유럽연합 EUR',
 '중국 CNY',
 '달러/일본 엔',
 '유로/달러',
 '영국 파운드/달러',
 '달러인덱스',
 'WTI',
 '휘발유',
 '국제 금',
 '국내 금']

In [75]:
price = soup.select('div.head_info > span.value')
[round(float(p.text.replace(',',''))) for p in price]
[round(float(''.join(p.text.split(',')))) for p in price]

[1375, 953, 1556, 191, 144, 1, 1, 99, 61, 1633, 3300, 146218]

In [61]:
out = '1,374.70'
round(float(''.join(out.split(','))))

1375

In [63]:
round(float(out.replace(',','')))

1375

In [70]:
unit = soup.select('div.head_info > span > span.blind')
unit = [u.text for u in unit]
unit.insert(7,'')
unit

['원', '원', '원', '원', '엔', '달러', '달러', '', '달러', '원', '달러', '원']

In [71]:
status = soup.select('div.head_info > span.blind')
[t.text for t in title]
[p.text for p in price]
unit
[s.string for s in status]

['하락', '하락', '하락', '하락', '상승', '하락', '하락', '상승', '하락', '하락', '하락', '상승']

In [72]:
len(title), len(price), len(unit), len(status)

(12, 12, 12, 12)

In [76]:
for idx in range(len(title)):
    print("{}. {} : {}{} - {}".format(idx,
                                title[idx].text,
                                 price[idx].text,
                                 unit[idx],
                                 status[idx].text))

0. 미국 USD : 1,375.20원 - 하락
1. 일본 JPY(100엔) : 953.05원 - 하락
2. 유럽연합 EUR : 1,556.38원 - 하락
3. 중국 CNY : 191.04원 - 하락
4. 달러/일본 엔 : 144.3800엔 - 상승
5. 유로/달러 : 1.1342달러 - 하락
6. 영국 파운드/달러 : 1.3520달러 - 하락
7. 달러인덱스 : 99.4200 - 상승
8. WTI : 60.89달러 - 하락
9. 휘발유 : 1633.17원 - 하락
10. 국제 금 : 3300.4달러 - 하락
11. 국내 금 : 146218.18원 - 상승

In [79]:
for idx, (t, p, u, s) in enumerate(zip(title, price, unit, status)):
    print("{}. {}:{}{} - {}".format(idx+1,
                                t.text,
                               p.text,
                               u,
                               s.text))

1. 미국 USD:1,375.20원 - 하락
2. 일본 JPY(100엔):953.05원 - 하락
3. 유럽연합 EUR:1,556.38원 - 하락
4. 중국 CNY:191.04원 - 하락
5. 달러/일본 엔:144.3800엔 - 상승
6. 유로/달러:1.1342달러 - 하락
7. 영국 파운드/달러:1.3520달러 - 하락
8. 달러인덱스:99.4200 - 상승
9. WTI:60.89달러 - 하락
10. 휘발유:1633.17원 - 하락
11. 국제 금:3300.4달러 - 하락
12. 국내 금:146218.18원 - 상승

### 2) 이번주 로또번호 출력
- https://dhlottery.co.kr/gameResult.do?method=byWin google에 "로또번호 당첨번호"검색
```
1173회(2025년 05월 24일 추첨)
당첨번호 [1 5 18 20 30 35]
보너스3
```

In [84]:
# 방법1
import requests
from bs4 import BeautifulSoup
url = 'https://dhlottery.co.kr/gameResult.do?method=byWin'
response = requests.get(url)
soup = BeautifulSoup(response.text, #response.content
                    'html.parser')
soup

<!DOCTYPE html>

<html lang="ko">
<head>
<meta charset="utf-8"/>
<meta content="동행복권" id="utitle" name="title"/>
<meta content="동행복권 1173회 당첨번호 1,5,18,20,30,35+3. 1등 총 24명, 1인당 당첨금액 1,179,946,063원." id="desc" name="description"/>
<title>로또6/45 - 회차별 당첨번호</title>
<title>동행복권</title>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<link href="/images/common/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<link href="/images/common/favicon.ico" rel="icon" type="image/x-icon"/>
<script src="/js/jquery-1.9.1.min.js" type="text/javascript"></script>
<script src="/js/jquery-ui.js" type="text/javascript"></script>
<script charset="utf-8" src="/js/common.js" type="text/javascript"></script>
<script type="text/javascript">

fn_g_init_message("");

var gameUserId = "";

function goGame(){
	var userId = "";

	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login";
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert('접속이 원활하지 않습니다.');
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp("");
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function goGame(lottoId,agreeType){
	var userId = "";
	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + lottoId);
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp(lottoId,agreeType);
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function goGamePnInfo(lottoId,agreeType,svcInfoPnPcMsgYn){
	var svcInfoPnPcMsgYn = svcInfoPnPcMsgYn;

	if (svcInfoPnPcMsgYn == "Y") {
		svcInfoPnMsg();
		return;
	}

	var userId = "";
	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + lottoId);
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",  	// url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp(lottoId,agreeType);
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function goGameElInfo(lottoId,agreeType,svcInfoElPcMsgYn){
	var lottoId = lottoId;
	var svcInfoElPcMsgYn = svcInfoElPcMsgYn;

	// 2024 연마감 관련 코드
	if (svcInfoElPcMsgYn == "Y") {
		if (lottoId == "LI21") {	//20241226 sicc_kic 2024년도 트리플럭 판매종료.
			svcInfoElTrMsg();
			return;
		}
		else if (lottoId == "LI22") {  //20241125 sicc_kic 2024년도 트레져헌터 판매종료.
			svcInfoElThMsg();
			return;
		}
		else if (lottoId == "LI23") {  //20241226 sicc_kic 2024년도 캐치미 판매종료.
			svcInfoElCmMsg();
			return;
		}
		else if (lottoId == "LD10") {  //20241125 sicc_kjh 2024년도 스피드키노 판매종료.
		    svcInfoElSkMsg();
			return;
		}
		else if (lottoId == "LD11") {  //20241112 sicc_khj 2024년도 메가빙고 판매종료.
			svcInfoElMbMsg();
			return;
		}
		else if (lottoId == "LD14") {  //20241125 sicc_kic 2024년도 파워볼 판매종료.
			svcInfoElPbMsg();
			return;
		}
		else if (lottoId == "LD20") {  //20241226 sicc_kic 2024년도 더블잭  판매종료.
			svcInfoElDmMsg();
			return;
		}
		else {
			svcInfoElMsg();
			return;
		}
	}

	var userId = "";
	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + lottoId);
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",  	// url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp(lottoId,agreeType);
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function goGameEnInfo(lottoId,agreeType,endInfoElPcMsgYn){
	var endInfoElPcMsgYn = endInfoElPcMsgYn;

	if (endInfoElPcMsgYn == "Y") {
		endInfoElMsg();
		return;
	}

	var userId = "";
	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + lottoId);
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",  	// url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp(lottoId,agreeType);
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function goGameElEnInfo(lottoId,agreeType,svcInfoElPcMsgYn,endInfoElPcMsgYn){
	var svcInfoElPcMsgYn = svcInfoElPcMsgYn;
	var endInfoElPcMsgYn = endInfoElPcMsgYn;

	//2023연마감 관련 코드 (캐치미,트래져헌터 조기종료로 추가된코드.)
	if("N" == "Y"){
		if(lottoId == "LI23" || lottoId == "LI22" ) {
			//LI23: 캐치미,  LI22트레져헌터
			svcInfoElMsgEx();
			return;
		}
	}

	if (svcInfoElPcMsgYn == "Y") {
			svcInfoElMsg();
			return;
	}

	if (endInfoElPcMsgYn == "Y") {
		endInfoElMsg();
		return;
	}

	var userId = "";
	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + lottoId);
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",  	// url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp(lottoId,agreeType);
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function doGamePopUp(lotid,agreeType){
	/*
	* 스피드키노 LD10, 메가빙고 LD11, 더블잭마이더스 LD20, 파워볼 LD14, 트레져헌터 LI22, 트리플럭 LI21 -> gamePop
	* 캐치미 LI23 -> catchPop
	*/
	var type;

	if( lotid === 'LI23' ){
		type = 'catchPop';
	}else{
		type = 'gamePop';
	}

	if($("#agreeChk").is(":checked") || agreeType == 2){
		var new_popup = centerPop('https://el.dhlottery.co.kr/game/TotalGame.jsp?LottoId='+ lotid, 'type', 1164, 645, 'no');
	}else{
		alert('약관에 동의해 주셔야 이용이 가능합니다.');
		$("#agreeChk").focus();
	}

}

//설문조사 팝업
function popCenter(url){
	var new_popup =	centerPop(url, '설문조사', 480, 800, 'yes');
}

//샘플게임 팝업
function sample_pop(code, userId){

	//location.href = "/gamezone.do?method=gameZoneMainView";
	//return;
	if(userId == null || userId == ""){
		alert("로그인 후 이용이 가능합니다.");
		//location.href = "/user.do?method=login";
		//location.href = "/user.do?method=login&returnUrl=/gamezone.do?method=gameZoneMainView";
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + code);
		return;
	}
	if(!$("#sampleAgreeChk").is(":checked")){
		alert('약관에 동의해 주셔야 이용이 가능합니다.');
		$("#sampleAgreeChk").focus();
		return;
	}

	$.ajax({
		type:"POST",                            // 메소드타입
		url:"/gamezone.do?method=autoAgreeProc",// url
		dataType:"json",                        // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		async:false,
		contentType : "application/json; charset=EUC-KR",
		error: function() {                     // 에러날경우 콜백함수
			console.log("error");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(data.successYn){
				console.log(data);
			}
		}
	});

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		//data:{"jackpot":strJackpotData},   	// 파라메터 타입
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(userId == data.userId && data.userId != ""){
				var new_popup =	centerPop('https://el.dhlottery.co.kr/game_sample/TotalGame.jsp?LottoId=' + code, 'gamePop', 1164, 645, 'no');
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

//샘플게임(랜덤) 팝업
function sample_random_pop(userId){

	//location.href = "/gamezone.do?method=gameZoneMainView";
	//return;
	if(userId == null || userId == ""){
		alert("로그인 후 이용이 가능합니다.");
		location.href = "/user.do?method=login";
// 		location.href = "/user.do?method=login&returnUrl=/gamezone.do?method=gameZoneMainView";
// 		location.href = "/common.do?method=main";
		return;
	}

	var x = Math.floor((Math.random() * 7) + 1 );

	if(x == 1){
		var code = "LD14";
	}else if(x == 2){
		var code = "LD10";
	}else if(x == 3){
		var code = "LD20";
	}else if(x == 4){
		var code = "LI23";
	}else if(x == 5){
		var code = "LI22";
	}else if(x == 6){
		var code = "LI21";
	}else if(x == 7){
		var code = "LD11";
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"/gamezone.do?method=autoAgreeProc",// url
		dataType:"json",                        // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		async:false,
		contentType : "application/json; charset=EUC-KR",
		error: function() {                     // 에러날경우 콜백함수
			console.log("error");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(data.successYn){
				console.log(data);
			}
		}
	});

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		//data:{"jackpot":strJackpotData},   	// 파라메터 타입
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(userId == data.userId && data.userId != ""){
				var new_popup =	centerPop('https://el.dhlottery.co.kr/game_sample/TotalGame.jsp?LottoId=' + code , 'gamePop', 1164, 645, 'no');
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}



function doReserve(){
	var userId = "";

	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		//location.href = "/user.do?method=login";
		location.href = "/user.do?method=login&returnUrl=/gameInfo.do?method=game720Method";
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(userId == data.userId && data.userId != ""){
					window.open('https://el.dhlottery.co.kr/lotto720.do?method=reserveBuy', 'pensionPop' , 'width=930, height=672, left=0, top=0, status=no, toolbar=no, menubar=no, location=no');
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});

}


function jackpotViewPop(){
	var url = "/gameInfo.do?method=jackpotView&lottoId=";
	commonPop("", url, 820, 700, 'yes');
}

function goLottoBuy(agreeType){
	var userId = "";

	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		//location.href = "/user.do?method=login";
		location.href = "/user.do?method=login&returnUrl=/gameInfo.do?method=buyLotto";
		return;
	}
	if(agreeType == 1 && !$("#agreeChk").is(":checked")){
		alert('약관에 동의해 주셔야 이용이 가능합니다.');
		$("#agreeChk").focus();
		return;
	}


	 $.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(userId == data.userId && data.userId != ""){
				var new_popup = centerPop('https://el.dhlottery.co.kr/game/TotalGame.jsp?LottoId=LO40', 'gamePop', 1164, 645, 'no');
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});

}

function loginType(pageCode){
	var userId = "";
	var pageCodes = pageCode.split("-");
}

//엔터만 치면 로그인
function enter_check_top(eventValue) {
	if (eventValue == 13) {
		check_if_Valid_top();
		return;
	}
}

function depositAlert(){
	alert("12월 2일 이후부터 사용 가능합니다.");
}

function check_if_Valid_top() {
	var f = document.frmLogin;

	if (f.userId.value == "") {
		alert("아이디를 입력해 주십시오");
		f.userId.focus();
		return;
	}
	if (f.password.value == "") {
		alert("비밀번호를 입력해 주세요");
		f.password.focus();
		return;
	}
	if (f.userId.value.length >= 15) {
		alert("아이디가 자릿수가 초과되었습니다.");
		return;
	}
	if (f.password.value.length >= 101) {
		alert("비밀번호가 자릿수가 초과되었습니다.");
		return;
	}
	loginpage_top();
}

function loginpage_top(){

	var f = window.document.frmLogin;
	var pageUrl = document.location.href;
	var returnUrl="";

	f.method = "post";
	//f.target = "jform";
	if(returnUrl != ''){
		f.action = "https://www.dhlottery.co.kr/userSsl.do?method=login&returnUrl="+encodeURIComponent(returnUrl);
	}else{
		f.action = "https://www.dhlottery.co.kr/userSsl.do?method=login&returnUrl="+encodeURIComponent(pageUrl);
	}
	f.submit();

}

function getCookie(uName) {
	var flag = document.cookie.indexOf(uName + '=');
	if (flag != -1) {
		flag += uName.length + 1;
		end = document.cookie.indexOf(';', flag);
		if (end == -1)
			end = document.cookie.length;
		return unescape(document.cookie.substring(flag, end));
	}
}

function gomain() {
	location.href="/common.do?method=main";
}

$(document).ready(function() {
	$("#phoneTopMenu").html("");

	if(getCookie("userId") != undefined)
	{
		$('.top_userid').val(getCookie("userId"));
	}

});

function svcInfoPnMsg() {
	alert("일시 판매정지 중입니다.\n\n정지 일시 : 2024년 12월 31일 10시\n재개 일시 : 2025년 01월 02일");
}


function svcInfoElMsg() {
	alert("일시 판매정지 중입니다.\n\n정지 일시 : 2023년 12월 31일 09시\n재개 일시 : 2024년 01월 02일 10시");
}

//연마감용 메시지
function svcInfoElMsgEx() {
	alert("일시 판매정지 중입니다.\n\n정지 일시 : 2023년 12월 05일 00시\n재개 일시 : 2024년 01월 02일 10시");
}

//20241112 sicc_khj 2024년도 메가빙고 판매종료.
function svcInfoElMbMsg() {
	alert("메가빙고 복권은 판매종료 합니다.\n\n판매종료 일시 : 2024년 11월 13일 00시 \n판매재개 일시 : 2025년 01월 02일 ");
}

// 20241125 sicc_kic 2024년도 파워볼 판매종료.
function svcInfoElPbMsg() {
	alert("파워볼 복권은 판매종료 합니다.\n\n판매종료 일시 : 2024년 12월 16일 00시 \n판매재개 일시 : 2025년 01월 02일");
}
//20241212 sicc_kic 2024년도 트레져헌터 판매종료.
function svcInfoElThMsg() {
	alert("트레져헌터 복권은 판매종료 합니다.\n\n판매종료 일시 : 2024년 12월 23일 00시 \n판매재개 일시 : 2025년 01월 02일");
}

//20241217 sicc_kjh 2024년도 스피드키노 판매종료.
function svcInfoElSkMsg() {
	alert("스피드키노 복권은 판매종료 합니다.\n\n판매종료 일시 : 2024년 12월 23일 00시 \n판매재개 일시 : 2025년 01월 02일");
}

//20241226 sicc_kic 2024년도 트리플럭 판매종료.
//--25회차 수정
function svcInfoElTrMsg() {
	alert("트리플럭 복권은 판매 정지 중입니다.\n\n정지일시 : 2024년 12월 31일 10시 \n재개 일시 : 2025년 01월 02일");
}

//20241226 sicc_kic 2024년도 더블잭 판매종료.
function svcInfoElDmMsg() {
	alert("더블잭 마이더스 복권은 판매 정지 중입니다.\n\n정지일시 : 2024년 12월 31일 10시 \n재개 일시 : 2025년 01월 02일 ");
}

//20241226 sicc_kic 2024년도 캐치미 판매종료.
function svcInfoElCmMsg() {
	alert("캐치미 복권은 판매 정지 중입니다.\n\n정지일시 : 2024년 12월 31일 10시 \n재개 일시 : 2025년 01월 02일 ");
}
function endInfoElMsg() {
	alert("판매시간이 아닙니다.\n\n판매 시간 : 06시 ~ 24시");
}

</script>
<!-- <link rel="stylesheet" type="text/css" href="/css/nanum_gothic_dev.css" /> -->
<link href="/css/styles.css" rel="stylesheet" type="text/css"/>
<script charset="utf-8" src="/js/function.js" type="text/javascript"></script>
<script charset="utf-8" src="/js/InsertFlash.js" type="text/javascript"></script>
<script charset="utf-8" src="/js/link.js" type="text/javascript"></script>
<script charset="utf-8" src="/js/makePCookie.js" type="text/javascript"></script>
<script src="/js/jquery.cookie.js" type="text/javascript"></script>
<script src="/js/webfont.js" type="text/javascript"></script>
<script>
if (navigator.platform && /win16|win32|win64|mac/ig.test(navigator.platform) == false) {
	if ('https://m.dhlottery.co.kr'.indexOf(location.hostname) == -1 || 'https://m.dhlottery.co.kr'.indexOf(location.hostname) == -1 ) {
	  	location.href = 'https://m.dhlottery.co.kr';
	}
}
</script>
<script>
var pageCode = "03-01-01";
var pageName = "회차별 당첨번호";

var hdrw = 1;
function search() {
	$('#drwNo').val($("#dwrNoList").val());
	$("#frm").attr({action:"/gameResult.do?method=byWin", method:"post"}).submit();
}

$(document).ready(function() {

	if("1173" != ""){
		$("#dwrNoList").val("1173");
		if ("1173" < 601) hdrw = 2;
	}
	$('#searchBtn').click(function(e) {
		search();
	});
	$('#printBtn').click(function(e) {
		e.preventDefault();
		commonPop("stat_pop", "/gameResult.do?method=allWinPrint&gubun=byWin&nowPage="+$("#nowPage").val()+"&drwNoStart="+$("#drwNoStart").val()+"&drwNoEnd="+$("#drwNoEnd").val(), "800", "750", "");
	});
	$('#exelBtn').click(function(e) {
		var search1 = $("#drwNoStart").val();
		var search2 = $("#drwNoEnd").val();
		if(parseInt(search2) < parseInt(search1)){
			alert("시작회차가 종료회차보다 큽니다.");
			$('#drwNoEnd').focus();
			return false;
		};
		location.href = "/gameResult.do?method=allWinExel&gubun=byWin&nowPage="+$("#nowPage").val()+"&drwNoStart="+$("#drwNoStart").val()+"&drwNoEnd="+$("#drwNoEnd").val();
	});
	$('#hdrwComb').click(function(e) {
		if($('#hdrwComb').val() != hdrw) {
			hdrw = $('#hdrwComb').val();
			$("#dwrNoList").empty();
			$("#drwNoStart").empty();
			$("#drwNoEnd").empty();
			var str = "";

			if(hdrw == 1) {

In [85]:
#방법2
from urllib.request import urlopen
url = 'https://dhlottery.co.kr/gameResult.do?method=byWin'
response= urlopen(url)
soup = BeautifulSoup(response,
                    'html.parser')
soup

<!DOCTYPE html>

<html lang="ko">
<head>
<meta charset="utf-8"/>
<meta content="동행복권" id="utitle" name="title"/>
<meta content="동행복권 1173회 당첨번호 1,5,18,20,30,35+3. 1등 총 24명, 1인당 당첨금액 1,179,946,063원." id="desc" name="description"/>
<title>로또6/45 - 회차별 당첨번호</title>
<title>동행복권</title>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<link href="/images/common/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<link href="/images/common/favicon.ico" rel="icon" type="image/x-icon"/>
<script src="/js/jquery-1.9.1.min.js" type="text/javascript"></script>
<script src="/js/jquery-ui.js" type="text/javascript"></script>
<script charset="utf-8" src="/js/common.js" type="text/javascript"></script>
<script type="text/javascript">

fn_g_init_message("");

var gameUserId = "";

function goGame(){
	var userId = "";

	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login";
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert('접속이 원활하지 않습니다.');
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp("");
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function goGame(lottoId,agreeType){
	var userId = "";
	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + lottoId);
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp(lottoId,agreeType);
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function goGamePnInfo(lottoId,agreeType,svcInfoPnPcMsgYn){
	var svcInfoPnPcMsgYn = svcInfoPnPcMsgYn;

	if (svcInfoPnPcMsgYn == "Y") {
		svcInfoPnMsg();
		return;
	}

	var userId = "";
	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + lottoId);
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",  	// url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp(lottoId,agreeType);
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function goGameElInfo(lottoId,agreeType,svcInfoElPcMsgYn){
	var lottoId = lottoId;
	var svcInfoElPcMsgYn = svcInfoElPcMsgYn;

	// 2024 연마감 관련 코드
	if (svcInfoElPcMsgYn == "Y") {
		if (lottoId == "LI21") {	//20241226 sicc_kic 2024년도 트리플럭 판매종료.
			svcInfoElTrMsg();
			return;
		}
		else if (lottoId == "LI22") {  //20241125 sicc_kic 2024년도 트레져헌터 판매종료.
			svcInfoElThMsg();
			return;
		}
		else if (lottoId == "LI23") {  //20241226 sicc_kic 2024년도 캐치미 판매종료.
			svcInfoElCmMsg();
			return;
		}
		else if (lottoId == "LD10") {  //20241125 sicc_kjh 2024년도 스피드키노 판매종료.
		    svcInfoElSkMsg();
			return;
		}
		else if (lottoId == "LD11") {  //20241112 sicc_khj 2024년도 메가빙고 판매종료.
			svcInfoElMbMsg();
			return;
		}
		else if (lottoId == "LD14") {  //20241125 sicc_kic 2024년도 파워볼 판매종료.
			svcInfoElPbMsg();
			return;
		}
		else if (lottoId == "LD20") {  //20241226 sicc_kic 2024년도 더블잭  판매종료.
			svcInfoElDmMsg();
			return;
		}
		else {
			svcInfoElMsg();
			return;
		}
	}

	var userId = "";
	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + lottoId);
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",  	// url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp(lottoId,agreeType);
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function goGameEnInfo(lottoId,agreeType,endInfoElPcMsgYn){
	var endInfoElPcMsgYn = endInfoElPcMsgYn;

	if (endInfoElPcMsgYn == "Y") {
		endInfoElMsg();
		return;
	}

	var userId = "";
	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + lottoId);
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",  	// url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp(lottoId,agreeType);
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function goGameElEnInfo(lottoId,agreeType,svcInfoElPcMsgYn,endInfoElPcMsgYn){
	var svcInfoElPcMsgYn = svcInfoElPcMsgYn;
	var endInfoElPcMsgYn = endInfoElPcMsgYn;

	//2023연마감 관련 코드 (캐치미,트래져헌터 조기종료로 추가된코드.)
	if("N" == "Y"){
		if(lottoId == "LI23" || lottoId == "LI22" ) {
			//LI23: 캐치미,  LI22트레져헌터
			svcInfoElMsgEx();
			return;
		}
	}

	if (svcInfoElPcMsgYn == "Y") {
			svcInfoElMsg();
			return;
	}

	if (endInfoElPcMsgYn == "Y") {
		endInfoElMsg();
		return;
	}

	var userId = "";
	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + lottoId);
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",  	// url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp(lottoId,agreeType);
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function doGamePopUp(lotid,agreeType){
	/*
	* 스피드키노 LD10, 메가빙고 LD11, 더블잭마이더스 LD20, 파워볼 LD14, 트레져헌터 LI22, 트리플럭 LI21 -> gamePop
	* 캐치미 LI23 -> catchPop
	*/
	var type;

	if( lotid === 'LI23' ){
		type = 'catchPop';
	}else{
		type = 'gamePop';
	}

	if($("#agreeChk").is(":checked") || agreeType == 2){
		var new_popup = centerPop('https://el.dhlottery.co.kr/game/TotalGame.jsp?LottoId='+ lotid, 'type', 1164, 645, 'no');
	}else{
		alert('약관에 동의해 주셔야 이용이 가능합니다.');
		$("#agreeChk").focus();
	}

}

//설문조사 팝업
function popCenter(url){
	var new_popup =	centerPop(url, '설문조사', 480, 800, 'yes');
}

//샘플게임 팝업
function sample_pop(code, userId){

	//location.href = "/gamezone.do?method=gameZoneMainView";
	//return;
	if(userId == null || userId == ""){
		alert("로그인 후 이용이 가능합니다.");
		//location.href = "/user.do?method=login";
		//location.href = "/user.do?method=login&returnUrl=/gamezone.do?method=gameZoneMainView";
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + code);
		return;
	}
	if(!$("#sampleAgreeChk").is(":checked")){
		alert('약관에 동의해 주셔야 이용이 가능합니다.');
		$("#sampleAgreeChk").focus();
		return;
	}

	$.ajax({
		type:"POST",                            // 메소드타입
		url:"/gamezone.do?method=autoAgreeProc",// url
		dataType:"json",                        // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		async:false,
		contentType : "application/json; charset=EUC-KR",
		error: function() {                     // 에러날경우 콜백함수
			console.log("error");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(data.successYn){
				console.log(data);
			}
		}
	});

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		//data:{"jackpot":strJackpotData},   	// 파라메터 타입
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(userId == data.userId && data.userId != ""){
				var new_popup =	centerPop('https://el.dhlottery.co.kr/game_sample/TotalGame.jsp?LottoId=' + code, 'gamePop', 1164, 645, 'no');
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

//샘플게임(랜덤) 팝업
function sample_random_pop(userId){

	//location.href = "/gamezone.do?method=gameZoneMainView";
	//return;
	if(userId == null || userId == ""){
		alert("로그인 후 이용이 가능합니다.");
		location.href = "/user.do?method=login";
// 		location.href = "/user.do?method=login&returnUrl=/gamezone.do?method=gameZoneMainView";
// 		location.href = "/common.do?method=main";
		return;
	}

	var x = Math.floor((Math.random() * 7) + 1 );

	if(x == 1){
		var code = "LD14";
	}else if(x == 2){
		var code = "LD10";
	}else if(x == 3){
		var code = "LD20";
	}else if(x == 4){
		var code = "LI23";
	}else if(x == 5){
		var code = "LI22";
	}else if(x == 6){
		var code = "LI21";
	}else if(x == 7){
		var code = "LD11";
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"/gamezone.do?method=autoAgreeProc",// url
		dataType:"json",                        // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		async:false,
		contentType : "application/json; charset=EUC-KR",
		error: function() {                     // 에러날경우 콜백함수
			console.log("error");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(data.successYn){
				console.log(data);
			}
		}
	});

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		//data:{"jackpot":strJackpotData},   	// 파라메터 타입
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(userId == data.userId && data.userId != ""){
				var new_popup =	centerPop('https://el.dhlottery.co.kr/game_sample/TotalGame.jsp?LottoId=' + code , 'gamePop', 1164, 645, 'no');
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}



function doReserve(){
	var userId = "";

	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		//location.href = "/user.do?method=login";
		location.href = "/user.do?method=login&returnUrl=/gameInfo.do?method=game720Method";
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(userId == data.userId && data.userId != ""){
					window.open('https://el.dhlottery.co.kr/lotto720.do?method=reserveBuy', 'pensionPop' , 'width=930, height=672, left=0, top=0, status=no, toolbar=no, menubar=no, location=no');
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});

}


function jackpotViewPop(){
	var url = "/gameInfo.do?method=jackpotView&lottoId=";
	commonPop("", url, 820, 700, 'yes');
}

function goLottoBuy(agreeType){
	var userId = "";

	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		//location.href = "/user.do?method=login";
		location.href = "/user.do?method=login&returnUrl=/gameInfo.do?method=buyLotto";
		return;
	}
	if(agreeType == 1 && !$("#agreeChk").is(":checked")){
		alert('약관에 동의해 주셔야 이용이 가능합니다.');
		$("#agreeChk").focus();
		return;
	}


	 $.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(userId == data.userId && data.userId != ""){
				var new_popup = centerPop('https://el.dhlottery.co.kr/game/TotalGame.jsp?LottoId=LO40', 'gamePop', 1164, 645, 'no');
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});

}

function loginType(pageCode){
	var userId = "";
	var pageCodes = pageCode.split("-");
}

//엔터만 치면 로그인
function enter_check_top(eventValue) {
	if (eventValue == 13) {
		check_if_Valid_top();
		return;
	}
}

function depositAlert(){
	alert("12월 2일 이후부터 사용 가능합니다.");
}

function check_if_Valid_top() {
	var f = document.frmLogin;

	if (f.userId.value == "") {
		alert("아이디를 입력해 주십시오");
		f.userId.focus();
		return;
	}
	if (f.password.value == "") {
		alert("비밀번호를 입력해 주세요");
		f.password.focus();
		return;
	}
	if (f.userId.value.length >= 15) {
		alert("아이디가 자릿수가 초과되었습니다.");
		return;
	}
	if (f.password.value.length >= 101) {
		alert("비밀번호가 자릿수가 초과되었습니다.");
		return;
	}
	loginpage_top();
}

function loginpage_top(){

	var f = window.document.frmLogin;
	var pageUrl = document.location.href;
	var returnUrl="";

	f.method = "post";
	//f.target = "jform";
	if(returnUrl != ''){
		f.action = "https://www.dhlottery.co.kr/userSsl.do?method=login&returnUrl="+encodeURIComponent(returnUrl);
	}else{
		f.action = "https://www.dhlottery.co.kr/userSsl.do?method=login&returnUrl="+encodeURIComponent(pageUrl);
	}
	f.submit();

}

function getCookie(uName) {
	var flag = document.cookie.indexOf(uName + '=');
	if (flag != -1) {
		flag += uName.length + 1;
		end = document.cookie.indexOf(';', flag);
		if (end == -1)
			end = document.cookie.length;
		return unescape(document.cookie.substring(flag, end));
	}
}

function gomain() {
	location.href="/common.do?method=main";
}

$(document).ready(function() {
	$("#phoneTopMenu").html("");

	if(getCookie("userId") != undefined)
	{
		$('.top_userid').val(getCookie("userId"));
	}

});

function svcInfoPnMsg() {
	alert("일시 판매정지 중입니다.\n\n정지 일시 : 2024년 12월 31일 10시\n재개 일시 : 2025년 01월 02일");
}


function svcInfoElMsg() {
	alert("일시 판매정지 중입니다.\n\n정지 일시 : 2023년 12월 31일 09시\n재개 일시 : 2024년 01월 02일 10시");
}

//연마감용 메시지
function svcInfoElMsgEx() {
	alert("일시 판매정지 중입니다.\n\n정지 일시 : 2023년 12월 05일 00시\n재개 일시 : 2024년 01월 02일 10시");
}

//20241112 sicc_khj 2024년도 메가빙고 판매종료.
function svcInfoElMbMsg() {
	alert("메가빙고 복권은 판매종료 합니다.\n\n판매종료 일시 : 2024년 11월 13일 00시 \n판매재개 일시 : 2025년 01월 02일 ");
}

// 20241125 sicc_kic 2024년도 파워볼 판매종료.
function svcInfoElPbMsg() {
	alert("파워볼 복권은 판매종료 합니다.\n\n판매종료 일시 : 2024년 12월 16일 00시 \n판매재개 일시 : 2025년 01월 02일");
}
//20241212 sicc_kic 2024년도 트레져헌터 판매종료.
function svcInfoElThMsg() {
	alert("트레져헌터 복권은 판매종료 합니다.\n\n판매종료 일시 : 2024년 12월 23일 00시 \n판매재개 일시 : 2025년 01월 02일");
}

//20241217 sicc_kjh 2024년도 스피드키노 판매종료.
function svcInfoElSkMsg() {
	alert("스피드키노 복권은 판매종료 합니다.\n\n판매종료 일시 : 2024년 12월 23일 00시 \n판매재개 일시 : 2025년 01월 02일");
}

//20241226 sicc_kic 2024년도 트리플럭 판매종료.
//--25회차 수정
function svcInfoElTrMsg() {
	alert("트리플럭 복권은 판매 정지 중입니다.\n\n정지일시 : 2024년 12월 31일 10시 \n재개 일시 : 2025년 01월 02일");
}

//20241226 sicc_kic 2024년도 더블잭 판매종료.
function svcInfoElDmMsg() {
	alert("더블잭 마이더스 복권은 판매 정지 중입니다.\n\n정지일시 : 2024년 12월 31일 10시 \n재개 일시 : 2025년 01월 02일 ");
}

//20241226 sicc_kic 2024년도 캐치미 판매종료.
function svcInfoElCmMsg() {
	alert("캐치미 복권은 판매 정지 중입니다.\n\n정지일시 : 2024년 12월 31일 10시 \n재개 일시 : 2025년 01월 02일 ");
}
function endInfoElMsg() {
	alert("판매시간이 아닙니다.\n\n판매 시간 : 06시 ~ 24시");
}

</script>
<!-- <link rel="stylesheet" type="text/css" href="/css/nanum_gothic_dev.css" /> -->
<link href="/css/styles.css" rel="stylesheet" type="text/css"/>
<script charset="utf-8" src="/js/function.js" type="text/javascript"></script>
<script charset="utf-8" src="/js/InsertFlash.js" type="text/javascript"></script>
<script charset="utf-8" src="/js/link.js" type="text/javascript"></script>
<script charset="utf-8" src="/js/makePCookie.js" type="text/javascript"></script>
<script src="/js/jquery.cookie.js" type="text/javascript"></script>
<script src="/js/webfont.js" type="text/javascript"></script>
<script>
if (navigator.platform && /win16|win32|win64|mac/ig.test(navigator.platform) == false) {
	if ('https://m.dhlottery.co.kr'.indexOf(location.hostname) == -1 || 'https://m.dhlottery.co.kr'.indexOf(location.hostname) == -1 ) {
	  	location.href = 'https://m.dhlottery.co.kr';
	}
}
</script>
<script>
var pageCode = "03-01-01";
var pageName = "회차별 당첨번호";

var hdrw = 1;
function search() {
	$('#drwNo').val($("#dwrNoList").val());
	$("#frm").attr({action:"/gameResult.do?method=byWin", method:"post"}).submit();
}

$(document).ready(function() {

	if("1173" != ""){
		$("#dwrNoList").val("1173");
		if ("1173" < 601) hdrw = 2;
	}
	$('#searchBtn').click(function(e) {
		search();
	});
	$('#printBtn').click(function(e) {
		e.preventDefault();
		commonPop("stat_pop", "/gameResult.do?method=allWinPrint&gubun=byWin&nowPage="+$("#nowPage").val()+"&drwNoStart="+$("#drwNoStart").val()+"&drwNoEnd="+$("#drwNoEnd").val(), "800", "750", "");
	});
	$('#exelBtn').click(function(e) {
		var search1 = $("#drwNoStart").val();
		var search2 = $("#drwNoEnd").val();
		if(parseInt(search2) < parseInt(search1)){
			alert("시작회차가 종료회차보다 큽니다.");
			$('#drwNoEnd').focus();
			return false;
		};
		location.href = "/gameResult.do?method=allWinExel&gubun=byWin&nowPage="+$("#nowPage").val()+"&drwNoStart="+$("#drwNoStart").val()+"&drwNoEnd="+$("#drwNoEnd").val();
	});
	$('#hdrwComb').click(function(e) {
		if($('#hdrwComb').val() != hdrw) {
			hdrw = $('#hdrwComb').val();
			$("#dwrNoList").empty();
			$("#drwNoStart").empty();
			$("#drwNoEnd").empty();
			var str = "";

			if(hdrw == 1) {

In [89]:
times = soup.select_one('div.win_result > h4 > strong').text # 1173회
date = soup.select_one('div.win_result >p.desc').text  #(2025년 05월 24일 추첨)
print(times, date)
title1 = soup.select_one('div.num.win > strong').text
lotto_number = soup.select('div.num.win > p > span')
print(title1, [int(lotto.text) for lotto in lotto_number])
title2 = soup.select_one('div.num.bonus > strong').string
bonus_number = soup.select_one('div.num.bonus > p > span').text
print(title2, bonus_number)

1173회 (2025년 05월 24일 추첨)
당첨번호 [1, 5, 18, 20, 30, 35]
보너스 3

In [97]:
#위의 select함수를 find함수로

# times = soup.select_one('div.win_result > h4 > strong').text #1173회
win_result = soup.find('div', class_="win_result")
times = win_result.find('strong').text
# date = soup.select_one('div.win_result >p.desc').text  #(2025년 05월 24일 추첨)
date = soup.find('p', class_="desc").text
print(times,date)
# title1 = soup.select_one('div.num.win > strong').text
num_win = soup.find("div", class_=['num', 'win'])
title1 = num_win.find('strong').text
# lotto_number = soup.select('div.num.win > p > span')
lotto_number = num_win.find_all('span')#배열
print(title1, [int(lotto.text) for lotto in lotto_number])
# title2 = soup.select_one('div.num.bonus > strong').string
num_bonus = soup.find('div', class_=['bonus'])
title2 = num_bonus.find('strong').text
# bonus_number = soup.select_one('div.num.bonus > p > span').text
bonus_number = num_bonus.find('span').text
print(title2, bonus_number)

1173회 (2025년 05월 24일 추첨)
당첨번호 [1, 5, 18, 20, 30, 35]
보너스 3

### 3)다음 검색 리스트

```90
no title link
0 [비트코인 2025] 백악관 크립토 차르~ https://v.daum.net/v/20250528103907230
1 [비즈 나우] 비트코인 2025 컨퍼런~ https://v.daum.net/v/20250528075215864
```

In [113]:
# 방법1
import requests
from bs4 import BeautifulSoup
word = '비트코인'
url = 'https://search.daum.net/search?w=news&nil_search=btn&DA=NTB&enc=utf8&cluster=y&cluster_page=1&q='+word
response = requests.get(url)
soup = BeautifulSoup(response.text, # response.content
                    "html.parser")
items_find_list = [] # 검색한 결과를 담을 dict list
items_el = soup.select('div.item-title > strong.tit-g.clamp-g > a')
# len(items_el)
for idx, item in enumerate(items_el):
    items_find_list.append({'no': idx,
                           'title': item.text,
                           'link': item.attrs['href']})
import pandas as pd
pd.DataFrame(items_find_list)

,no,title,link
0,0,[비트코인 2025] 백악관 크립토 차르 “美 정부 비트코인 추가 매입 검토…부채...,http://v.daum.net/v/20250528103907230
1,1,[비즈 나우] 비트코인 2025 컨퍼런스 개막…'전략자산' 선언 코앞,http://v.daum.net/v/20250528075215864
2,2,“맥O날드보다 맛없어!” 혹평이 가득한 트럼프 만찬과 비트코인 피자데이[엠블록레터],http://v.daum.net/v/20250528143002735
3,3,"비트코인, 트럼프 미디어 비축 소식에도 주춤…1억5100만원대",http://v.daum.net/v/20250528095112897
4,4,"'비트코인 빚투' 스트레티지, 또 샀다…보유량 58만개 돌파",http://v.daum.net/v/20250528042404292
5,5,"美 상원의원 ""트럼프 대통령, 비트코인법 지지""",http://v.daum.net/v/20250528090342853
6,6,"숨 고르는 비트코인, 10만8000달러선 '주춤'",http://v.daum.net/v/20250528095921258
7,7,[비트코인 2025] 로빈후드 창업자 “토큰화 증권은 美 ‘자본 패권’ 키우는 수단”,http://v.daum.net/v/20250528110600761
8,8,"트럼프미디어그룹, 25억 달러 규모 자금 조달 통해 비트코인 매입 예고",http://v.daum.net/v/20250528084245020
9,9,연일 최고가 경신하는 비트코인…투자자들 강 건너 불구경하는 이유는,http://v.daum.net/v/20250526212400275

In [126]:
#다음 뉴스 검색(키워드, 원하는 페이지수)
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
def collect_list(keyword, page=1):
    'keyword로 다음 검색한 결과(해당 page)를 return'
    url = f'https://search.daum.net/search?w=news&nil_search=btn&DA=NTB&enc=utf8&cluster=y'
    params = {'q':keyword, 'p':page}
    response = requests.get(url, params=params)
    soup = BeautifulSoup(response.text, #response.content
                    'html.parser')
    items_find_list = [] # 검색한 결과를 담을 dict list
    items_el = soup.select('div.item-title > strong.tit-g.clamp-g > a')
    for idx, item in enumerate(items_el):
        items_find_list.append({'no': idx,
                           'title': item.text,
                           'link': item.attrs['href']})
    return items_find_list

In [127]:
collect_list('대선', 2)

[{'no': 0,
  'title': ' 부산 다시 찾은 김문수, ‘사전 투표’ 재차 독려 [21대 대선] ',
  'link': 'http://v.daum.net/v/20250528155306855'},
 {'no': 1,
  'title': " [살까팔까] '지배구조 개선' 대선 공약에…한화·효성 등 지주사株 '훨훨' ",
  'link': 'http://v.daum.net/v/20250528155002701'},
 {'no': 2,
  'title': ' [이재명 공약집] 금융사, 소액 금융분쟁 결정 바로 따라야 [대선 2025] ',
  'link': 'http://v.daum.net/v/20250528152126320'},
 {'no': 3,
  'title': ' 대선에 경찰 최대동원…서울 투표함 회송에 무장경찰 6400명 ',
  'link': 'http://v.daum.net/v/20250528154201339'},
 {'no': 4,
  'title': ' [대선공약] 코리아 디스카운트 넘는다…李 "주주권익 보호" vs 金 "세제 혜택" ',
  'link': 'http://v.daum.net/v/20250528153751194'},
 {'no': 5,
  'title': ' 이준석 발언 겨냥? 이재명 “대선, 혐오의 언어로 채워져” ',
  'link': 'http://v.daum.net/v/20250528144125273'},
 {'no': 6,
  'title': ' [대선공약] 李·金 모두 \'AI 인프라\' 방점…"구체적 실행 방안은 실종" ',
  'link': 'http://v.daum.net/v/20250528160128321'},
 {'no': 7,
  'title': ' “여성 유권자에게 사과”…이준석 유세 중 날아든 지적 [21대 대선] ',
  'link': 'http://v.daum.net/v/20250528142905688'},
 {'no': 8,
  'title': ' 대선토론 최악의 언어 성폭력…이준석 발언 ‘사후 제재’ 가능할까 ',
  'link': 'http://v.daum.net/v/20250528144503420'},
 {'no': 9,
  'title': " '대선 투표함 지켜라' 무장경찰 6400명 투입… 본투표땐 갑호비상 ",
  'link': 'http://v.daum.net/v/20250528154717586'}]

In [132]:
#원하는 keyword로 다음검색
result = []
keyword="청바지"
pages = 3
for page in range(1, pages+1):
    result.extend(collect_list(keyword, page))
    time.sleep(1)
result_df = pd.DataFrame(result)
result_df

Empty DataFrame
Columns: []
Index: []

In [141]:
keywords = ['청바지', '면바지']
pages=5
result0 = [] #청바지 검색결과 50개
result1 = [] #면바지 검색결과 50개
for i, keyword in enumerate(keywords):
    for page in range(1, pages+1):
        print(f'~~~~~~~~~{i}번째 {keyword} {page}검색 중입니다~~~~~~~~')
        if i==0:
            result0.extend(collect_list(keyword, page))
        else:
            result1.extend(collect_list(keyword, page))
        time.sleep(3)

~~~~~~~~~0번째 청바지 1검색 중입니다~~~~~~~~
~~~~~~~~~0번째 청바지 2검색 중입니다~~~~~~~~
~~~~~~~~~0번째 청바지 3검색 중입니다~~~~~~~~
~~~~~~~~~0번째 청바지 4검색 중입니다~~~~~~~~
~~~~~~~~~0번째 청바지 5검색 중입니다~~~~~~~~
~~~~~~~~~1번째 면바지 1검색 중입니다~~~~~~~~
~~~~~~~~~1번째 면바지 2검색 중입니다~~~~~~~~
~~~~~~~~~1번째 면바지 3검색 중입니다~~~~~~~~
~~~~~~~~~1번째 면바지 4검색 중입니다~~~~~~~~
~~~~~~~~~1번째 면바지 5검색 중입니다~~~~~~~~

In [142]:
result0_df = pd.DataFrame(result0)
result0_df.head()

,no,title,link
0,0,"'이병헌♥' 이민정, 매장 통째로 빌려 청바지 쇼핑",http://v.daum.net/v/20250528050507783
1,1,"“추앙받을 만 하네”… 김지원, 셔츠에 청바지만 입어도 공항 ‘정지’",http://v.daum.net/v/20250526182411395
2,2,흰 티셔츠에 청바지 정석대로 입는 법,http://v.daum.net/v/20250527185425864
3,3,"이민정, 매장 빌려 폭풍 쇼핑 ""10년 전 샀던 청바지는 응급실""(MJ)",http://v.daum.net/v/20250527191015309
4,4,"‘이병헌♥’ 이민정, 청바지 사는데 매장 통째로 빌렸다..남다른 쇼핑 클래스 “나...",http://v.daum.net/v/20250527192310643

In [143]:
result1_df = pd.DataFrame(result0)
result1_df.head()

,no,title,link
0,0,"'이병헌♥' 이민정, 매장 통째로 빌려 청바지 쇼핑",http://v.daum.net/v/20250528050507783
1,1,"“추앙받을 만 하네”… 김지원, 셔츠에 청바지만 입어도 공항 ‘정지’",http://v.daum.net/v/20250526182411395
2,2,흰 티셔츠에 청바지 정석대로 입는 법,http://v.daum.net/v/20250527185425864
3,3,"이민정, 매장 빌려 폭풍 쇼핑 ""10년 전 샀던 청바지는 응급실""(MJ)",http://v.daum.net/v/20250527191015309
4,4,"‘이병헌♥’ 이민정, 청바지 사는데 매장 통째로 빌렸다..남다른 쇼핑 클래스 “나...",http://v.daum.net/v/20250527192310643

In [147]:
result0_df.to_csv('data/ch14'+keywords[0]+'.csv',index=False, encoding='cp949')
result1_df.to_csv('data/ch14'+keywords[1]+'.csv',index=False)

### 4) Useragent를 추가하여 크롤링
- urlopen()함수를 사용하면 크롤링이 안 되는 사이트

In [145]:
#방법2
from urllib.request import urlopen, Request
import urllib.parse
word = '비트코인'
word = urllib.parse.quote(word)
#print(word)
url = 'https://search.daum.net/search?w=news&nil_search=btn&DA=NTB&enc=utf8&cluster=y&cluster_page=1&q='+word
#User-Agent를 추가하여 브라우저처럼 보이게 포장
headers = {'user-agent':
         'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36'}
request = Request(url, headers = headers)
response = urlopen(request)
soup = BeautifulSoup(response, # response.content
                    "html.parser")
soup

<!DOCTYPE html>

<html lang="ko" xmlns="http://www.w3.org/1999/xhtml">
<head profile="http://a9.com/-/spec/opensearch/1.1/">
<meta content="text/html;charset=utf-8" http-equiv="content-Type"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="off" name="autocomplete"/>
<meta content="always" name="referrer"/>
<meta content="telephone=no,address=no,email=no" name="format-detection">
<meta content="비트코인 – Daum 검색" property="og:title"/>
<meta content="https://search.daum.net/search?w=news&amp;nil_search=btn&amp;DA=NTB&amp;enc=utf8&amp;cluster=y&amp;cluster_page=1&amp;q=%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8" property="og:url"/>
<meta content="Daum 검색에서 비트코인에 대한 최신정보를 찾아보세요." property="og:description"/>
<meta content="https://search1.daumcdn.net/search/statics/common/img/20250107/daum_og.png" property="og:image"/>
<meta content="다음검색" property="og:site_name"/>
<link href="https://t1.daumcdn.net/top/favicon/20241223/daum.ico" rel="shortcut icon"/>
<link href="//sl.search.daum.net/" rel="preconnect"/>
<link href="//ssl.daumcdn.net/" rel="preconnect"/>
<link href="//t1.daumcdn.net/" rel="preconnect"/>
<link href="//wat.ad.daum.net/" rel="preconnect"/>
<link href="//track.tiara.daum.net/" rel="preconnect"/>
<link href="//webid.ad.daum.net/" rel="preconnect"/>
<link href="//webid.kakao.com/" rel="preconnect"/>
<title>비트코인 – Daum 검색</title>
<link href="//search.daum.net/OpenSearch.xml" rel="search" title="Daum" type="application/opensearchdescription+xml"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2025/p_common.0408023855.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2024/p_component.0610023548.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2025/pm_common.0512034956.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2025/q_comm.0407032624.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/js/fe/cubic/20250519130026/cubic.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2025/p_collection.0114125841.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2024/p_collection2.0923031103.css" rel="stylesheet" type="text/css"/>
<link charset="utf-8" href="//search1.daumcdn.net/search/statics/common/css/2024/p_newsColl.1105104334.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript">
var uk = "cf930c51-382a-463c-80ab-45e2c559410f";
var mk = "cf930c51-382a-463c-80ab-45e2c559410f";
var ksk = "cf930c51-382a-463c-80ab-45e2c559410f";
var ud = "";
var uuid = "";
var adid = "";
var adid_enabled = "N";
var viewio = "i";
var viewsite = "";
var ServerTime = "20250528165143";
var utf8Query = encodeURIComponent("비트코인");
var topQuery = "비트코인";
var backQuery = encodeURIComponent("비트코인");
var login_yn = "N";
var encodeType = "2";
var refCode = "";
var bucketType = "";
var name_check = "0";
var mobileDevice = "N";
var param_w = "news";
var param_da = "NTB";
var paramCfg = "";
var param_cnucc = "";
var tpl_cfg = "";
var cnucc = "";
var usrIp = "210.121.189.12";
var isDetailTab = "N";
var schSort = "";
var existMobileTabYn = "N";
var width_over_620 = "N";
var sPageLoadedmsTime =  266 ;
var isReleaseMode = '';
var isTotDebugMode = false;
var KAKAO_ACCOUNT_ID_CONNECTED = "N";
var displayInfo = {"SER":[{"code":"DNS","doc_count":10}],"SGR":[{"code":"1MV","doc_count":10},{"code":"NSJ","doc_count":0},{"code":"DCC","doc_count":0}],"SUI":[],"CUT":[]};
var usr4 = "1MV10_PSB0_NSJ0_DCC0_DNS10";
var slCallType = "sync";
var pageLoadedTime = 0;
var startTime = new Date().getTime();
var sugLocCode = "";
var searchLog = {
uc: 0,
clickCount: 0,
dl: ""
};
var SEARCHLOGDOMAIN = "\/\/sl.search.daum.net";
var CNUCC_URL = "https:\/\/harm.search.daum.net\/v2\/api\/report-harm";
var SUG_URL = "\/\/suggest.search.daum.net\/sushi\/pc\/get";
var VSUG_URL = "\/\/vmsuggest.search.daum.net\/v2\/sushi\/pc\/get";
var ASUG_URL = "\/\/ninstant.search.daum.net\/suggest\/index.daum";
var AMADO_URL = "\/\/search1.daumcdn.net\/search\/statics\/common\/js\/fe\/amado-workspace\/pc\/2.8.0\/main.js";
var SF = {
phase: "prod",
userQueryParamW: "news",
platform: "pc",
iam: {
clean: false,
geo: false,
login: false,
adult: false,
adultUrl: "https:\/\/logins.daum.net\/accounts\/loginform.do?service=adult_service\u0026url=https%3A%2F%2Fsearch.daum.net%2Fsearch%3FDA%3DNTB%26cluster%3Dy%26cluster_page%3D1%26enc%3Dutf8%26nil_search%3Dbtn%26q%3D%25EB%25B9%2584%25ED%258A%25B8%25EC%25BD%2594%25EC%259D%25B8%26realname_redirect%3D1%26w%3Dnews"
},
ua: {"ua":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36","browser":{"name":"chrome","version":{"info":"136.0.0.0","major":136,"minor":0,"patch":0}},"device":"","os":{"name":"windows","version":{"info":"10","major":10,"minor":0,"patch":0}},"platform":"pc","app":{"isDaumapp":false,"isKakao":false,"version":{"info":"","major":0,"minor":0,"patch":0}}}
};
SF.ua.app.isApp = SF.ua.app.isDaumapp;
SF.ua.os[SF.ua.os.name] = true;
SF.ua.browser[SF.ua.browser.name] = true;
SF.loadModuleList = {"amcharts":"//search1.daumcdn.net/search/statics/common/js/fe/tot-search/library/p/amcharts.20190321202015.min.js","calendar":"//search1.daumcdn.net/search/statics/common/js/fe/tot-search/module/p/calendar/module.p.calendar.20210312112039.min.js","chart":"//search1.daumcdn.net/search/statics/common/js/fe/tot-search/library/p/chart.20200602182334.min.js","kakaosdk":"//search1.daumcdn.net/search/statics/common/js/fe/tot-search/library/p/kakaosdk.20230811110443.min.js","kakaotv":"//tv.kakao.com/player/script/sdk/player_api.min.js","ks":"//search1.daumcdn.net/search/statics/common/js/fe/tot-search/module/p/ks/module.p.ks.20221122154101.min.js","pagenavigation":"//search1.daumcdn.net/search/statics/common/js/fe/tot-search/module/p/pagenavigation/module.p.pagenavigation.20220705092744.min.js","v3":"//ssl.daumcdn.net/dmaps/map_js_init/v3.js","youtube":"//www.youtube.com/player_api"};
var SD = {};
var SG = {};
var C = {};
var T = {};
var SL = {
mkeyLog: function(){},
freelog: {
send: function(){}
},
dexposeLog: {
send: function(){}
},
xscrollLog: function(){}
};
var smartLog = function(){};
</script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/tot-workspace/polyfill/p-legacy/1.4.0/main.min.js" type="text/javascript"></script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/tot-workspace/logger/1.2.0/main.js?o=p" type="text/javascript"></script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/tot-workspace/vendor/p/1.0.0/main.min.js" type="text/javascript"></script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/tot-workspace/search-log/p/1.3.0/main.min.js" type="text/javascript"></script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/tot-workspace/module/1.43.0/main.min.js?o=p" type="text/javascript"></script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/tot-workspace/library/1.38.0/remoteEntry.js?o=p" type="text/javascript"></script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/tot-workspace/runtime/1.34.0/main.min.js?o=p" type="text/javascript"></script>
<script charset="utf-8" crossorigin="anonymous" src="//search1.daumcdn.net/search/statics/common/js/fe/cubic/20250519130026/cubic.min.js?o=p" type="text/javascript"></script>
<script src="//t1.daumcdn.net/tiara/js/v1/tiara.min.js" type="text/javascript"></script>
<script type="text/javascript">
(function(SF){
SF.tiaraTracker.setDefaultConfig();
})(window.SF || {});
</script>
</meta></head>
<body class="daum windows win chrome pc">
<script type="text/javascript">
SL.mkeyLog();
</script>
<nav class="d_direct" id="daumIndex">
<a class="link_direct" href="#daumBody">본문 바로가기</a>
<a class="link_direct" href="#daumGnb">메뉴 바로가기</a>
</nav>
<div id="saq" style="display:none">비트코인</div>
<div class="sch_tab_news" id="daumWrap">
<header id="daumHead">
<div class="d_head">
<h1 class="screen_out">다음</h1>
<h2 class="screen_out">검색</h2>
<div class="inner_header" id="innerHeader">
<form class="d_sch" id="daumSearch" method="get" name="search">
<fieldset class="fld_total">
<legend class="screen_out">검색폼</legend>
<input id="nil_suggest" name="nil_suggest" type="hidden" value="btn"/>
<input id="nil_ch" name="nil_ch" type="hidden" value=""/>
<input name="rtupcoll" type="hidden" value=""/>
<input name="w" type="hidden" value="news"/>
<input name="m" type="hidden" value=""/>
<input id="f" name="f" type="hidden" value=""/>
<input name="lpp" type="hidden" value=""/>
<input name="DA" type="hidden" value="SBC"/>
<input name="sug" type="hidden" value=""/>
<input name="sq" type="hidden" value=""/>
<input name="o" type="hidden" value=""/>
<input name="sugo" type="hidden" value=""/>
<input name="cluster" type="hidden" value="y"/>
<div class="box_searchbar">
<div class="inner_searchbar">
<a class="link_service" data-target="_top" href="https://www.daum.net/" id="daumLogo" onclick='smartLog(this, "e=1&amp;dc=MLC", event);' target="_top" title="Daum 메인페이지로 가기">
<img alt="Daum" height="56" src="//search1.daumcdn.net/search/statics/common/pi/logo/logo_D112x112_241223.svg"/>
</a>
<input autocomplete="off" class="tf_keyword" id="q" maxlength="255" name="q" title="검색어 입력" type="text" value="비트코인"/>
<button class="btn_reset" id="btnResetHeader" onclick="smartLog(this, 'pg=1&amp;p=2&amp;r=1&amp;rc=1&amp;dc=SBC&amp;at=func', event);" title="검색어 지우기" type="button">
<span class="ico_ksg">입력삭제</span>
</button>
<button aria-label="가상키보드 열기" class="btn_vkey" id="VKIBtn" onclick="smartLog(this, 'pg=1&amp;p=1&amp;r=1&amp;rc=1&amp;dc=BFJ&amp;at=func', event);" title="가상키보드 열기" type="button">
<svg fill="none" height="28" width="28" xmlns="http://www.w3.org/2000/svg">
<rect height="15" rx="4" stroke="currentColor" stroke-width="2" width="24" x="2" y="6.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="6" y="9.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="9.5" y="9.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="13" y="9.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="16.5" y="9.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="20" y="9.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="6" y="13"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="9.5" y="13"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="13" y="13"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="16.5" y="13"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="20" y="13"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="6" y="16.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="9" x="9.5" y="16.5"></rect>
<rect fill="currentColor" height="2" rx=".5" width="2" x="20" y="16.5"></rect>
</svg>
</button>
<button aria-label="검색" class="btn_ksearch" id="daumBtnSearch" title="검색" type="submit">
<svg fill="currentColor" height="28" viewbox="0 0 28 28" width="28" xmlns="http://www.w3.org/2000/svg">
<path clip-rule="evenodd" d="M6 12.5C6 8.91015 8.91015 6 12.5 6C16.0899 6 19 8.91015 19 12.5C19 16.0899 16.0899 19 12.5 19C8.91015 19 6 16.0899 6 12.5ZM12.5 4C7.80558 4 4 7.80558 4 12.5C4 17.1944 7.80558 21 12.5 21C14.5006 21 16.3399 20.3088 17.7919 19.1522C17.836 19.2314 17.8916 19.3059 17.9589 19.3731L22.9589 24.3731C23.3494 24.7636 23.9826 24.7636 24.3731 24.3731C24.7636 23.9826 24.7636 23.3494 24.3731 22.9589L19.3731 17.9589C19.3059 17.8916 19.2314 17.836 19.1522 17.7919C20.3088 16.3399 21 14.5006 21 12.5C21 7.80558 17.1944 4 12.5 4Z" fill="currentColor" fill-rule="evenodd"></path>
</svg>
</button>
</div>
</div>
</fieldset>
<div class="box_suggest" id="daumSuggestTop"><div id="suggestBox"></div></div>
</form>
<div id="wrapMinidaum"></div>
</div>
<div id="daumGnb">
<div class="tab_dynamic tab_flex">
<ul class="list_tab">
<li class="">
<a class="tab_tit" href="?w=tot&amp;q=%eb%b9%84%ed%8a%b8%ec%bd%94%ec%9d%b8&amp;DA=NTB" onclick="smartLog(this, 'pg=1&amp;r=1&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event);"><span class="inner_tab">통합</span></a>
</li>
<li class="on">
<span class="screen_out">선택된 항목</span>
<a class="tab_tit" href="?w=news&amp;nil_search=btn&amp;DA=NTB&amp;enc=utf8&amp;cluster=y&amp;cluster_page=1&amp;q=%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8" onclick="smartLog(this, 'pg=1&amp;r=2&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event)">
<span class="inner_tab">
뉴스</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="?w=img&amp;nil_search=btn&amp;DA=NTB&amp;enc=utf8&amp;q=%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8" onclick="smartLog(this, 'pg=1&amp;r=3&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event)">
<span class="inner_tab">
이미지</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="?w=vclip&amp;nil_search=btn&amp;DA=NTB&amp;enc=utf8&amp;q=%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8" onclick="smartLog(this, 'pg=1&amp;r=4&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event)">
<span class="inner_tab">
동영상</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="?w=fusion&amp;nil_search=btn&amp;DA=NTB&amp;p=2&amp;q=%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8" onclick="smartLog(this, 'pg=1&amp;r=5&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event)">
<span class="inner_tab">
통합웹</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="?w=site&amp;nil_search=btn&amp;DA=NTB&amp;enc=utf8&amp;lpp=10&amp;q=%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8" onclick="smartLog(this, 'pg=1&amp;r=6&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event)">
<span class="inner_tab">
사이트</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="http://dic.daum.net/search.do?q=%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8" onclick="smartLog(this, 'pg=1&amp;r=7&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event)" target="_blank">
<span class="inner_tab">
어학사전<span class="ico_ksg ico_outlink">새창</span>
</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="https://map.kakao.com/?from=total&amp;nil_suggest=btn&amp;tab=place&amp;q=%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8" onclick="smartLog(this, 'pg=1&amp;r=8&amp;p=1&amp;rc=1&amp;dc=NTB&amp;at=more', event)" target="_blank">
<span class="inner_tab">
지도<span class="ico_ksg ico_outlink">새창</span>
</span>
</a>
</li>
</ul>
<div class="more_dynamic more_search">
<button class="btn_tab" id="gnbToggleBtn" title="더보기" type="button">
<span class="ico_ksg">더보기/접기</span>
</button>
<ul class="list_more">
<li class="">
<a class="tab_tit" href="https://100.daum.net/search/entry?q=%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8" onclick="smartLog(this, 'pg=1&amp;r=9&amp;p=2&amp;rc=1&amp;e1=NS&amp;e2=1DVZ&amp;dc=NTB&amp;at=more', event)" target="_blank">
<span class="inner_tab">
백과사전<span class="ico_ksg ico_outlink">새창</span>
</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="https://shoppinghow.kakao.com/search/%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8/&amp;srchhow=Cexpo" onclick="smartLog(this, 'pg=1&amp;r=10&amp;p=2&amp;rc=1&amp;e1=NS&amp;e2=SNPZ&amp;dc=NTB&amp;at=more', event)" target="_blank">
<span class="inner_tab">
쇼핑<span class="ico_ksg ico_outlink">새창</span>
</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="?w=book&amp;nil_search=btn&amp;DA=NTB&amp;enc=utf8&amp;q=%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8" onclick="smartLog(this, 'pg=1&amp;r=11&amp;p=2&amp;rc=1&amp;e1=NS&amp;e2=LB2Z&amp;dc=NTB&amp;at=more', event)">
<span class="inner_tab">
책</span>
</a>
</li>
<li class="">
<a class="tab_tit" href="https://www.melon.com/search/total/index.htm?q=%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8&amp;ref=W10060" onclick="smartLog(this, 'pg=1&amp;r=12&amp;p=2&amp;rc=1&amp;e1=NS&amp;e2=MS2Z&amp;dc=NTB&amp;at=more', event)" target="_blank">
<span class="inner_tab">
멜론뮤직<span class="ico_ksg ico_outlink">새창</span>
</span>
</a>
</li>
</ul>
</div>
</div>
</div>
</div>
</header>
<div id="daumContent">
<main id="cMain">
<div id="mArticle">
<div class="inner_article">
<span class="screen_out" id="daumBody">검색 본문</span>
<div class="g_comp" disp-attr="NSJ">

In [146]:
def collect_list(keyword, page=1):
    'keyword로 다음 검색한 결과(해당 page)를 return'
    url = f'https://search.daum.net/search?w=news&nil_search=btn&DA=NTB&enc=utf8&cluster=y'
    params = {'q':keyword, 'p':page}
    response = requests.get(url, params=params)
    soup = BeautifulSoup(response.text, #response.content
                    'html.parser')
    items_find_list = [] # 검색한 결과를 담을 dict list
    items_el = soup.select('div.item-title > strong.tit-g.clamp-g > a')
    for idx, item in enumerate(items_el):
        items_find_list.append({'no': idx,
                           'title': item.text,
                           'link': item.attrs['href']})
    return items_find_list
collect_list('청바지', 1)

[{'no': 0,
  'title': " '이병헌♥' 이민정, 매장 통째로 빌려 청바지 쇼핑 ",
  'link': 'http://v.daum.net/v/20250528050507783'},
 {'no': 1,
  'title': ' “추앙받을 만 하네”… 김지원, 셔츠에 청바지만 입어도 공항 ‘정지’ ',
  'link': 'http://v.daum.net/v/20250526182411395'},
 {'no': 2,
  'title': ' 흰 티셔츠에 청바지 정석대로 입는 법 ',
  'link': 'http://v.daum.net/v/20250527185425864'},
 {'no': 3,
  'title': ' 이민정, 매장 빌려 폭풍 쇼핑 "10년 전 샀던 청바지는 응급실"(MJ) ',
  'link': 'http://v.daum.net/v/20250527191015309'},
 {'no': 4,
  'title': ' ‘이병헌♥’ 이민정, 청바지 사는데 매장 통째로 빌렸다..남다른 쇼핑 클래스 “나는 즉흥적”(이민정 MJ) ',
  'link': 'http://v.daum.net/v/20250527192310643'},
 {'no': 5,
  'title': ' 이시영처럼 다리 길어보이고 싶어서 청바지 분석함 [입스타그램] ',
  'link': 'http://v.daum.net/v/20250519172231644'},
 {'no': 6,
  'title': ' \'의사 그만둔\' 고윤정, 흰 티+청바지..."정석 미녀" [★해시태그] ',
  'link': 'http://v.daum.net/v/20250522182007490'},
 {'no': 7,
  'title': ' "청렴이 최고" … 창원특례시 성산구 문화위생과, \'청바지 데이\' 추진 ',
  'link': 'http://v.daum.net/v/20250511091428626'},
 {'no': 8,
  'title': ' 패셔니스타 김지원, 청바지가 어울리는 여자랍니다! [포토] ',
  'link': 'http://v.daum.net/v/20250518220139191'},
 {'no': 9,
  'title': ' 박병은 "류준하로 3개월 활동"…청바지 모델 시절 언급 ',
  'link': 'http://v.daum.net/v/20250519190323957'}]

- 꼭 User-Agent를 사용하여야 하는 경우: https://www.melon.com/chart/

In [161]:
# 방법1
import requests
from bs4 import BeautifulSoup
url='https://www.melon.com/chart/'
melonpage = requests.get(url)
melonpage

In [162]:
# 방법2
from urllib.request import urlopen, Request
#melonpage = urlopen(url) 에러남

In [163]:
#User-Agent추가
headers={'user-agent':
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36'}
#방법2
request = Request(url, headers=headers)
melonpage = urlopen(request)
#방법1
melonpage = requests.get(url, headers=headers)
soup = BeautifulSoup(melonpage.text, #melonpage.content
                    'html.parser')
#soup

In [168]:
#멜론 순위, 가수, 노래 제목
#1위 |너에게 닿기를 |10cm  (100위까지 크롤링)
title_els = soup.select('div.ellipsis rank01 > span')
singer_els = soup.select('div.ellipsis.rank02 > span.checkEllipsis')
len([title.text.strip() for title in title_els]),\
len([singer.text for singer in singer_els])
for idx, (title, singer) in enumerate(zip(title_els, singer_els)):
    print('{}위 | {} - {}'.format(idx+1,
                                title.text.strip(),
                                singer.text))