In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import numpy as np

In [14]:
df_first = pd.read_csv('C:/ai_x/download/share/부동산/주택도시보증공사_전국 신규 민간아파트 분양가격 동향_20241231 (1).csv', encoding='cp949')
df_first.head()

  지역명                     규모구분    연도   월 분양가격(제곱미터)
0  서울                     모든면적  2015  10       5841
1  서울            전용면적 60제곱미터이하  2015  10       5652
2  서울   전용면적 60제곱미터초과 85제곱미터이하  2015  10       5882
3  서울  전용면적 85제곱미터초과 102제곱미터이하  2015  10       5721
4  서울           전용면적 102제곱미터초과  2015  10       5879

In [15]:
df_first.shape

(9095, 5)

In [16]:
df_first.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9095 entries, 0 to 9094
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   지역명         9095 non-null   object
 1   규모구분        9095 non-null   object
 2   연도          9095 non-null   int64
 3   월           9095 non-null   int64
 4   분양가격(제곱미터)  8481 non-null   object
dtypes: int64(2), object(3)
memory usage: 355.4+ KB

In [17]:
df_first.isna().sum()

지역명             0
규모구분            0
연도              0
월               0
분양가격(제곱미터)    614
dtype: int64

In [18]:
df_first.tail()

     지역명                     규모구분    연도  월 분양가격(제곱미터)
9090  제주                     모든면적  2024  8       7703
9091  제주            전용면적 60제곱미터이하  2024  8        NaN
9092  제주   전용면적 60제곱미터초과 85제곱미터이하  2024  8       7515
9093  제주  전용면적 85제곱미터초과 102제곱미터이하  2024  8        NaN
9094  제주           전용면적 102제곱미터초과  2024  8       7950

In [21]:
df_first[df_first['분양가격(제곱미터)'].isnull()]

     지역명                     규모구분    연도  월 분양가격(제곱미터)
368   광주  전용면적 85제곱미터초과 102제곱미터이하  2016  2        NaN
369   광주           전용면적 102제곱미터초과  2016  2        NaN
374   대전           전용면적 102제곱미터초과  2016  2        NaN
388   강원  전용면적 85제곱미터초과 102제곱미터이하  2016  2        NaN
421   제주            전용면적 60제곱미터이하  2016  2        NaN
...   ..                      ...   ... ..        ...
9078  전남  전용면적 85제곱미터초과 102제곱미터이하  2024  8        NaN
9081  경북            전용면적 60제곱미터이하  2024  8        NaN
9088  경남  전용면적 85제곱미터초과 102제곱미터이하  2024  8        NaN
9091  제주            전용면적 60제곱미터이하  2024  8        NaN
9093  제주  전용면적 85제곱미터초과 102제곱미터이하  2024  8        NaN

[614 rows x 5 columns]

In [23]:
pd.to_numeric(df_first['분양가격(제곱미터)'], errors='coerce', downcast = None)

0       5841.0
1       5652.0
2       5882.0
3       5721.0
4       5879.0
         ...
9090    7703.0
9091       NaN
9092    7515.0
9093       NaN
9094    7950.0
Name: 분양가격(제곱미터), Length: 9095, dtype: float64

In [24]:
pd.to_numeric(df_first['분양가격(제곱미터)'], errors='coerce', downcast = None).isna().sum()

740

In [27]:
def get_pricelen(row):
    prices=row['분양가격(제곱미터)']
    if pd.notnull(prices) and prices.strip()!=' ':
        return len(prices)
    else:
        return 0
    
get_pricelen(df_first.loc[0])

4

In [29]:
#  ★  자리수열 추가
df_first = df_first.copy()
df_first['자리수']= df_first.apply(get_pricelen, axis=1)
df_first

     지역명                     규모구분    연도   월 분양가격(제곱미터)  자리수
0     서울                     모든면적  2015  10       5841    4
1     서울            전용면적 60제곱미터이하  2015  10       5652    4
2     서울   전용면적 60제곱미터초과 85제곱미터이하  2015  10       5882    4
3     서울  전용면적 85제곱미터초과 102제곱미터이하  2015  10       5721    4
4     서울           전용면적 102제곱미터초과  2015  10       5879    4
...   ..                      ...   ...  ..        ...  ...
9090  제주                     모든면적  2024   8       7703    4
9091  제주            전용면적 60제곱미터이하  2024   8        NaN    0
9092  제주   전용면적 60제곱미터초과 85제곱미터이하  2024   8       7515    4
9093  제주  전용면적 85제곱미터초과 102제곱미터이하  2024   8        NaN    0
9094  제주           전용면적 102제곱미터초과  2024   8       7950    4

[9095 rows x 6 columns]

In [32]:
def commadrop(row):
    row = row.copy()
    price = row['분양가격(제곱미터)']
    if pd.isna(price):
        row['분양가격(제곱미터)'] == np.nan
    elif (price.strip()==' ')|(price.find(',')):
        row['분양가격(제곱미터)'] == np.nan
    else:
        row['분양가격(제곱미터)'] == price
        
    return row

In [34]:
df_first = df_first.apply(commadrop, axis=1)
df_first

     지역명                     규모구분    연도   월 분양가격(제곱미터)  자리수
0     서울                     모든면적  2015  10       5841    4
1     서울            전용면적 60제곱미터이하  2015  10       5652    4
2     서울   전용면적 60제곱미터초과 85제곱미터이하  2015  10       5882    4
3     서울  전용면적 85제곱미터초과 102제곱미터이하  2015  10       5721    4
4     서울           전용면적 102제곱미터초과  2015  10       5879    4
...   ..                      ...   ...  ..        ...  ...
9090  제주                     모든면적  2024   8       7703    4
9091  제주            전용면적 60제곱미터이하  2024   8        NaN    0
9092  제주   전용면적 60제곱미터초과 85제곱미터이하  2024   8       7515    4
9093  제주  전용면적 85제곱미터초과 102제곱미터이하  2024   8        NaN    0
9094  제주           전용면적 102제곱미터초과  2024   8       7950    4

[9095 rows x 6 columns]

In [35]:
df_first.isna().sum()

지역명             0
규모구분            0
연도              0
월               0
분양가격(제곱미터)    614
자리수             0
dtype: int64